### ISSUE TITLE
Rename this repo in xvoila or xoila

### ISSUE THREAD

**Issue by JohanMabille** [voila-dashboards/voila#1]
Othewise it cannot be the next big thing from QuantStack!

**Comment by timkpaine** [comment]
I feel like you lose some of the magic :-)
<img width="334" alt="screen shot 2018-09-13 at 10 10 45 am" src="https://user-images.githubusercontent.com/3105306/45493664-4bf47480-b73d-11e8-94cf-ba97bea52500.png">
