### ISSUE TITLE
Drop `python 3.6` and `traitlets 4` from CI test 

### ISSUE THREAD

**Issue by trungleduc** [voila-dashboards/voila#1027]
`Voila` depends heavily on `nbconvert` and `nbconvert` required minimum `python 3.7` and `traitlets 5` since version `6.1.0`. Should we drop  the configuration for testing `python 3.6` and add the test for `python 3.10`?

**Comment by trungleduc** [comment]
@jtpio should we go for it?

**Comment by jtpio** [comment]
Maybe we could start testing on 3.7 and 3.10 on CI as a first step. I'll open a PR.

**Comment by martinRenou** [comment]
Remove traitlets 4 test in https://github.com/voila-dashboards/voila/pull/1060
