### ISSUE TITLE
add github docs link to https://voila.readthedocs.io/

### ISSUE THREAD

**Issue by raybellwaves** [voila-dashboards/voila#1050]
Github has a docs input (top right of home page; see below). Would be good to link to https://voila.readthedocs.io/

<img width="335" alt="Screen Shot 2021-12-28 at 11 50 12 PM" src="https://user-images.githubusercontent.com/17162724/147628364-a87b7f3b-e1de-432e-93b8-f72df77ab685.png">

**Comment by jtpio** [comment]
Thanks @raybellwaves for the suggestion :+1: 

This should now be the case:

![image](https://user-images.githubusercontent.com/591645/147641588-983da367-ed73-430d-8d75-3f2f3ffbcfa3.png)

Closing as fixed, and https://github.com/voila-dashboards/voila/issues/787 as well.

Thanks!
