### ISSUE TITLE
Wrong documentation on RTD 

### ISSUE THREAD

**Issue by trungleduc** [voila-dashboards/voila#1061]
The stable version of the documentation on RTD is still pointing to `0.2.12`.

**Comment by trungleduc** [comment]
cc @jtpio

**Comment by jtpio** [comment]
Thanks @trungleduc for spotting this.

Looks like this might be because the `stable` branch is now lagging a bit behind?

I'll do the branch reset to see if that fixes the issue.

**Comment by jtpio** [comment]
Looking better:

![image](https://user-images.githubusercontent.com/591645/149771361-f0926122-0a22-4a63-97f6-0bb1b2f9d751.png)

Now that we don't do releases manually but with the Jupyter Releaser instead, we should look into fixing this issue to handle resetting the `stable` branch automatically: https://github.com/voila-dashboards/voila/issues/971

**Comment by trungleduc** [comment]
Fixed by #1085
