### ISSUE TITLE
Get current kernel's id/name

### ISSUE THREAD

**Issue by riegerben** [voila-dashboards/voila#1063]
Hi, im trying to get the id/name of the kernel that the code is executed on.

Is it possible?

**Comment by trungleduc** [comment]
Hi @riegerben, you can get the kernel id through the `VOILA_KERNEL_ID` environment variable.

**Comment by riegerben** [comment]
Hi! Thank you for the reply :)
I tried it but im getting None...

**Comment by trungleduc** [comment]
Are you using Voila 0.3.0? And this variable is only defined when a notebook is served with Voila.

**Comment by riegerben** [comment]
Using 0.2.10, i will update...
Thank you!

**Comment by riegerben** [comment]
Worked :) Thanks!
