### ISSUE TITLE
Display Outputs Side-by-Side

### ISSUE THREAD

**Issue by r0f1** [voila-dashboards/voila#1072]
Hi everybody,
I have two Jupyter notebook cells that produce rather large outputs. The first one is a scatter plot, the second one is a grid of small image tiles. When the user selects some points in the scatter plot, the image tiles get filtered based on what was selected.
Since the outputs are rather large, I would like to display them next to each other (instead of one below the other). 

Viewing the notebook in Jupyter, this feature is already possible, since you can display the output of a cell in a separate window and then drag that window to the right of your screen.

Is that already somehow possible with voila? If not, that would be a nice additional feature.

**Comment by trungleduc** [comment]
Hi, you can check out https://github.com/voila-dashboards/voila-gridstack. This `Voila` template allows users to configure the layout of the dashboard.

**Comment by r0f1** [comment]
Beautiful. Exactly what I was looking for. Thanks :)
