### ISSUE TITLE
Voila 0.3.x is not working with dokku server

### ISSUE THREAD

**Issue by dou-du** [voila-dashboards/voila#1088]
There seems some problem with the Voila version 0.3.x for the dokku server.  The app can be 
pushed to and built no problem on the dokku server. However, the webpage is not working 
and showing error information.

**Comment by martinRenou** [comment]
Thanks for opening an issue! Would you be able to provide those error information?

**Comment by trungleduc** [comment]
Hello, can you try the solution in this issue https://github.com/voila-dashboards/voila/issues/1047 ?

**Comment by dou-du** [comment]
> Hello, can you try the solution in this issue #1047 ?

Thank you. It is working now.
