### ISSUE TITLE
Preheat kernel module imports only

### ISSUE THREAD

**Issue by sradomski** [voila-dashboards/voila#1090]
Hey there,

first of all thank you for a very nice piece of software - your work is really appreciated!

We were evaluating the preheated mode in voila 0.3.1 and were wondering, if it is possible to **preheat the kernels per notebook with module imports only**?

### Problem

With the new preheating feature, one can supply a `voila.json` simply in the root directory of the notebooks to be served and voila will spawn some preheated kernels with the notebooks executed already (as documented [here](https://voila.readthedocs.io/en/stable/customize.html#preheated-kernels)). However, our notebooks use dynamic properties from the clients` HTTP requests that are not known up-front.

### Proposed Solution

It would be great if the kernels preheated per notebook will allow 1. for an importing of the modules at preheat-time and 2. for an actual execution at HTTP request-time. In our case, importing and initializing the various modules is expensive and passing `kernel_env_variables` via voila.json is infeasible as their values are dynamically assigned from HTTP headers.

One possible approach could be to extend the `voila.json` configuration `kernel_pools_config` with a new key, e.g.: `python_imports` = [`pandas`, `numpy`] as was discussed [here](https://github.com/voila-dashboards/voila/pull/820#issuecomment-769843227) as well.

**Comment by trungleduc** [comment]
Hello @sradomski, `Voila` has a helper function [get_query_string](https://voila.readthedocs.io/en/stable/customize.html#partially-pre-render-notebook) which allows users to get the HTML request query string at runtime. It will block the execution of notebooks in the preheated kernel at its cell and wait for an actual user to connect to Voilà. 
If you only want to pre-import libraries, you can call this function just after your import cell, e.g.

```python
import pandas
import numpy
....
from voila.utils import get_query_string
get_query_string();
# The codes from here will be executed at runtime 
```
