### ISSUE TITLE
Matplotlib widget not visible 

### ISSUE THREAD

**Issue by pmarcellino** [voila-dashboards/voila#1100]
When I run https://github.com/voila-gallery/ipympl I don't see the plots in voila. If I run it as a note book it works fine.
![image](https://user-images.githubusercontent.com/46568443/155409288-dd462089-b8cf-4d8a-8578-e8fbbf942c08.png)

- voila version 
![image](https://user-images.githubusercontent.com/46568443/155409465-120d06ff-aa1e-497d-8b5e-6fbfa5b57e30.png)
Browser Output
![image](https://user-images.githubusercontent.com/46568443/155410554-33fe06c8-999f-4598-a028-13d870e01c46.png)

### If using JupyterLab

<details><summary>Installed Labextensions</summary>
<pre>
![image](https://user-images.githubusercontent.com/46568443/155410092-493f2295-e8f7-4bb3-9605-d0640503f51c.png)
</pre>
</details>

**Comment by trungleduc** [comment]
Hello @pmarcellino, can you try this notebook with a new environment? I tried this repo with mybinder and it works well.

**Comment by jtpio** [comment]
Closing as answered since there hasn't been any replies for a couple of months.

@pmarcellino feel free to comment here or open a new ticket if you are still having issues, thanks!
