### ISSUE TITLE
asyncio blocks forever in a deadlock when running with voila

### ISSUE THREAD

**Issue by wookayin** [voila-dashboards/voila#1114]
## Description

When there are some code cells after an asyncio operation (more precisely, `await` something), the kernel blocks forever. It never procedees after showing "Executing 1 of XX".

## Reproduce

Consider the following ipython notebook with two cells:

[1]:
```
import asyncio
print("Cancelling existing task")
[t.cancel() for t in asyncio.all_tasks()]
```

[2]:
```
print("Have any code after asyncio call")
```

When you execute this under voila, it will hang in a deadlock. I see "Executing 1 of 2" forever.

## Expected behavior

The notebook can run without any problem in normal jupyter notebook.

## Context

What's interesting is, if you remove the cell [2] --- i.e., if `await` call is the last cell to execute, it doesn't block and renders OK.

### If using JupyterLab

- JupyterLab version: 3.2.8

<details><summary>Installed Labextensions</summary>
<pre>
IPython          : 7.29.0
ipykernel        : 6.5.0
ipywidgets       : 7.6.5
jupyter_client   : 7.0.6
jupyter_core     : 4.9.1
jupyter_server   : 1.13.4
jupyterlab       : 3.2.8
nbclient         : 0.5.5
nbconvert        : 6.4.4
nbformat         : 5.1.3
notebook         : 6.4.5
qtconsole        : 5.2.0
traitlets        : 5.1.1

        @jupyter-widgets/jupyterlab-manager v3.0.1 enabled OK (python, jupyterlab_widgets)
        @krassowski/jupyterlab-lsp v3.10.0 enabled OK (python, jupyterlab-lsp)
        @pyviz/jupyterlab_pyviz v2.1.0 enabled OK (python, pyviz_comms)
        @voila-dashboards/jupyterlab-preview v2.1.3 enabled OK (python, voila)
</pre>
</details>

**Comment by trungleduc** [comment]
Hello @wookayin, I don't think this is an issue of `voila`. If you execute the notebook a second time without restarting your kernel, nothing is printed. 
The problem is that your first cell will cancel the `Kernel.dispatch_queue()` task of your kernel. So any code after this call will not work.

**Comment by trungleduc** [comment]
this snippet with `await` works well with `voila`

```python

import asyncio
async def main():
    print('Hello ...')
    await asyncio.sleep(5)
    print('... World!')

await main()
print("Have any code after asyncio call")
```

**Comment by wookayin** [comment]
@trungleduc Thanks for the help and that makes a lot of sense! I wasn't ware that jupyter's rendering and interaction with user inputs have something to do with asyncio tasks.

```
In [1]: asyncio.all_tasks()

Out [1]: {<Task pending name='Task-2' coro=<Kernel.dispatch_queue() running at ...lib/python3.9/site-packages/ipykernel/kernelbase.py:457> cb=[IOLoop.add_future.<locals>.<lambda>() at .../lib/python3.9/site-packages/tornado/ioloop.py:688]>}
```

Yes, so it looks like it was my invalid use. I thought I had another similar situation where `task.cancel()` wasn't used but maybe I got it wrong.

Hope this can be helpful for someone who might accidentally run into a similar mistake. Thanks again!
