### ISSUE TITLE
Missing 'authorizer' for tornado web application 

### ISSUE THREAD

**Issue by SchmidL** [voila-dashboards/voila#1115]
## Description
When running a freshly install (all pip) - I get the following error... or that is the output and then it hangs in the nowhere
```
(E:\test) Z:\test\simplegeoscript.ipynb"
[Voila] Using C:\Users\user\AppData\Local\Temp to store connection files
[Voila] Storing connection files in C:\Users\user\AppData\Local\Temp\voila_6qdoo4ew.
[Voila] Serving static files from E:\test\lib\site-packages\voila\static.
[Voila] Voilà is running at:
http://localhost:8866/
[Voila] WARNING | Notebook simplegeoscript.ipynb is not trusted
[Voila] Kernel started: 036e54bf-a362-41d6-b67e-9947e02d1d07
E:\test\lib\site-packages\jupyter_server\auth\decorator.py:18: UserWarning: The Tornado web application does not have an 'authorizer' defined in its settings. In future releases of jupyter_server, this will be a required key for all subclasses of `JupyterHandler`. For an example, see the jupyter_server source code for how to add an authorizer to the tornado settings: https://github.com/jupyter-server/jupyter_server/blob/653740cbad7ce0c8a8752ce83e4d3c2c754b13cb/jupyter_server/serverapp.py#L234-L256
```
## Reproduce
I don't know if that helps, but I try to use voila for a geo script using geopandas. As geopandas is not so convenient installable via pip, so I use separate wheels.
```
conda activate E:\test

pip install .\GDAL-3.4.1-cp310-cp310-win_amd64.whl
pip install .\pyproj-3.3.0-cp310-cp310-win_amd64.whl
pip install .\Fiona-1.8.21-cp310-cp310-win_amd64.whl
pip install .\Shapely-1.8.1.post1-cp310-cp310-win_amd64.whl
pip install .\geopandas-0.10.2-py2.py3-none-any.whl

pip install jupyterlab voila
```
Then I just run voila simplegeoscript.ipynb

## Context

- voila version 3.3.0
- Operating System and version: Windows 10 Enterprise LTSC, 1809
- Browser and version: Chrome

**Comment by martinRenou** [comment]
This might be related to https://github.com/voila-dashboards/voila/issues/1110

**Comment by martinRenou** [comment]
That's annoying indeed. What is your jupyter-server version? Can you share your `pip list` output?

**Comment by martinRenou** [comment]
Can you please try updating jupyter-server to `1.15.6`? It looks like there were some bug fixes related to authorization in the last couple path releases https://github.com/jupyter-server/jupyter_server/releases

**Comment by SchmidL** [comment]
Perfect! now it works smoothly :)

**Comment by martinRenou** [comment]
Cool! Glad it works now :)
