### ISSUE TITLE
widgets not shown when displayed in function call

### ISSUE THREAD

**Issue by SchmidL** [voila-dashboards/voila#1116]
## Description
In a notebook I can call the creation and display of an object within a function call and everything is shown perfect, but when moving to voila, the second object is not created/shown anymore. Do I not understand the coding paradigm here or is that a bug?

## Reproduce
I give here a short code example for replication using just a button

```
import ipywidgets as widgets
### create functions
def firstBttn():
    global bttn1
    bttn1 = widgets.Button(description='first')
    display(bttn1)
    bttn1.on_click(show_secondBttn)

def create_secondBttn():
    global bttn2
    bttn2 = widgets.Button(description='second')
def show_secondBttn(*args):
    # *args to catch the remove parameter
    display(bttn2)

### call functions
firstBttn()
create_secondBttn()
```

## Context
- voila version 3.3.0
- Operating System and version: Windows 10 Enterprise LTSC, 1809
- Browser and version: Chrome

**Comment by trungleduc** [comment]
hi @SchmidL, I can not reproduce your issue. 
- If I use your snippet, in the notebook it only shows the first button, so does voila.
- if I call your `show_secondBttn`, the second button is shown on both notebook and voila.

![vlbug](https://user-images.githubusercontent.com/4451292/158967233-d21c916e-91b5-4e7e-b0a8-5368131d7966.gif)

**Comment by SchmidL** [comment]
Hi - your example is true when I want to show them upfront.

but in firstBttn() -> line 4: I add the function call of the secondBttn() on click.

And with the click the second button is created in the notebook, not in voila

**Comment by trungleduc** [comment]
Sorry, I missed the `onclick` callback, but I still can not display the second one.

![vlbug2](https://user-images.githubusercontent.com/4451292/158972489-044fe951-b601-4666-bc3c-79df3f073792.gif)

**Comment by trungleduc** [comment]
Indeed it did work with notebook classic

![vlbug3](https://user-images.githubusercontent.com/4451292/158972943-f96f00d7-75de-4ba0-8dfd-5539cf16c5ee.gif)

**Comment by trungleduc** [comment]
To make it work in jupyterlab and voila, you can use the `Output` widget:

```python
import ipywidgets as widgets
output = widgets.Output()
def firstBttn():
    global bttn1
    bttn1 = widgets.Button(description='first')
    display(bttn1, output)
    bttn1.on_click(show_secondBttn)
def create_secondBttn():
    global bttn2
    bttn2 = widgets.Button(description='second')
def show_secondBttn(*args):
    with output:
        display(bttn2)
firstBttn()
create_secondBttn()
```
![vlbug4](https://user-images.githubusercontent.com/4451292/158974463-5281e464-b4de-4e8c-bb52-19999d4bc46f.gif)
