### ISSUE TITLE
`gridspecLayout` example does not work with `ipywidgets=7.7.0`

### ISSUE THREAD

**Issue by trungleduc** [voila-dashboards/voila#1119]
## Description
`gridspecLayout.ipynb` notebook does  not work with  `voila=0.3.3` and `ipywidgets=7.7.0`. It works well in `JupyterLab` or with `ipywidgets=7.6.5` 

- `ipywidgets=7.6.5`
![ipy765](https://user-images.githubusercontent.com/4451292/159031821-eabca512-2314-44c8-aa0b-25809c2573eb.gif)

- `ipywidgets=7.7.0`
![ipy770](https://user-images.githubusercontent.com/4451292/159032698-e65f8b52-d63c-4bf0-b41c-6f39b60cc601.gif)

## Reproduce

1. Install `ipywidgets=7.7.0` and `voila=3.3.0`
2. Start `voila` with the example folder 
3. Go to `voila/render/gridspecLayout.ipynb`
```
voila.js:488 Uncaught (in promise) Error: widget model not found
    at Qt.get_model (voila.js:488:81803)
    at q (voila.js:23:209508)
    at voila.js:23:209326
    at Array.forEach (<anonymous>)
    at Object.q [as deserialize] (voila.js:23:209296)
    at Function.t._deserialize_state (voila.js:23:214684)
    at Qt.<anonymous> (voila.js:23:203604)
    at voila.js:23:199970
    at Object.next (voila.js:23:200075)
    at a (voila.js:23:198813)
```

## Expected behavior

Widget is rendered and no error is logged

## Context

- voila version `0.3.3`

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `voila` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

### If using JupyterLab
- JupyterLab version:

<details><summary>Installed Labextensions</summary>
<pre>
Paste the output from your command line running `jupyter labextension list`.
</pre>
</details>

**Comment by trungleduc** [comment]
cc @martinRenou any idea about the bug?

**Comment by trungleduc** [comment]
It seems to be related to the new `_build_models` method using the control comm channel. The `GridBoxModel` model is created before its child so it causes the `_deserialize_state` call on its child model to fail.

Creating the comms separately from the models does make it work, but I'm not sure if it defeats the improvement of the control channel.

```javascript
//manager.ts-L282

    // Start creating all widgets
    const comms: { [key: string]: base.IClassicComm } = {};
    for (const widget_id of Object.keys(states)) {
      try {
        comms[widget_id] = await this._create_comm('jupyter.widget', widget_id);
      } catch (error) {
        console.error(error);
      }
    }
    for (const [widget_id, state] of Object.entries(states) as any) {
      try {
        const comm = comms[widget_id];
        ...
```

**Comment by martinRenou** [comment]
We should look into ipywidgets's implementation of fetching widgets models and see if something differs there. I can do that for tomorrow if you want.

**Comment by trungleduc** [comment]
Thanks @martinRenou, that would be great!

**Comment by martinRenou** [comment]
I think we should make use of the (_loadFromKernel)[https://github.com/jupyter-widgets/ipywidgets/blob/7.x/packages/base/src/manager-base.ts#L402] method from the base manager, this should remove some code and will hopefully fix this issue.

**Comment by anxhelahyseni** [comment]
@trungleduc  With voila 0.3.4 and ipywidgets 7.7.0, I am facing still the same issue. 
![image](https://user-images.githubusercontent.com/17935951/159948080-f379a3a9-a911-48b7-b3a8-e640375e5967.png)

**Comment by martinRenou** [comment]
Would you be able to share a Notebook that reproduces this issue?
