### ISSUE TITLE
Voila version>0.3.0 can't render geemap

### ISSUE THREAD

**Issue by giswqs** [voila-dashboards/voila#1120]
## Description

Voila v0.3.0 can render [geemap](https://github.com/giswqs/geemap/). However, newer Voila versions can't render geemap, resulting in an empty page.  https://github.com/giswqs/geemap-heroku/issues/10

## Reproduce

Install geemap (`pip install geemap`) and create a notebook (e.g., `geemap.ipynb`) with the following content, then run `voila geemap.ipynb`. Only Voila v0.3.0 can render the map. Voila v0.3.1 or newer only shows an empty page.

```python
import geemap
m = geemap.Map(ee_initialize=False)
m
```

## Expected behavior

It should show a map like this.
![image](https://user-images.githubusercontent.com/5016453/159149056-44c8d103-974a-4083-afb7-d4d2a933875f.png)

### If using JupyterLab
- JupyterLab version: 3.3.2

<details><summary>Installed Labextensions</summary>
<pre>
JupyterLab v3.3.2
        jupyter-leaflet v0.15.0 enabled OK
        bqplot v0.5.34 enabled OK (python, bqplot)
        ipytree v0.2.1 enabled OK
        ipysheet v0.5.0 enabled OK (python, ipysheet)
        ipyevents v1.9.0 enabled OK
        jupyterlab-plotly v5.6.0 enabled OK
        @here/map-widget-for-jupyter v1.1.3 enabled OK
        @jupyter-widgets/jupyterlab-manager v3.1.0 enabled OK (python, jupyterlab_widgets)
        @voila-dashboards/jupyterlab-preview v2.1.0 enabled OK (python, voila)

</pre>
</details>

**Comment by trungleduc** [comment]
Hi @giswqs, `voila 0.3.3` is having an issue with `ipywidgets 7.7.0` (#1119 ). It tested and `geemap` works well with `voila 0.3.3` and `ipywidgets 7.6.5`

**Comment by giswqs** [comment]
@trungleduc Thank you for the insight. I look forward to the fix.

**Comment by trungleduc** [comment]
`voila 0.3.4` is released and it should fix this issue.
