### ISSUE TITLE
Ipyvuetify widgets not rendering with pre-heated kernels

### ISSUE THREAD

**Issue by sradomski** [voila-dashboards/voila#1123]
## Description

When using voila 0.3.4 with pre-heated kernels, ipywidgets will no longer render any output.

## Reproduce

Just copy this snippet into a notebook being served by voila with pre-heating enabled.

```
import ipyvuetify as v
from IPython import display
import traitlets

from voila.utils import wait_for_request
wait_for_request();

class InlineTemplate(v.VuetifyTemplate):
    template = traitlets.Unicode("""
<template>
    <h1>Test</H1>
</template>
    """).tag(sync=True)

it = InlineTemplate()
display.display(it)
```

## Expected behavior

I expect a heading "Test" to appear on the rendered html page. This is indeed the case when disabling pre-heating or when using the jupyter notebook extension. However, when served from voila with pre-heating enabled, no output is generated.

## Context

- voila version: 0.3.4
- Operating System and version: Cent OS 7
- Browser and version: tested Chrome and Safari (latest stable version)

**Comment by sradomski** [comment]
I suppose it may have something to do with network connectivity?

We run voila 0.3.4 in a kubernetes pod as a container alongside a usual jupyter notebook server on ports 8900 and 8901 respectively. We also have to specify a `base_url` for both jupyter and voila in order to be able to dispatch http and websocket requests via a reverse proxy that does oauth against a keycloak identity provider and ssl termination.

We start voila as:

```
voila \
--no-browser \
--debug \
--enable_nbextensions=True \
--port=8900 \
--Voila.ip=0.0.0.0 \
--base_url=${REVERSE_PROXY_PREFIX}/ \
--VoilaConfiguration.allow_template_override=NO \
--VoilaConfiguration.http_header_envs='REQ_HEADERS_Given_name' \
--VoilaConfiguration.http_header_envs='REQ_HEADERS_Family_name' \
--VoilaConfiguration.http_header_envs='REQ_HEADERS_Middle_name' \
--VoilaConfiguration.http_header_envs='REQ_HEADERS_Email' \
--VoilaConfiguration.http_header_envs='REQ_HEADERS_Preferred_username' \
--VoilaConfiguration.file_whitelist=".*\.png" \
--VoilaConfiguration.file_whitelist=".*\.jpg" \
--VoilaConfiguration.file_whitelist=".*\.gif" \
--VoilaConfiguration.file_whitelist=".*\.csv" \
--VoilaConfiguration.file_whitelist=".*\.txt" \
--VoilaConfiguration.file_whitelist=".*\.xls" \
--VoilaConfiguration.file_whitelist=".*\.xlsx" \
--VoilaConfiguration.file_whitelist=".*\.doc" \
--VoilaConfiguration.file_whitelist=".*\.docx" \
--VoilaConfiguration.file_whitelist=".*\.html" \
> ~/workspace/logs/voila.log 2>&1 & echo $! > ~/pids/voila.pid
```

Could you maybe detail the steps in `wait_for_request` with preheated kernels a bit? With our deployment, we had to export two environmental variables for it to work at all:

```
import os
os.environ['VOILA_BASE_URL'] = os.environ['REVERSE_PROXY_PREFIX']
os.environ['VOILA_APP_PORT'] = '8900'
```

As I understand it, this will cause a request in `wait_for_request` to `ws://127.0.0.1:8900${REVERSE_PROXY_PREFIX}/voila/query`. And I thought this is only done to expose HTTP headers and other variables as environmental variables in the pre-heated kernel from the request handler in the voila process. Is this url in anyway accessed by the HTTP client as well?

Could any of this be related to ipyvuetify widgets not rendering in our case?

**Comment by trungleduc** [comment]
Indeed I think `wait_for_request` can not connect to the WebSocket endpoint. 
> As I understand it, this will cause a request in wait_for_request to ws://127.0.0.1:8900${REVERSE_PROXY_PREFIX}/voila/query

The WebSocket connection is made from the machine running `voila` server, so normally it's behind your reverse proxy. If you can access your `voila` server internally at `127.0.0.1:8900` then you only need the `VOILA_APP_PORT` variable and not `VOILA_BASE_URL`. And these variables can be set from the `voila.json` file, you don't need to expose them in the notebook.

> Is this url in anyway accessed by the HTTP client as well?

No, it is used internally inside the server, not from the HTTP clients.

**Comment by trungleduc** [comment]
I will add connection timeout to the `ws` connection to make it easier to understand the issue for users.

**Comment by havok2063** [comment]
I'm seeing the same JSON decode error when I first start up the voila server.  I have `wait_for_request()` set to run in the 2nd cell, just after the cell with my imports.  The error triggers almost immediately upon voila server start.  

Test voila command:
```
voila --no-browser --template=embed --enable_nbextensions=True --Voila.tornado_settings="{'allow_origin': 'http://localhost:8081', 'allow_credentials': True}" --preheat_kernel=True --pool_size=3 --port=8000
```

Traceback
```
Traceback (most recent call last):
  File "/Users/bcherinka/anaconda3/envs/voila-mast2/lib/python3.8/site-packages/voila/notebook_renderer.py", line 248, in _jinja_cell_generator
    output_cell = await self.executor.execute_cell(
  File "/Users/bcherinka/anaconda3/envs/voila-mast2/lib/python3.8/site-packages/voila/execute.py", line 69, in execute_cell
    result = await self.async_execute_cell(cell, cell_index, store_history)
  File "/Users/bcherinka/anaconda3/envs/voila-mast2/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/bcherinka/anaconda3/envs/voila-mast2/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from voila.utils import wait_for_request
wait_for_request()
------------------

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/var/folders/js/s2zfzbv16019vjh0dft_l_w0000263/T/ipykernel_75788/1734290938.py in <module>
      1 from voila.utils import wait_for_request
----> 2 wait_for_request()

~/anaconda3/envs/voila-mast2/lib/python3.8/site-packages/voila/utils.py in wait_for_request(url)
    105         asyncio.get_event_loop().stop()
    106
--> 107     for k, v in json.loads(request_info).items():
    108         os.environ[k] = v
    109

~/anaconda3/envs/voila-mast2/lib/python3.8/json/__init__.py in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    339     else:
    340         if not isinstance(s, (bytes, bytearray)):
--> 341             raise TypeError(f'the JSON object must be str, bytes or bytearray, '
    342                             f'not {s.__class__.__name__}')
    343         s = s.decode(detect_encoding(s), 'surrogatepass')

TypeError: the JSON object must be str, bytes or bytearray, not NoneType
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
```

**Comment by havok2063** [comment]
Yeah, that fixed it for me, thanks!
