### ISSUE TITLE
voila(0.3.4) won't display ipywidget 

### ISSUE THREAD

**Issue by mark5907** [voila-dashboards/voila#1124]
## Description

voila won't display ipywidget anymore. 

## Reproduce

In nodebook:

```python
from ipywidgets import widgets
signal_date = widgets.DatePicker(description='date:')
display(signal_date)
```

## Expected behavior

Voila to display the dialog box

## Context

- voila version  0.3.4
- Operating System and version: Ubuntu (latestest version)
- Browser and version: chrome (99.0.4844.74)
- IPython          : 8.1.1
- ipykernel        : 6.9.1
- ipywidgets       : 7.7.0
- jupyter_client   : 7.1.2
- jupyter_core     : 4.9.2
- jupyter_server   : 1.15.6
- jupyterlab       : not installed
- nbclient         : 0.5.11
- nbconvert        : 6.4.4
- nbformat         : 5.2.0
- notebook         : 6.4.8
- qtconsole        : 5.2.2
- traitlets        : 5.1.1
- ipywidgets:  : 7.7.0

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>
<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `voila` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

### If using JupyterLab
- JupyterLab version:

<details><summary>Installed Labextensions</summary>
<pre>
Paste the output from your command line running `jupyter labextension list`.
</pre>
</details>

**Comment by mark5907** [comment]
More investigation, firefox(98.0.2) works fine

**Comment by martinRenou** [comment]
> More investigation, firefox(98.0.2) works fine

Do you mean that it works fine with Firefox 98.0.2? Were you testing with another browser for which voila did no work?

**Comment by trungleduc** [comment]
just tested, the above snippet works well with `voila=0.3.4` and `chrome=99.0.4844.82`

**Comment by mark5907** [comment]
Checked more, it works with chrome/firefox/edge now. 
The culprit is a chrome app i installed: Phantom (0.15.2). It works fine after I turn it off. Closing the issue now, thanks for checking!

**Comment by maartenbreddels** [comment]
Wondering if it could be a caching issue, do you see a JavaScript error in
the dev console, and if you tick the no not cache checkbox in the network
tab, is it fixed?

(from mobile phone)

Op do 24 mrt. 2022 08:39 schreef Duc Trung LE ***@***.***>:
