### ISSUE TITLE
Voila looks in the wrong location for an extension via CDN

### ISSUE THREAD

**Issue by timkpaine** [voila-dashboards/voila#1128]
# Description
Packages pushed to CDN may define widget/extension entrypoints other than `index.js`. 

xref: https://github.com/finos/perspective/issues/1773
voila extension loader: https://github.com/voila-dashboards/voila/blob/857eb692b1edd98ee59002fa39416df0d628f411/packages/voila/src/loader.ts#L44

# Expectation
We should inspect the [main attribute of the package.json](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#main) if possible to identify the entrypoint. 

# Context
voila version: all to date

**Comment by timkpaine** [comment]
No `dist/index.js`: https://github.com/voila-dashboards/voila/issues/882

**Comment by timkpaine** [comment]
https://github.com/voila-dashboards/voila/issues/894

**Comment by timkpaine** [comment]
https://github.com/voila-dashboards/voila/issues/892

**Comment by trungleduc** [comment]
Loading extensions from CDN is removed in 0.5.0
