### ISSUE TITLE
0.4.0 Release Plan

### ISSUE THREAD

**Issue by jtpio** [voila-dashboards/voila#1146]
### Problem

At some point we'll want to start merging breaking changes into the `main` branch.

We should then start considering making a `0.4.0` release.

### Proposed Solution

A new `0.4.0` milestone has been created: https://github.com/voila-dashboards/voila/milestone/7

We can add issues and PRs we would like to target for `0.4.0` to that milestone.

### Additional context

We can still follow the alpha -> beta -> rc -> final cycle.

Linking to the 0.3.0 Release Plan issue for reference: https://github.com/voila-dashboards/voila/issues/991

**Comment by jtpio** [comment]
Maybe the next "major" version should actually be a `1.0.0` instead of `0.4.0`, that would include bigger changes like https://github.com/voila-dashboards/voila/pull/846 and https://github.com/voila-dashboards/voila/pull/984.

Voila could then make use of the full semver range for the next releases.

**Comment by jtpio** [comment]
Based on the discussions in https://github.com/voila-dashboards/voila/pull/1206#issuecomment-1259084776 the idea would be to make a `0.4.0` release first that includes support for ipywidgets 8: https://github.com/voila-dashboards/voila/pull/1046

@martinRenou thinking we can get https://github.com/voila-dashboards/voila/pull/1197 in as well, although it doesn't have to be in `0.4.0a0` but could land in another alpha release.

Just updated the milestone to keep track of the remaining issues and PRs: https://github.com/voila-dashboards/voila/milestone/7

**Comment by jtpio** [comment]
This first alpha is out: https://github.com/voila-dashboards/voila/releases/tag/v0.4.0a0

Thanks @martinRenou!

**Comment by jtpio** [comment]
A new alpha release is now available: https://github.com/voila-dashboards/voila/releases/tag/v0.4.0a2

There is no more issue in the `0.4.0` milestone except for this one: https://github.com/voila-dashboards/voila/milestone/7

We can wait a couple of days before bumping to beta. And proceed with a release candidate and final version next week.

**Comment by jtpio** [comment]
`v0.4.0b0` is now out. No changes since `v0.4.0a2`, just the bump to beta.

The plan is to target RC and final next week if nothing comes up in the meantime,

**Comment by jtpio** [comment]
`0.4.0rc0` is now released: https://github.com/voila-dashboards/voila/releases/tag/v0.4.0rc0

**Comment by trungleduc** [comment]
`0.4.0rc1` is out now: https://github.com/voila-dashboards/voila/releases/tag/v0.4.0rc1

**Comment by jtpio** [comment]
Closing since `0.4.0` is now released: https://github.com/voila-dashboards/voila/releases/tag/v0.4.0

Thanks @martinRenou for making the final release!

**Comment by jtpio** [comment]
A follow-up would be to create a `0.4.x` branch from https://github.com/voila-dashboards/voila/commit/86d64bda6eace46760ff5ed514eee6daa09dbd77 now that https://github.com/voila-dashboards/voila/pull/846 has been merged.

**Comment by martinRenou** [comment]
Done https://github.com/voila-dashboards/voila/tree/0.4.x ! :)
