### ISSUE TITLE
Cannot build voila from source

### ISSUE THREAD

**Issue by pllim** [voila-dashboards/voila#1155]
I started see this error when trying to build voila from source. How to fix? Thanks!

```
Building wheel for voila (pyproject.toml): finished with status 'error'
...
      $ jupyter labextension build .
      An error occurred.
      ValueError: Extensions require a devDependency on @jupyterlab/builder@^3.4.1, you have a dependency on 3.3.2
```

cc @maartenbreddels

xref https://github.com/spacetelescope/jdaviz/pull/1314#issuecomment-1125179704

**Comment by jtpio** [comment]
Maybe it's an issue with the 3.4.1 release then.

Looks like https://github.com/jupyterlab/jupyterlab/pull/12533 might be relevant.

**Comment by jtpio** [comment]
Fix incoming in https://github.com/jupyterlab/jupyterlab/pull/12571.

**Comment by pllim** [comment]
Thank you!
