### ISSUE TITLE
Voila and jupyterlab-github

### ISSUE THREAD

**Issue by djangoliv** [voila-dashboards/voila#1168]
I tried to use voila with [jupyterlab-github](https://github.com/jupyterlab/jupyterlab-github) but it doesn't work.

The problem is that voila want to save the notebook before render it, but it is not possible in this case (the files are in readonly mode)

Do you think that it is possible to render the notebook without saving in this case ?

Regards

**Comment by jtpio** [comment]
Thanks @djangoliv for reporting.

Right the Voila Preview extension saves the document before opening the preview:

https://github.com/voila-dashboards/voila/blob/7d4ac99ac2e639d2fd7d38b9b4fff5364b34a5b2/packages/jupyterlab-preview/src/index.ts#L186

This should indeed handle read-only mode which can be the case also in other situations where a user can't write to the file system.

**Comment by jtpio** [comment]
Marking this one as a good first issue.

Maybe a first simple approach would be to surround the call to `context.save()` with a `try` / `catch` block. And proceed with opening the preview anyway.

**Comment by djangoliv** [comment]
The problem is still present with jupyterlab-3.6.4 and voila 0.5.0a4

- install jupyterlab==3.6.5, jupyterlab-github and voila==0.5.0a4
- open a notebook with jupyterlab-github
- click on voila button

The rendering fail with the error: Repository is readonly

![screenchot](https://github.com/voila-dashboards/voila/assets/13416971/c4de4bb4-b60e-4133-9fba-a832a259b60e)
