### ISSUE TITLE
Unable to deploy voila app using GCP

### ISSUE THREAD

**Issue by ryogi-dh** [voila-dashboards/voila#1179]
Hi,

I am using GCP to deploy the voila app and am following the instructions as mentioned in the following page:
https://voila.readthedocs.io/en/stable/deploy.html#deployment-on-google-app-engine

However, I am getting the following error:
![image](https://user-images.githubusercontent.com/109581341/182102338-4f0474f6-1329-4780-8e67-581e91470bbc.png)

I am not sure what other steps I need to follow in order to deploy it successfully. Please advise.

Regards,
Rushil Y

**Comment by trungleduc** [comment]
Hi, you will need to add `--Voila.ip=0.0.0.0` to your `entrypoint`. We will update the documentation.

**Comment by ryogi-dh** [comment]
Thank you for sharing this. I tried it and now I am getting 500: Internal Server Error. Here's my entrypoint line for reference:
`entrypoint: voila --port=$PORT --no-browser "Notebook_name.ipynb" --Voila.ip=0.0.0.0`

**Comment by ryogi-dh** [comment]
Hi,
I had not added `ipywidgets` in my requirements.txt file. After adding that it worked.
