### ISSUE TITLE
New nbconvert==6.5.1 released on Aug 9th 2022 is breaking voila notebooks the use ipydatagrid and plotly

### ISSUE THREAD

**Issue by yosbak** [voila-dashboards/voila#1186]
The setup.cfg has nbconvert>=6.4.5,<7..
This is causing automatic builds to pickup the newest release of nbconvert..

If your notebook is using  ipydatagrid or plotly widgets the notebook will fail to render.

To mitigate, I temporarily placed an explicit nbconvert==6.5.0 into the dependancy chain of my project and my notebook is again rendering correctly.

**Comment by martinRenou** [comment]
Thank you for reporting. That's really helpful! We should be making a patch release for nbconvert quickly.

**Comment by martinRenou** [comment]
nbconvert 6.5.2 should fix it. It's available on PyPi, coming soon on conda-forge.

**Comment by yosbak** [comment]
Thank you Martin.. I am amazed and impressed at how quickly this was addressed.
Regards
Joseph
