### ISSUE TITLE
voila notebook_name.ipynb produces a blank web page even though widgets show in Jupyter notebook

### ISSUE THREAD

**Issue by NikhielRahulSingh** [voila-dashboards/voila#1202]
## Reproduce

2. Click on '...'
3. Scroll down to '...'
4. See error '...'

## Context

- voila version 
- Operating System and version:
- Browser and version:

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `voila` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

### If using JupyterLab
- JupyterLab version:

<details><summary>Installed Labextensions</summary>
<pre>
Paste the output from your command line running `jupyter labextension list`.
</pre>
</details>

**Comment by OutSorcerer** [comment]
I have the same problem with 
```
jupyterlab==3.4.7
voila==0.3.6
ipywidgets==8.0.2
```

In the browser console I get

```
Error: Module @jupyter-widgets/base, semver range ^2.0.0 is not registered as a widget module...
Uncaught (in promise) Error: Module @jupyter-widgets/controls, semver range ^2.0.0 is not registered as a widget module...
```

The output of `jupyter labextension list` is 

```
JupyterLab v3.4.7
/usr/local/share/jupyter/labextensions
        jupyterlab_pygments v0.2.2 enabled OK (python, jupyterlab_pygments)
        jupyterlab-jupytext v1.3.8+dev enabled OK (python, jupytext)
        @voila-dashboards/jupyterlab-preview v2.1.6 enabled OK (python, voila)
        @jupyter-widgets/jupyterlab-manager v5.0.3 enabled OK (python, jupyterlab_widgets)
```

**Comment by martinRenou** [comment]
Voila does not support ipywidgets 8 yet. Though this has been fixed in https://github.com/voila-dashboards/voila/pull/1046 and remains to be released.

Please downgrade to ipywidgets 7 in the meantime.

Closing as fixed by https://github.com/voila-dashboards/voila/pull/1046
