### ISSUE TITLE
Issue running standalone in Docker container

### ISSUE THREAD

**Issue by ktaletsk** [voila-dashboards/voila#1228]
## Description

I am trying to create a Docker image that will run the voila in the standalone mode and serve the dashboard to the specified open port. I followed the instructions, but could not get the example dashboard loaded in my environment.

## Reproduce

1. Start Docker container. I use `jupyter/datascience-notebook` in this example as a common reference image, but I initially experienced the issue in my own different container
   ```
   docker run --rm -it -p 8888:8888 jupyter/datascience-notebook:2022-10-05 bash
   ```
2. Install the current version of voila
   ```
   pip install voila==0.3.6
   ```
3. Copy the contents of the example of notebook from https://github.com/voila-dashboards/voila/blob/main/notebooks/basics.ipynb
   ```
   nano basics.ipynb
   <paste from https://raw.githubusercontent.com/voila-dashboards/voila/main/notebooks/basics.ipynb>
   ```
4. Launch voila
   ```
   voila /home/jovyan/basics.ipynb --port 8888 --no-browser 
   ```
5. Go to browser, http://localhost:8888
6. Page does not load
![image](https://user-images.githubusercontent.com/8834829/194445927-b1a1f80b-5717-4924-9902-fed81a2ed9b1.png)

Please, excuse me if I forgot some obvious command line flag that is required in this situation.

I also checked to make sure there isn't any issue with my Docker installation or ports were open incorrectly. Since, this is a Jupyter Docker image, I was able to run `jupyter lab` and access the UI at http://localhost:8888/lab, which indicates that port 8888 was properly open and mapped between container and host.

## Expected behavior

The dashboard would show up in the browser when going to http://localhost:8888

## Context

- voila version 0.3.6
- Operating System and version: macOS 12.6
- Browser and version: Microsoft Edge 95.0.1020.53, Safari 16.0

Troubleshoot Output -- too long to paste in this issue (got error `body is too long (maximum is 65536 characters)` from GitHub)

<details><summary>Command Line Output</summary>
<pre>
[Voila] Looking for voila in /etc/jupyter
[Voila] Looking for voila in /usr/local/etc/jupyter
[Voila] Looking for voila in /opt/conda/etc/jupyter
[Voila] Looking for voila in /home/jovyan/.local/etc/jupyter
[Voila] Looking for voila in /home/jovyan/.jupyter
[Voila] Looking for voila in /home/jovyan
[Voila] using template: lab
[Voila] template paths:
	/opt/conda/share/jupyter/voila/templates/lab
	/opt/conda/share/jupyter/nbconvert/templates/lab
	/opt/conda/share/jupyter/voila/templates/base
	/opt/conda/share/jupyter/nbconvert/templates/base
	/home/jovyan/.local/share/jupyter
	/home/jovyan/.local/share/jupyter/voila/templates
	/home/jovyan/.local/share/jupyter/nbconvert/templates
	/opt/conda/share/jupyter
	/opt/conda/share/jupyter/voila/templates
	/opt/conda/share/jupyter/nbconvert/templates
	/usr/local/share/jupyter
	/usr/local/share/jupyter/voila/templates
	/usr/local/share/jupyter/nbconvert/templates
	/usr/share/jupyter
	/usr/share/jupyter/voila/templates
	/usr/share/jupyter/nbconvert/templates
[Voila] static paths:
	/home/jovyan/.local/share/jupyter/voila/templates/lab/static
	/home/jovyan/.local/share/jupyter/nbconvert/templates/lab/static
	/opt/conda/share/jupyter/voila/templates/lab/static
	/opt/conda/share/jupyter/nbconvert/templates/lab/static
	/usr/local/share/jupyter/voila/templates/lab/static
	/usr/local/share/jupyter/nbconvert/templates/lab/static
	/usr/share/jupyter/voila/templates/lab/static
	/usr/share/jupyter/nbconvert/templates/lab/static
	/home/jovyan/.local/share/jupyter/voila/templates/base/static
	/home/jovyan/.local/share/jupyter/nbconvert/templates/base/static
	/opt/conda/share/jupyter/voila/templates/base/static
	/opt/conda/share/jupyter/nbconvert/templates/base/static
	/usr/local/share/jupyter/voila/templates/base/static
	/usr/local/share/jupyter/nbconvert/templates/base/static
	/usr/share/jupyter/voila/templates/base/static
	/usr/share/jupyter/nbconvert/templates/base/static
[Voila] Using /tmp to store connection files
[Voila] Storing connection files in /tmp/voila_qqvzgand.
[Voila] Serving static files from /opt/conda/lib/python3.10/site-packages/voila/static.
[Voila] Voilà is running at:
http://localhost:8888/
WARNING:tornado.general:403 GET /voila/files/api (127.0.0.1): File not whitelisted
WARNING:tornado.access:403 GET /voila/files/api (127.0.0.1) 0.56ms
</pre>
</details>

Browser Output -- empty

**Comment by trungleduc** [comment]
Hi, at the launch Voila step, can you try with:

`voila /home/jovyan/basics.ipynb --port 8888 --Voila.ip="0.0.0.0" --no-browser `

**Comment by ktaletsk** [comment]
Perfect, that resolved it! Would you like me to update documentation somewhere to help the next person who encounter this?

**Comment by trungleduc** [comment]
It would be great if you could clarify this point on the deployment page (https://github.com/voila-dashboards/voila/blob/main/docs/source/deploy.rst)
