### ISSUE TITLE
Failed to load model class 'VBoxModel' from module '@jupyter-widgets/controls' JS error after upgrading voila to 0.4.0b

### ISSUE THREAD

**Issue by nik1097** [voila-dashboards/voila#1238]
## Description

After upgrading to voila to 0.4.0b I get the failed to load model class error. I have upgraded ipywidgets to 8.0.0. 

## Reproduce

1. Go to JupyterLab
2. Upgrade voila to 0.4.0b and ipywidgets to 8.0.0
3. Run a cell with a widget
4. JS Error

## Expected behavior

Widget must load correctly

## Context

- voila version  0.4.0b
- Operating System and version: 
- Browser and version: Chrome 99.0.4844.84 

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

### If using JupyterLab
- JupyterLab version:

<details><summary>Installed Labextensions</summary>
<pre>
Paste the output from your command line running `jupyter labextension list`.
        jupyterlab-plotly v5.10.0 enabled OK
        nbdime-jupyterlab v2.1.1 enabled OK
        ge_launcher_extension v1.4.6 enabled OK (python, ge_launcher_extension)
        @jupyter-widgets/jupyterlab-manager v5.0.3 enabled OK (python, jupyterlab_widgets)
        @jupyterlab/git v0.30.1 enabled OK (python, jupyterlab-git)
        @jupyterlab/server-proxy v3.2.2 enabled OK
        @voila-dashboards/jupyterlab-preview v2.2.0-rc.0 enabled OK (python, voila)
</pre>
</details>

**Comment by trungleduc** [comment]
**Installed Labextensions**
>         jupyterlab-plotly v5.10.0 enabled OK
>         nbdime-jupyterlab v2.1.1 enabled OK
>         ge_launcher_extension v1.4.6 enabled OK (python, ge_launcher_extension)
>         @jupyter-widgets/jupyterlab-manager v5.0.3 enabled OK (python, jupyterlab_widgets)
>         @jupyterlab/git v0.30.1 enabled OK (python, jupyterlab-git)
>         @jupyterlab/server-proxy v3.2.2 enabled OK
>         @voila-dashboards/jupyterlab-preview v2.2.0-rc.0 enabled OK (python, voila)

@nik1097 Since the `jupyterlab-plotly` does not support `ipywidgets` 8 yet, could you remove it from your environment and try `voila` again?

**Comment by nik1097** [comment]
Thank you so much! It was an issue with dependencies as you had pointed out. I managed to fix it today.
Really excited to be using the new updates!

**Comment by jmp75** [comment]
In case someone else bumps into this issue; I am trying to use  [jupyter-flex](https://github.com/danielfrg/jupyter-flex) which installs plotly, probably for its example notebooks rather than the package. I know jupyter-flex does not yet support voila <= 0.4 and/or ipywidgets 8, I am trying to see what I can contribute towards that. 

After removing plotly, I still get when launching the voila (0.4.0) server javascript errors such as

```text
Failed to load model class 'VBoxModel' from module '@jupyter-widgets/controls'
Error: Module @jupyter-widgets/controls, version ^1.5.0 is not registered, however,         2.0.0 is
```

with the following jupyterlab extensions:

```text
JupyterLab v3.4.7
/home/per202/miniconda/envs/bm/share/jupyter/labextensions
        ipyevents v2.0.1 enabled OK
        jupyter-leaflet v0.17.1 enabled OK
        bqplot v0.5.37 enabled OK (python, bqplot)
        jupyterlab_pygments v0.2.2 enabled OK (python, jupyterlab_pygments)
        ipydatagrid v1.1.13 enabled OK
        ipyurl v0.1.2 enabled OK (python, ipyurl)
        jupyterlab-jupytext v1.3.8+dev enabled OK (python, jupytext)
        ipyspin v0.1.5 enabled OK
        @voila-dashboards/jupyterlab-preview v2.0.7 enabled OK (python, voila)
        @jupyter-widgets/jupyterlab-manager v3.1.1 enabled OK (python, jupyterlab_widgets)
```
