### ISSUE TITLE
new release breaks

### ISSUE THREAD

**Issue by mfesan36** [voila-dashboards/voila#1244]
## Description
Fails to load. it stopped to work after latest update. 

## Reproduce

Failed to load model class 'TabModel' from module '@jupyter-widgets/controls'
Error: Module @jupyter-widgets/controls, version ^1.5.0 is not registered, however,         2.0.0 is

## Context

- voila version 
- Operating System and version:
- Browser and version:

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `voila` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Failed to load model class 'TabModel' from module '@jupyter-widgets/controls'
Error: Module @jupyter-widgets/controls, version ^1.5.0 is not registered, however,         2.0.0 is
</pre>
</details>

### If using JupyterLab
- JupyterLab version:

<details><summary>Installed Labextensions</summary>
<pre>
Paste the output from your command line running `jupyter labextension list`.
</pre>
</details>

**Comment by mfesan36** [comment]
Thanks Martin. That was indeed the issue!  Now it is working fine with the latest ipywidgets.

**Comment by mfesan36** [comment]
Relate issue:

My plotly graphs do not get rendered anymore. Is there a way to go back to previous version? I could not find the version number.

**Comment by martinRenou** [comment]
> My plotly graphs do not get rendered anymore

Can you provide an example that shows this? Are you using the plotly widget?

> Is there a way to go back to previous version? 

```
pip install voila==0.3.6
```
