### ISSUE TITLE
0.5.0 Release Plan

### ISSUE THREAD

**Issue by martinRenou** [voila-dashboards/voila#1245]
### Problem

`0.4.0` was out a couple of days ago and we already started merging breaking changes!

We should start considering making an `0.5.0` release.

### Proposed Solution

This is the milestone for `0.5.0` https://github.com/voila-dashboards/voila/milestone/10

We can start adding issues and PRs to it.

**Comment by martinRenou** [comment]
Thoughts about including the Voila + FPS PR into this milestone? https://github.com/voila-dashboards/voila/pull/984

**Comment by martinRenou** [comment]
The first alpha is out https://github.com/voila-dashboards/voila/releases/tag/v0.5.0a0

**Comment by mangecoeur** [comment]
Hi, I'd be interested in the FPS functionality being merged into Voila, I would be happy to help in any way I can! I'm especially interested in combing voila with FPS Auth.

**Comment by trungleduc** [comment]
@jtpio @martinRenou I opened an issue (https://github.com/voila-dashboards/voila/issues/1304) for migrating voila to lab 4.

**Comment by jtpio** [comment]
Adding https://github.com/voila-dashboards/voila/issues/539 to the milestone to have it on the radar.

We should check Voila can run offline or in self-contained mode that doesn't make requests to external services. Hopefully should be easier now with #846.

This was also brought in https://discourse.jupyter.org/t/running-voila-without-internet/13823.

**Comment by martinRenou** [comment]
0.5.0a5 is out with the JupyterLab 4 migration! https://pypi.org/project/voila/0.5.0a5

Congrats @trungleduc !

**Comment by martinRenou** [comment]
@mariobuikhuizen @maartenbreddels friendly ping :)

We just released 0.5.0a5, I wonder if you would have the same issue with this one you had before.

If you have time to test it that'd be great!

**Comment by mariobuikhuizen** [comment]
Thanks for the ping @martinRenou. For voila-vuetify and ipypopout we hook in to the internals of the voila frontend code, which has substantially changed. We have to make changes to voila-vuetify and ipypopout to make it compatible with the new frontend code. I don't think this can be fixed in voila and also isn't a defect in voila, so it shouldn't block the release of 0.5.0.

**Comment by martinRenou** [comment]
We may want to try including fixes for the following issues (that may be easy to fix with the new usage of JupyterLab mime renderers):
- https://github.com/voila-dashboards/voila/issues/516
- https://github.com/voila-dashboards/voila/issues/1159

**Comment by martinRenou** [comment]
> Adding https://github.com/voila-dashboards/voila/issues/539 to the milestone to have it on the radar.
We should check Voila can run offline or in self-contained mode that doesn't make requests to external services. Hopefully should be easier now with https://github.com/voila-dashboards/voila/pull/846.
This was also brought in https://discourse.jupyter.org/t/running-voila-without-internet/13823.

@jtpio Should we postpone this to an 0.5.1? This could be done in a backward compatible way.

**Comment by martinRenou** [comment]
Do we actually need to make it configurable? If only fontawesome is the issue, Voila could ship its version of fontawesome in the static folder (maybe done at build time and not committed in the repo), similar to what we do for https://github.com/voila-dashboards/voila/blob/main/hatch_build.py#L12

**Comment by trungleduc** [comment]
FYI I'm addressing https://github.com/voila-dashboards/voila/pull/846#discussion_r623784403

**Comment by martinRenou** [comment]
> FYI I'm addressing https://github.com/voila-dashboards/voila/pull/846#discussion_r623784403

Thanks! Wondering if that would fix https://github.com/voila-dashboards/voila/issues/516

**Comment by jtpio** [comment]
Closing as `0.5.0` has been released: https://github.com/voila-dashboards/voila/releases/tag/v0.5.0
