### ISSUE TITLE
clear_output/display different behaviour Voila (0.2.9) vs Jupyter Notebook

### ISSUE THREAD

**Issue by DiegoF90** [voila-dashboards/voila#1265]
Clearing or displaying an output widget seems to have a different behaviour on Jupyter Notebook and Voila.

I know I am sitting behind a few versions but would like to confirm if this is still an issue on newer versions (not currently able to update my env), or if it is remaining to be fixed.

I would expect the code below to show both "Text 1" and "Text 2" after every click on the checkbox. This is the behaviour seen in Jupyter Notebook but not using Voila.
In Voila both "Text 1" and "Text 2" are shown on the first click, but only "Text 2" is shown on subsequent clicks.

```
import ipywidgets as widgets 

def build_o1():
    o1 = widgets.Output()
    t1 = widgets.Label(value="Text 1")
    with o1:
        display(t1)
        print("Text 2")
    return o1

o1 = build_o1()
o2 = widgets.Output()
c1 = widgets.Checkbox(description='Show/Hide')
display(c1)
display(o2)

def c1_event_handler(obj):
    if c1.value:
        with o2:
            display(o1)
    else:
        o2.clear_output()

c1.observe(c1_event_handler, names="value")
````

- voila version 0.2.9
- Operating System and version: Windows 10
- Browser and version: Google Chrome [Version 107.0.5304.88 (Official Build) (64-bit)]

**Comment by martinRenou** [comment]
Thanks for opening an issue! 

I can confirm this is still an issue in latest Voila. Though I can also replicate this issue in JupyterLab, this might have to do with the Output widget or the widget manager. May I suggest moving this issue to the ipywidgets repository?

**Comment by DiegoF90** [comment]
Hi @martinRenou thanks for the swift reply!
Using a Jupyter Notebook, do you observe both "Text 1" and "Text 2" being correctly shown every time?
Will raise the issue in ipywidgets too. Thanks

**Comment by martinRenou** [comment]
Closing the issue here, let's follow the discussing in the jupyter-widgets repo
