### ISSUE TITLE
Make `voila` compatible with `jupyterlab` 4 

### ISSUE THREAD

**Issue by trungleduc** [voila-dashboards/voila#1304]
### Problem
Since `JupyterLab` 4.0  is just around the corner, I think for the next release (0.5.0), `voila` should be compatible with lab 4 and not lab 3. 

### Proposed Solution

- [x] Update to `jupyter-sever` 2 (https://github.com/voila-dashboards/voila/pull/1283)
- [x] Update the jupyterlab frontend components to use the 4.0.0 series, it can fix some remaining issues of https://github.com/voila-dashboards/voila/pull/846
- [ ] Use `type` when adding the preview to the `main` area. See https://github.com/jupyterlab/jupyterlab/pull/11614 for more information

**Comment by jtpio** [comment]
Posting here one of the comments from #846 which could be addressed by updating to lab 4 packages:

> We should now be able to update to the `4.0.0-alpha.x` JupyterLab packages, which include the change from https://github.com/jupyterlab/jupyterlab/pull/11537 to allow for mock services.

**Comment by jtpio** [comment]
FYI JupyterLab 4 final has been released: https://github.com/jupyterlab/jupyterlab/releases/tag/v4.0.0

**Comment by martinRenou** [comment]
We may be stuck waiting for ipywidgets to support lab 4 before being able to update Voila

**Comment by trungleduc** [comment]
for the ipywidgets PR, a simple version bump is enough?

**Comment by martinRenou** [comment]
Hopefully, some attempts have been made https://github.com/jupyter-widgets/ipywidgets/pull/3752/files

Galata needs to be updated there too

**Comment by jtpio** [comment]
As part of the update of the Voila Preview extension for JupyterLab, it would also be useful to use the `type` property when adding a preview to the `main` area. So end users could decide to open the preview in a different area if they would like to (via the settings).

This functionality was added to JupyterLab in https://github.com/jupyterlab/jupyterlab/pull/11614.
