### ISSUE TITLE
Update to webpack 5 Asset Modules

### ISSUE THREAD

**Issue by jtpio** [voila-dashboards/voila#1305]
### Problem

Currently the `@voila-dashboards/voila` package depends on Webpack 5:

https://github.com/voila-dashboards/voila/blob/c60b6c07a870ef1b03bd2e787c0fdbceef5842bf/packages/voila/package.json#L66

In Webpack 5 most of the `url-loader`, `file-loader` and others have been deprecated in favor of the Asset Modules: https://webpack.js.org/guides/asset-modules/

### Proposed Solution

We should check if Voila could drop some of the dependencies on the old loaders:

https://github.com/voila-dashboards/voila/blob/c60b6c07a870ef1b03bd2e787c0fdbceef5842bf/packages/voila/package.json#L52

https://github.com/voila-dashboards/voila/blob/c60b6c07a870ef1b03bd2e787c0fdbceef5842bf/packages/voila/package.json#L64

### Additional context

For reference JupyterLab implemented this change in https://github.com/jupyterlab/jupyterlab/pull/12350

**Comment by martinRenou** [comment]
This could probably go into a 0.5.1 release? Should we remove it from the 0.5.0 milestone?

**Comment by jtpio** [comment]
Probably the only impact would be for extension authors that expect these loaders to be there, which is why it would have been nice to clean that up for the next major release.

Although in the case of Voila the impact would probably be limited as widgets and mime renderers usually don't care about these details.

**Comment by trungleduc** [comment]
👍 on delivering this change on 0.5.0
