### ISSUE TITLE
ipydatagrid filter dropdown issue

### ISSUE THREAD

**Issue by ollyhensby** [voila-dashboards/voila#1323]
## Description

Clicking on the little filter button in a column header in a DataGrid appears to open the dropdown in the incorrect place.

Here I am using ipydatagrid 1.1.16. I also tried with versions 1.1.14 and 1.1.15 with the same issue occurring.

I also tried using voila 0.3.6 but the same issue still occurred.

![filter-issue](https://github.com/voila-dashboards/voila/assets/79875276/920e7e6b-b537-4643-b44e-9309dc90232c)

Just to add, this works fine when launched in jupyter lab.

## Reproduce

The code below produces a DataGrid which some example data.
```python
import pandas as pd
from ipydatagrid import DataGrid

df = pd.DataFrame([{"a": 1}])
DataGrid(df)
```

Launch using Voila and click on the filter button to see the issue.

## Expected behavior

Expect the dropdown when clicking the filter button to be closer to the filter button itself instead of further down the page.

## Context

- voila version: 0.4.0
- Operating System and version: WSL 2/Ubuntu 20.04
- Browser and version: Version 114.0.5735.90 (Official Build) (64-bit)

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
        /home/jovyan/mambaforge/envs/ipydatagrid-dev/bin
        /home/jovyan/mambaforge/condabin
        ...
       
sys.path:
        /home/jovyan/mambaforge/envs/ipydatagrid-dev/bin
        /home/jovyan/mambaforge/envs/ipydatagrid-dev/lib/python311.zip
        /home/jovyan/mambaforge/envs/ipydatagrid-dev/lib/python3.11
        /home/jovyan/mambaforge/envs/ipydatagrid-dev/lib/python3.11/lib-dynload
        /home/jovyan/mambaforge/envs/ipydatagrid-dev/lib/python3.11/site-packages

sys.executable:
        /home/jovyan/mambaforge/envs/ipydatagrid-dev/bin/python

sys.version:
        3.11.3 | packaged by conda-forge | (main, Apr  6 2023, 08:57:19) [GCC 11.3.0]

platform.platform():
        Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.31

which -a jupyter:
        /home/jovyan/mambaforge/envs/ipydatagrid-dev/bin/jupyter

pip list:
        Package                       Version
        ----------------------------- -----------
        aiofiles                      22.1.0
        aiosqlite                     0.19.0
        anyio                         3.7.0
        argon2-cffi                   21.3.0
        argon2-cffi-bindings          21.2.0
        asttokens                     2.2.1
        async-lru                     2.0.2
        attrs                         23.1.0
        Babel                         2.12.1
        backcall                      0.2.0
        backports.functools-lru-cache 1.6.4
        beautifulsoup4                4.12.2
        bleach                        6.0.0
        bqplot                        0.12.39
        certifi                       2023.5.7
        cffi                          1.15.1
        charset-normalizer            3.1.0
        comm                          0.1.3
        debugpy                       1.6.7
        decorator                     5.1.1
        defusedxml                    0.7.1
        entrypoints                   0.4
        exceptiongroup                1.1.1
        executing                     1.2.0
        fastjsonschema                2.17.1
        flit_core                     3.9.0
        gast                          0.4.0
        idna                          3.4
        importlib-metadata            6.6.0
        importlib-resources           5.12.0
        ipydatagrid                   1.1.16
        ipykernel                     6.23.1
        ipython                       8.13.2
        ipython-genutils              0.2.0
        ipywidgets                    8.0.6
        jedi                          0.18.2
        Jinja2                        3.1.2
        json5                         0.9.5
        jsonschema                    4.17.3
        jupyter_client                7.4.1
        jupyter_core                  5.3.0
        jupyter-events                0.6.3
        jupyter-lsp                   2.2.0
        jupyter-server                1.23.6
        jupyter_server_fileid         0.9.0
        jupyter_server_terminals      0.4.4
        jupyter_server_ydoc           0.8.0
        jupyter-ydoc                  0.2.4
        jupyterlab                    3.6.4
        jupyterlab-pygments           0.2.2
        jupyterlab_server             2.22.1
        jupyterlab-widgets            3.0.7
        MarkupSafe                    2.1.2
        matplotlib-inline             0.1.6
        mistune                       2.0.5
        nbclassic                     1.0.0
        nbclient                      0.7.4
        nbconvert                     7.4.0
        nbformat                      5.9.0
        nest-asyncio                  1.5.6
        notebook                      6.5.4
        notebook_shim                 0.2.3
        numpy                         1.24.3
        overrides                     7.3.1
        packaging                     23.1
        pandas                        2.0.2
        pandocfilters                 1.5.0
        parso                         0.8.3
        pexpect                       4.8.0
        pickleshare                   0.7.5
        pip                           23.1.2
        pkgutil_resolve_name          1.3.10
        platformdirs                  3.5.1
        prometheus-client             0.17.0
        prompt-toolkit                3.0.38
        psutil                        5.9.5
        ptyprocess                    0.7.0
        pure-eval                     0.2.2
        py2vega                       0.6.1
        pycparser                     2.21
        Pygments                      2.15.1
        pyrsistent                    0.19.3
        PySocks                       1.7.1
        python-dateutil               2.8.2
        python-json-logger            2.0.7
        pytz                          2023.3
        PyYAML                        6.0
        pyzmq                         25.1.0
        requests                      2.31.0
        rfc3339-validator             0.1.4
        rfc3986-validator             0.1.1
        Send2Trash                    1.8.2
        setuptools                    67.7.2
        six                           1.16.0
        sniffio                       1.3.0
        soupsieve                     2.3.2.post1
        stack-data                    0.6.2
        terminado                     0.17.1
        tinycss2                      1.2.1
        tomli                         2.0.1
        tornado                       6.3.2
        traitlets                     5.9.0
        traittypes                    0.2.1
        typing_extensions             4.6.2
        typing-utils                  0.1.0
        tzdata                        2023.3
        urllib3                       2.0.2
        voila                         0.4.0
        wcwidth                       0.2.6
        webencodings                  0.5.1
        websocket-client              1.5.2
        websockets                    11.0.3
        wheel                         0.40.0
        widgetsnbextension            4.0.7
        y-py                          0.5.9
        ypy-websocket                 0.8.2
        zipp                          3.15.0

conda list:
        # packages in environment at /home/jovyan/mambaforge/envs/ipydatagrid-dev:
        #
        # Name                    Version                   Build  Channel
        _libgcc_mutex             0.1                 conda_forge    conda-forge
        _openmp_mutex             4.5                       2_gnu    conda-forge
        aiofiles                  22.1.0             pyhd8ed1ab_0    conda-forge
        aiosqlite                 0.19.0             pyhd8ed1ab_0    conda-forge
        anyio                     3.7.0              pyhd8ed1ab_1    conda-forge
        argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
        argon2-cffi-bindings      21.2.0          py311hd4cff14_3    conda-forge
        asttokens                 2.2.1              pyhd8ed1ab_0    conda-forge
        async-lru                 2.0.2              pyhd8ed1ab_0    conda-forge
        attrs                     23.1.0             pyh71513ae_1    conda-forge
        babel                     2.12.1             pyhd8ed1ab_1    conda-forge
        backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
        backports                 1.0                pyhd8ed1ab_3    conda-forge
        backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
        beautifulsoup4            4.12.2             pyha770c72_0    conda-forge
        bleach                    6.0.0              pyhd8ed1ab_0    conda-forge
        bqplot                    0.12.39            pyhd8ed1ab_0    conda-forge
        brotli                    1.0.9                h166bdaf_8    conda-forge
        brotli-bin                1.0.9                h166bdaf_8    conda-forge
        bzip2                     1.0.8                h7f98852_4    conda-forge
        ca-certificates           2023.5.7             hbcca054_0    conda-forge
        certifi                   2023.5.7           pyhd8ed1ab_0    conda-forge
        cffi                      1.15.1          py311h409f033_3    conda-forge
        charset-normalizer        3.1.0              pyhd8ed1ab_0    conda-forge
        comm                      0.1.3              pyhd8ed1ab_0    conda-forge
        debugpy                   1.6.7           py311hcafe171_0    conda-forge
        decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
        defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
        entrypoints               0.4                pyhd8ed1ab_0    conda-forge
        exceptiongroup            1.1.1              pyhd8ed1ab_0    conda-forge
        executing                 1.2.0              pyhd8ed1ab_0    conda-forge
        flit-core                 3.9.0              pyhd8ed1ab_0    conda-forge
        gast                      0.4.0              pyh9f0ad1d_0    conda-forge
        idna                      3.4                pyhd8ed1ab_0    conda-forge
        importlib-metadata        6.6.0              pyha770c72_0    conda-forge
        importlib_metadata        6.6.0                hd8ed1ab_0    conda-forge
        importlib_resources       5.12.0             pyhd8ed1ab_0    conda-forge
        ipydatagrid               1.1.16             pyhd8ed1ab_0    conda-forge
        ipykernel                 6.23.1             pyh210e3f2_0    conda-forge
        ipython                   8.13.2             pyh41d4057_0    conda-forge
        ipython_genutils          0.2.0                      py_1    conda-forge
        ipywidgets                8.0.6              pyhd8ed1ab_0    conda-forge
        jedi                      0.18.2             pyhd8ed1ab_0    conda-forge
        jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
        json5                     0.9.5              pyh9f0ad1d_0    conda-forge
        jsonschema                4.17.3             pyhd8ed1ab_0    conda-forge
        jupyter-lsp               2.2.0              pyhd8ed1ab_0    conda-forge
        jupyter_client            7.4.1              pyhd8ed1ab_0    conda-forge
        jupyter_core              5.3.0           py311h38be061_0    conda-forge
        jupyter_events            0.6.3              pyhd8ed1ab_0    conda-forge
        jupyter_server            1.23.6             pyhd8ed1ab_0    conda-forge
        jupyter_server_fileid     0.9.0              pyhd8ed1ab_0    conda-forge
        jupyter_server_terminals  0.4.4              pyhd8ed1ab_1    conda-forge
        jupyter_server_ydoc       0.8.0              pyhd8ed1ab_0    conda-forge
        jupyter_ydoc              0.2.4              pyhd8ed1ab_0    conda-forge
        jupyterlab                3.6.4              pyhd8ed1ab_0    conda-forge
        jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
        jupyterlab_server         2.22.1             pyhd8ed1ab_0    conda-forge
        jupyterlab_widgets        3.0.7              pyhd8ed1ab_1    conda-forge
        ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
        libblas                   3.9.0           16_linux64_openblas    conda-forge
        libbrotlicommon           1.0.9                h166bdaf_8    conda-forge
        libbrotlidec              1.0.9                h166bdaf_8    conda-forge
        libbrotlienc              1.0.9                h166bdaf_8    conda-forge
        libcblas                  3.9.0           16_linux64_openblas    conda-forge
        libexpat                  2.5.0                hcb278e6_1    conda-forge
        libffi                    3.4.2                h7f98852_5    conda-forge
        libgcc-ng                 12.2.0              h65d4601_19    conda-forge
        libgfortran-ng            12.2.0              h69a702a_19    conda-forge
        libgfortran5              12.2.0              h337968e_19    conda-forge
        libgomp                   12.2.0              h65d4601_19    conda-forge
        liblapack                 3.9.0           16_linux64_openblas    conda-forge
        libnsl                    2.0.0                h7f98852_0    conda-forge
        libopenblas               0.3.21          pthreads_h78a6416_3    conda-forge
        libsodium                 1.0.18               h36c2ea0_1    conda-forge
        libsqlite                 3.42.0               h2797004_0    conda-forge
        libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
        libuuid                   2.38.1               h0b41bf4_0    conda-forge
        libzlib                   1.2.13               h166bdaf_4    conda-forge
        markupsafe                2.1.2           py311h2582759_0    conda-forge
        matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
        mistune                   2.0.5              pyhd8ed1ab_0    conda-forge
        nbclassic                 1.0.0              pyhb4ecaf3_1    conda-forge
        nbclient                  0.7.4              pyhd8ed1ab_0    conda-forge
        nbconvert                 7.4.0              pyhd8ed1ab_0    conda-forge
        nbconvert-core            7.4.0              pyhd8ed1ab_0    conda-forge
        nbconvert-pandoc          7.4.0              pyhd8ed1ab_0    conda-forge
        nbformat                  5.9.0              pyhd8ed1ab_0    conda-forge
        ncurses                   6.3                  h27087fc_1    conda-forge
        nest-asyncio              1.5.6              pyhd8ed1ab_0    conda-forge
        notebook                  6.5.4              pyha770c72_0    conda-forge
        notebook-shim             0.2.3              pyhd8ed1ab_0    conda-forge
        numpy                     1.24.3          py311h64a7726_0    conda-forge
        openssl                   3.1.1                hd590300_1    conda-forge
        overrides                 7.3.1              pyhd8ed1ab_0    conda-forge
        packaging                 23.1               pyhd8ed1ab_0    conda-forge
        pandas                    2.0.2           py311h320fe9a_0    conda-forge
        pandoc                    2.19.2               h32600fe_2    conda-forge
        pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
        parso                     0.8.3              pyhd8ed1ab_0    conda-forge
        pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
        pickleshare               0.7.5                   py_1003    conda-forge
        pip                       23.1.2             pyhd8ed1ab_0    conda-forge
        pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
        platformdirs              3.5.1              pyhd8ed1ab_0    conda-forge
        prometheus_client         0.17.0             pyhd8ed1ab_0    conda-forge
        prompt-toolkit            3.0.38             pyha770c72_0    conda-forge
        prompt_toolkit            3.0.38               hd8ed1ab_0    conda-forge
        psutil                    5.9.5           py311h2582759_0    conda-forge
        ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
        pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
        py2vega                   0.6.1              pyhd8ed1ab_0    conda-forge
        pycparser                 2.21               pyhd8ed1ab_0    conda-forge
        pygments                  2.15.1             pyhd8ed1ab_0    conda-forge
        pyrsistent                0.19.3          py311h2582759_0    conda-forge
        pysocks                   1.7.1              pyha2e5f31_6    conda-forge
        python                    3.11.3          h2755cc3_0_cpython    conda-forge
        python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
        python-fastjsonschema     2.17.1             pyhd8ed1ab_0    conda-forge
        python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
        python-tzdata             2023.3             pyhd8ed1ab_0    conda-forge
        python_abi                3.11                    3_cp311    conda-forge
        pytz                      2023.3             pyhd8ed1ab_0    conda-forge
        pyyaml                    6.0             py311hd4cff14_5    conda-forge
        pyzmq                     25.1.0          py311h75c88c4_0    conda-forge
        readline                  8.2                  h8228510_1    conda-forge
        requests                  2.31.0             pyhd8ed1ab_0    conda-forge
        rfc3339-validator         0.1.4              pyhd8ed1ab_0    conda-forge
        rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
        send2trash                1.8.2              pyh41d4057_0    conda-forge
        setuptools                67.7.2             pyhd8ed1ab_0    conda-forge
        six                       1.16.0             pyh6c4a22f_0    conda-forge
        sniffio                   1.3.0              pyhd8ed1ab_0    conda-forge
        soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
        stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
        terminado                 0.17.1             pyh41d4057_0    conda-forge
        tinycss2                  1.2.1              pyhd8ed1ab_0    conda-forge
        tk                        8.6.12               h27826a3_0    conda-forge
        tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
        tornado                   6.3.2           py311h459d7ec_0    conda-forge
        traitlets                 5.9.0              pyhd8ed1ab_0    conda-forge
        traittypes                0.2.1              pyh9f0ad1d_2    conda-forge
        typing-extensions         4.6.2                hd8ed1ab_0    conda-forge
        typing_extensions         4.6.2              pyha770c72_0    conda-forge
        typing_utils              0.1.0              pyhd8ed1ab_0    conda-forge
        tzdata                    2023c                h71feb2d_0    conda-forge
        urllib3                   2.0.2              pyhd8ed1ab_0    conda-forge
        voila                     0.4.0              pyhd8ed1ab_0    conda-forge
        wcwidth                   0.2.6              pyhd8ed1ab_0    conda-forge
        webencodings              0.5.1                      py_1    conda-forge
        websocket-client          1.5.2              pyhd8ed1ab_0    conda-forge
        websockets                11.0.3          py311h459d7ec_0    conda-forge
        wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
        widgetsnbextension        4.0.7              pyhd8ed1ab_0    conda-forge
        xz                        5.2.6                h166bdaf_0    conda-forge
        y-py                      0.5.9           py311hfe55011_0    conda-forge
        yaml                      0.2.5                h7f98852_2    conda-forge
        ypy-websocket             0.8.2              pyhd8ed1ab_0    conda-forge
        zeromq                    4.3.4                h9c3ff4c_1    conda-forge
        zipp                      3.15.0             pyhd8ed1ab_0    conda-forge

conda env:
        name: ipydatagrid-dev
        channels:
          - conda-forge
          - file:///mnt/conda-bld
        dependencies:
          - _libgcc_mutex=0.1=conda_forge
          - _openmp_mutex=4.5=2_gnu
          - aiofiles=22.1.0=pyhd8ed1ab_0
          - aiosqlite=0.19.0=pyhd8ed1ab_0
          - anyio=3.7.0=pyhd8ed1ab_1
          - argon2-cffi=21.3.0=pyhd8ed1ab_0
          - argon2-cffi-bindings=21.2.0=py311hd4cff14_3
          - asttokens=2.2.1=pyhd8ed1ab_0
          - async-lru=2.0.2=pyhd8ed1ab_0
          - attrs=23.1.0=pyh71513ae_1
          - babel=2.12.1=pyhd8ed1ab_1
          - backcall=0.2.0=pyh9f0ad1d_0
          - backports=1.0=pyhd8ed1ab_3
          - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
          - beautifulsoup4=4.12.2=pyha770c72_0
          - bleach=6.0.0=pyhd8ed1ab_0
          - bqplot=0.12.39=pyhd8ed1ab_0
          - brotli=1.0.9=h166bdaf_8
          - brotli-bin=1.0.9=h166bdaf_8
          - bzip2=1.0.8=h7f98852_4
          - ca-certificates=2023.5.7=hbcca054_0
          - certifi=2023.5.7=pyhd8ed1ab_0
          - cffi=1.15.1=py311h409f033_3
          - charset-normalizer=3.1.0=pyhd8ed1ab_0
          - comm=0.1.3=pyhd8ed1ab_0
          - debugpy=1.6.7=py311hcafe171_0
          - decorator=5.1.1=pyhd8ed1ab_0
          - defusedxml=0.7.1=pyhd8ed1ab_0
          - entrypoints=0.4=pyhd8ed1ab_0
          - exceptiongroup=1.1.1=pyhd8ed1ab_0
          - executing=1.2.0=pyhd8ed1ab_0
          - flit-core=3.9.0=pyhd8ed1ab_0
          - gast=0.4.0=pyh9f0ad1d_0
          - idna=3.4=pyhd8ed1ab_0
          - importlib-metadata=6.6.0=pyha770c72_0
          - importlib_metadata=6.6.0=hd8ed1ab_0
          - importlib_resources=5.12.0=pyhd8ed1ab_0
          - ipydatagrid=1.1.16=pyhd8ed1ab_0
          - ipykernel=6.23.1=pyh210e3f2_0
          - ipython=8.13.2=pyh41d4057_0
          - ipython_genutils=0.2.0=py_1
          - ipywidgets=8.0.6=pyhd8ed1ab_0
          - jedi=0.18.2=pyhd8ed1ab_0
          - jinja2=3.1.2=pyhd8ed1ab_1
          - json5=0.9.5=pyh9f0ad1d_0
          - jsonschema=4.17.3=pyhd8ed1ab_0
          - jupyter-lsp=2.2.0=pyhd8ed1ab_0
          - jupyter_client=7.4.1=pyhd8ed1ab_0
          - jupyter_core=5.3.0=py311h38be061_0
          - jupyter_events=0.6.3=pyhd8ed1ab_0
          - jupyter_server=1.23.6=pyhd8ed1ab_0
          - jupyter_server_fileid=0.9.0=pyhd8ed1ab_0
          - jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
          - jupyter_server_ydoc=0.8.0=pyhd8ed1ab_0
          - jupyter_ydoc=0.2.4=pyhd8ed1ab_0
          - jupyterlab=3.6.4=pyhd8ed1ab_0
          - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
          - jupyterlab_server=2.22.1=pyhd8ed1ab_0
          - jupyterlab_widgets=3.0.7=pyhd8ed1ab_1
          - ld_impl_linux-64=2.40=h41732ed_0
          - libblas=3.9.0=16_linux64_openblas
          - libbrotlicommon=1.0.9=h166bdaf_8
          - libbrotlidec=1.0.9=h166bdaf_8
          - libbrotlienc=1.0.9=h166bdaf_8
          - libcblas=3.9.0=16_linux64_openblas
          - libexpat=2.5.0=hcb278e6_1
          - libffi=3.4.2=h7f98852_5
          - libgcc-ng=12.2.0=h65d4601_19
          - libgfortran-ng=12.2.0=h69a702a_19
          - libgfortran5=12.2.0=h337968e_19
          - libgomp=12.2.0=h65d4601_19
          - liblapack=3.9.0=16_linux64_openblas
          - libnsl=2.0.0=h7f98852_0
          - libopenblas=0.3.21=pthreads_h78a6416_3
          - libsodium=1.0.18=h36c2ea0_1
          - libsqlite=3.42.0=h2797004_0
          - libstdcxx-ng=12.2.0=h46fd767_19
          - libuuid=2.38.1=h0b41bf4_0
          - libzlib=1.2.13=h166bdaf_4
          - markupsafe=2.1.2=py311h2582759_0
          - matplotlib-inline=0.1.6=pyhd8ed1ab_0
          - mistune=2.0.5=pyhd8ed1ab_0
          - nbclassic=1.0.0=pyhb4ecaf3_1
          - nbclient=0.7.4=pyhd8ed1ab_0
          - nbconvert=7.4.0=pyhd8ed1ab_0
          - nbconvert-core=7.4.0=pyhd8ed1ab_0
          - nbconvert-pandoc=7.4.0=pyhd8ed1ab_0
          - nbformat=5.9.0=pyhd8ed1ab_0
          - ncurses=6.3=h27087fc_1
          - nest-asyncio=1.5.6=pyhd8ed1ab_0
          - notebook=6.5.4=pyha770c72_0
          - notebook-shim=0.2.3=pyhd8ed1ab_0
          - numpy=1.24.3=py311h64a7726_0
          - openssl=3.1.1=hd590300_1
          - overrides=7.3.1=pyhd8ed1ab_0
          - packaging=23.1=pyhd8ed1ab_0
          - pandas=2.0.2=py311h320fe9a_0
          - pandoc=2.19.2=h32600fe_2
          - pandocfilters=1.5.0=pyhd8ed1ab_0
          - parso=0.8.3=pyhd8ed1ab_0
          - pexpect=4.8.0=pyh1a96a4e_2
          - pickleshare=0.7.5=py_1003
          - pip=23.1.2=pyhd8ed1ab_0
          - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
          - platformdirs=3.5.1=pyhd8ed1ab_0
          - prometheus_client=0.17.0=pyhd8ed1ab_0
          - prompt-toolkit=3.0.38=pyha770c72_0
          - prompt_toolkit=3.0.38=hd8ed1ab_0
          - psutil=5.9.5=py311h2582759_0
          - ptyprocess=0.7.0=pyhd3deb0d_0
          - pure_eval=0.2.2=pyhd8ed1ab_0
          - py2vega=0.6.1=pyhd8ed1ab_0
          - pycparser=2.21=pyhd8ed1ab_0
          - pygments=2.15.1=pyhd8ed1ab_0
          - pyrsistent=0.19.3=py311h2582759_0
          - pysocks=1.7.1=pyha2e5f31_6
          - python=3.11.3=h2755cc3_0_cpython
          - python-dateutil=2.8.2=pyhd8ed1ab_0
          - python-fastjsonschema=2.17.1=pyhd8ed1ab_0
          - python-json-logger=2.0.7=pyhd8ed1ab_0
          - python-tzdata=2023.3=pyhd8ed1ab_0
          - python_abi=3.11=3_cp311
          - pytz=2023.3=pyhd8ed1ab_0
          - pyyaml=6.0=py311hd4cff14_5
          - pyzmq=25.1.0=py311h75c88c4_0
          - readline=8.2=h8228510_1
          - requests=2.31.0=pyhd8ed1ab_0
          - rfc3339-validator=0.1.4=pyhd8ed1ab_0
          - rfc3986-validator=0.1.1=pyh9f0ad1d_0
          - send2trash=1.8.2=pyh41d4057_0
          - setuptools=67.7.2=pyhd8ed1ab_0
          - six=1.16.0=pyh6c4a22f_0
          - sniffio=1.3.0=pyhd8ed1ab_0
          - soupsieve=2.3.2.post1=pyhd8ed1ab_0
          - stack_data=0.6.2=pyhd8ed1ab_0
          - terminado=0.17.1=pyh41d4057_0
          - tinycss2=1.2.1=pyhd8ed1ab_0
          - tk=8.6.12=h27826a3_0
          - tomli=2.0.1=pyhd8ed1ab_0
          - tornado=6.3.2=py311h459d7ec_0
          - traitlets=5.9.0=pyhd8ed1ab_0
          - traittypes=0.2.1=pyh9f0ad1d_2
          - typing-extensions=4.6.2=hd8ed1ab_0
          - typing_extensions=4.6.2=pyha770c72_0
          - typing_utils=0.1.0=pyhd8ed1ab_0
          - tzdata=2023c=h71feb2d_0
          - urllib3=2.0.2=pyhd8ed1ab_0
          - voila=0.4.0=pyhd8ed1ab_0
          - wcwidth=0.2.6=pyhd8ed1ab_0
          - webencodings=0.5.1=py_1
          - websocket-client=1.5.2=pyhd8ed1ab_0
          - websockets=11.0.3=py311h459d7ec_0
          - wheel=0.40.0=pyhd8ed1ab_0
          - widgetsnbextension=4.0.7=pyhd8ed1ab_0
          - xz=5.2.6=h166bdaf_0
          - y-py=0.5.9=py311hfe55011_0
          - yaml=0.2.5=h7f98852_2
          - ypy-websocket=0.8.2=pyhd8ed1ab_0
          - zeromq=4.3.4=h9c3ff4c_1
          - zipp=3.15.0=pyhd8ed1ab_0
        prefix: /home/jovyan/mambaforge/envs/ipydatagrid-dev
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
[Voila] Looking for voila in /etc/jupyter
[Voila] Looking for voila in /usr/local/etc/jupyter
[Voila] Looking for voila in /home/jovyan/.local/etc/jupyter
[Voila] Looking for voila in /home/jovyan/.jupyter
[Voila] Looking for voila in /home/jovyan/mambaforge/envs/ipydatagrid-dev/etc/jupyter
[Voila] Looking for voila in /mnt/c/engdev/git_me/ipydatagrid-1.1.16-issue
[Voila] using template: lab
[Voila] template paths:
        /home/jovyan/mambaforge/envs/ipydatagrid-dev/share/jupyter/voila/templates/lab
        /home/jovyan/mambaforge/envs/ipydatagrid-dev/share/jupyter/nbconvert/templates/lab
        /home/jovyan/mambaforge/envs/ipydatagrid-dev/share/jupyter/voila/templates/base
        /home/jovyan/mambaforge/envs/ipydatagrid-dev/share/jupyter/nbconvert/templates/base
        /home/jovyan/mambaforge/envs/ipydatagrid-dev/share/jupyter
        /home/jovyan/mambaforge/envs/ipydatagrid-dev/share/jupyter/voila/templates
        /home/jovyan/mambaforge/envs/ipydatagrid-dev/share/jupyter/nbconvert/templates
        /home/jovyan/.local/share/jupyter
        /home/jovyan/.local/share/jupyter/voila/templates
        /home/jovyan/.local/share/jupyter/nbconvert/templates
        /usr/local/share/jupyter
        /usr/local/share/jupyter/voila/templates
        /usr/local/share/jupyter/nbconvert/templates
        /usr/share/jupyter
        /usr/share/jupyter/voila/templates
        /usr/share/jupyter/nbconvert/templates
[Voila] static paths:
        /home/jovyan/mambaforge/envs/ipydatagrid-dev/share/jupyter/voila/templates/lab/static
        /home/jovyan/mambaforge/envs/ipydatagrid-dev/share/jupyter/nbconvert/templates/lab/static
        /home/jovyan/.local/share/jupyter/voila/templates/lab/static
        /home/jovyan/.local/share/jupyter/nbconvert/templates/lab/static
        /usr/local/share/jupyter/voila/templates/lab/static
        /usr/local/share/jupyter/nbconvert/templates/lab/static
        /usr/share/jupyter/voila/templates/lab/static
        /usr/share/jupyter/nbconvert/templates/lab/static
        /home/jovyan/mambaforge/envs/ipydatagrid-dev/share/jupyter/voila/templates/base/static
        /home/jovyan/mambaforge/envs/ipydatagrid-dev/share/jupyter/nbconvert/templates/base/static
        /home/jovyan/.local/share/jupyter/voila/templates/base/static
        /home/jovyan/.local/share/jupyter/nbconvert/templates/base/static
        /usr/local/share/jupyter/voila/templates/base/static
        /usr/local/share/jupyter/nbconvert/templates/base/static
        /usr/share/jupyter/voila/templates/base/static
        /usr/share/jupyter/nbconvert/templates/base/static
[Voila] Using /tmp to store connection files
[Voila] Storing connection files in /tmp/voila_7g41tcd9.
[Voila] Serving static files from /home/jovyan/mambaforge/envs/ipydatagrid-dev/lib/python3.11/site-packages/voila/static.
[Voila] serving directory: '/mnt/c/engdev/git_me/ipydatagrid-1.1.16-issue'
[Voila] Voilà is running at:
http://localhost:8866/
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
:8866/voila/ipydatagrid.js:1     Failed to load resource: the server responded with a status of 404 (Not Found)
4loader.js:60 Falling back to https://cdn.jsdelivr.net/npm/ for ipydatagrid@^1.1.16
</pre>
</details>

### If using JupyterLab
- JupyterLab version: 3.6.4

<details><summary>Installed Labextensions</summary>
<pre>
JupyterLab v3.6.4
/home/jovyan/mambaforge/envs/ipydatagrid-dev/share/jupyter/labextensions
        jupyterlab_pygments v0.2.2 enabled OK (python, jupyterlab_pygments)
        bqplot v0.5.40 enabled OK (python, bqplot)
        ipydatagrid v1.1.16 enabled OK
        @jupyter-widgets/jupyterlab-manager v5.0.7 enabled OK (python, jupyterlab_widgets)
        @voila-dashboards/jupyterlab-preview v2.2.0 enabled OK (python, voila)
</pre>
</details>

**Comment by Benjamin-Setzer** [comment]
I have the same issue. When viewing our app in raw jupyterlab, the grid works as intended. In a notebook or voila, the bug shows itself.
I also tried going down to ipydatagrid 1.1.13, and the bug persists.
This is the oldest version we had used, and back then, the bug didnt show.
Which is weird, and leads me to the suspision that maybe something in browsers changed.
Tested in an uptodate Chrome and Edge.

**Comment by chuckmandu** [comment]
Duplicate of https://github.com/voila-dashboards/voila/issues/930 wherein a fix is proposed.

**Comment by jgunstone** [comment]
just to confirm - 
this is still an issue in 0.5.0a5
![image](https://github.com/voila-dashboards/voila/assets/21370980/37fe7416-82ab-49e7-ac5a-bb5cbc80414b)


but fine in jlab
![image](https://github.com/voila-dashboards/voila/assets/21370980/891dc560-cfc9-4b19-9b09-a0f511b92778)

**Comment by jgunstone** [comment]
this is still an issue in [v0.5.0rc0](https://github.com/voila-dashboards/voila/releases/tag/v0.5.0rc0)

<img width="887" alt="image" src="https://github.com/voila-dashboards/voila/assets/21370980/eb2135f4-0674-41e8-83b1-414594927fed">


i tested on jupyterlab==4.0.3 and ==4.0.5

**Comment by trungleduc** [comment]
From @jtpio's comment (https://github.com/voila-dashboards/voila/issues/930#issuecomment-924062075), it looks like an issue of  `ipydatagrid` and not on `Voila` side.

**Comment by jgunstone** [comment]
https://github.com/bloomberg/ipydatagrid/issues/422

**Comment by ollyhensby** [comment]
Fixed here: https://github.com/bloomberg/ipydatagrid/pull/441
