### ISSUE TITLE
Review added

### ISSUE THREAD

**Issue by repo-reviews** [voila-dashboards/voila#1332]
### Thank you for building **voila**!

I created the following review on [repo-reviews.github.io](https://repo-reviews.github.io) to share my experience using **voila**.

### Review

**Title**: Reviewing Viola for Python

[link to review](https://repo-reviews.github.io//reviews/2023-06-20_SAMarcon_Voila-Dashboards_voila)

If you would like to help your users share their experiences using your repo, add a [badge](https://github.com/repo-reviews/repo-reviews.github.io#add-badges) to your README.md.

I hope these learnings help your users **increase their productivity**.

--
Please be kind,
I’m a human!

**Comment by maartenbreddels** [comment]
Thank you, that was a nice review. Note that you typed Viola instead of Voila at https://repo-reviews.github.io/

Maybe render.com is a better alternative for heroku.

**Comment by repo-reviews** [comment]
thanks, just fixed it :)

@SAMarcon

**Comment by SAMarcon** [comment]
Great thanks.
