### ISSUE TITLE
Voila Perspective error

### ISSUE THREAD

**Issue by Armadik** [voila-dashboards/voila#1347]
## Description
i use this notebook https://github.com/finos/perspective/blob/master/examples/jupyter-notebooks/widget_tutorial.ipynb
After I start the viola. I get an error:

```
[Open Browser Console for more detailed log - Double click to close this message]
Failed to load model class 'PerspectiveModel' from module '@finos/perspective-jupyterlab'
Error: Script error for "@finos/perspective-jupyterlab"
http://requirejs.org/docs/errors.html#scripterror
    at makeError (https://jupyterhub/user/test/voila/static/require.min.js:1:1067)
    at HTMLScriptElement.onScriptError (https://jupyterhub/user/test/voila/static/require.min.js:1:13218)
```
Although the perspective-python package itself works in the standard jupiterlab interface. This can be seen in the screenshot.

## Reproduce

![image](https://github.com/voila-dashboards/voila/assets/50964282/b6231c72-13e4-404e-ac03-9ee34d4daafe)

## Expected behavior

Widget works in viola

## Context

perspective-python        2.2.1              pyh1a96a4e_1    conda-forge
jupyterlab                3.6.5              pyhd8ed1ab_0    conda-forge
voila                     0.4.1              pyhd8ed1ab_0    conda-forge

**Comment by trungleduc** [comment]
Hi, the next release of Voila (which will be released soon™) will support JupyterLab extensions, so if the widget works in JupyterLab, I will work in Voila.

**Comment by martinRenou** [comment]
We're getting closer to the final 0.5.0. Just tested with voila=0.5.0b1 and it works nicely indeed:

![Screenshot from 2023-08-03 14-47-31](https://github.com/voila-dashboards/voila/assets/21197331/617306bf-ddf3-468a-84c9-9f48102c7814)
