### ISSUE TITLE
VoilaMarkdownRenderer.image() got an unexpected keyword argument 'url'

### ISSUE THREAD

**Issue by jiboncom** [voila-dashboards/voila#1360]
## Description

Voila fails to render markdown cells with images.

## Reproduce

Add an image using markdown to a notebook and try to run it on Voila.
```
![](extras/example.jpg)
```

Voila returns:
`TypeError: VoilaMarkdownRenderer.image() got an unexpected keyword argument 'url'`

## Expected behavior

Parse the cell and the notebook.

## Context

Tried it using Github Actions and on my Windows laptop using Voila 0.5.0a3 and before (I need this for Voici).  

<details><summary>Browser Output</summary>
Nothing except "Ok, voila is still executing..."

**Comment by martinRenou** [comment]
This should be fixed in 0.4.3
