### ISSUE TITLE
"MIME type ('text/plain') is not executable" error on latest Chrome

### ISSUE THREAD

**Issue by eyalk11** [voila-dashboards/voila#1388]
This causes extensions not to run . It works in edge and Firefox. 

```
Refused to execute script from 'http://localhost:8866/voila/labextensions/@jupyter-widgets/jupyterlab-manager/static/remoteEntry.98b8a827bfc5f86e95d2.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
```

This is the root cause: 

![image](https://github.com/voila-dashboards/voila/assets/72234965/af45e137-924b-4a11-8167-9ddd708546a1)

I tried the solution here :
https://github.com/jupyterlab/jupyterlab/issues/6098

Still not working in chrome. Also tried to downgrade to notebook 5.7.5 .

https://github.com/bloomberg/ipydatagrid/issues/435 
(has some more details , including versions)

**Comment by eyalk11** [comment]
Interestingly, the same thing works in my VM

**Comment by eyalk11** [comment]
OK, after doing restarts (?) it seems to be solved.

**Comment by KiARC** [comment]
Currently having the same issue on Firefox
