### ISSUE TITLE
Download rendered HTML

### ISSUE THREAD

**Issue by svaidyans** [voila-dashboards/voila#1391]
### Problem
Foremost thanks for a wonderful tool!

I am trying to automate verification of outputs of Python test assignments.  I would like to have a Download option as command line parameter to save the rendered html file locally. 

### Proposed Solution
Kindly see if it is possible to have this feature...for example, something like this:
```
voila <notebook> --strip_sources=False --download_file="<filename>.html"
```

### Additional context
Thanks in advance for considering this.

**Comment by martinRenou** [comment]
Would using nbconvert directly be an option for you?

**Comment by svaidyans** [comment]
Wow! Excellent.  Thank you - this works perfectly and suits my needs.  Appreciate your quick response.

**Comment by svaidyans** [comment]
Wow! Excellent.  Thank you - this works perfectly and suits my needs.  Appreciate your quick response.
