### ISSUE TITLE
display(Javascript(....)) no effect in a widget button click

### ISSUE THREAD

**Issue by timiil** [voila-dashboards/voila#1399]
## Description

hello, we are trying invoke some js in a widget button clicked event

## Reproduce

```
import IPython
from IPython.display import display, Javascript, HTML
import ipywidgets as widgets

js = """
<script>
    function test() {
        document.querySelector('input[type=text]').value = 'Hello from JavaScript';
    }
</script>
"""

text_widget = widgets.Text(description="Text:")

button = widgets.Button(description="Set Text")
display(HTML(js), text_widget, button)

def on_button_click(b):
    display(Javascript("test();"))

button.on_click(on_button_click)
```

in normal Juypter Notebook mode, the button work well, but in voila page mode, the button click does not do anyting, no browser error.
voila command is here:
```
voila --version
0.4.3

voila --Voila.tornado_settings="{'allow_origin': '*'}" --Voila.base_url=/voila_8703/ --port=8703 tools/test.ipynb
```

do anything that i had missed ? thanks for any help !

**Comment by maartenbreddels** [comment]
Hi,

I think this also does not work in Jupyter Lab. We do not know where to place it. I think if you use an output widget, you can do:
```python
output = widgets.Output()

display(HTML(js), text_widget, button, output)
def on_button_click(b):
    with output:
        display(Javascript("test();"))
```

Let us know if this helps.

I think a cleaner way of doing this is using https://ipyvuetify.readthedocs.io/en/latest/template_usage.html or AnyWidget where you can put javascript in a widget.

**Comment by timiil** [comment]
> Hi,
> 
> I think this also does not work in Jupyter Lab. We do not know where to place it. I think if you use an output widget, you can do:
> 
> ```python
> output = widgets.Output()
> 
> display(HTML(js), text_widget, button, output)
> def on_button_click(b):
>     with output:
>         display(Javascript("test();"))
> ```
> 
> Let us know if this helps.
> 
> I think a cleaner way of doing this is using https://ipyvuetify.readthedocs.io/en/latest/template_usage.html or AnyWidget where you can put javascript in a widget.

Thanks for you kindly help :), It is work by using the Output widget. Thanks you.
