### ISSUE TITLE
Allow for other kernel_spec_manager classes

### ISSUE THREAD

**Issue by ClaytonAstrom** [voila-dashboards/voila#1403]
### Problem

kernel_spec_manager is hardcoded to a jupyter_client KernelSpecManager instance, not allowing for async or other managers - https://github.com/voila-dashboards/voila/blob/main/voila/app.py#L547

### Proposed Solution

* Expose the top level `kernel_spec_manager` to the `VoilaConfiguration`

**Comment by martinRenou** [comment]
Thank you for opening an issue! Making this configurable could be nice indeed. Would you be willing to try opening a PR for this?
