### ISSUE TITLE
Voila - path traversal vulnerability

### ISSUE THREAD

**Issue by sustarun** [voila-dashboards/voila#1438]
## Description

We have a voila instance on a linux server which has been detected for path traversal vulnerability.
Anyone faced this before?
Would like to know any possible solution to it.

## Context

- voila version: 0.4.1
- Operating System and version: RedHat Linux 7.9
- Browser and version: Chrome v119

**Comment by martinRenou** [comment]
Thank you for opening an issue @sustarun.

Would you be able to send me an email at martin.renou@quantstack.net with more information about what you've found? I'll make sure to have the relevant people on the email thread.

Closing this issue for now. Thank you.
