### ISSUE TITLE
Remove usage of `ADMIN_GITHUB_TOKEN` for releasing with the Jupyter Releaser

### ISSUE THREAD

**Issue by jtpio** [voila-dashboards/voila#1449]
The Jupyter Releaser updated its example workflows to use a GitHub App instead of relying on the `ADMIN_GITHUB_TOKEN`: https://github.com/jupyter-server/jupyter_releaser/blob/89be0fbdc13f47011c95a870218c18d94c4f193b/example-workflows/publish-release.yml#L24

For reference this is already in use in some other Jupyter projects, for example Jupyter Server: https://github.com/jupyter-server/jupyter_server/blob/69361eeb2702572faca6e6cc8ac1003e393eb5aa/.github/workflows/publish-release.yml#L24

We could start doing the same for the repos under the `voila-dashboards` organization, following the guide: https://jupyter-releaser.readthedocs.io/en/latest/how_to_guides/convert_repo_from_repo.html#checklist-for-adoption

**Comment by jtpio** [comment]
Opened PRs on several repos currently using the releaser:

- https://github.com/voila-dashboards/voila/pull/1453
- https://github.com/voila-dashboards/voila-gridstack/pull/223
- https://github.com/voila-dashboards/voici/pull/114

@martinRenou @trungleduc are there any other repos in the `voila-dashboards` org using the releaser?

**Comment by trungleduc** [comment]
Thanks @jtpio for working on it, https://github.com/voila-dashboards/voila-topbar still uses the admin token

**Comment by jtpio** [comment]
OK thanks, just opened https://github.com/voila-dashboards/voila-topbar/pull/11

**Comment by jtpio** [comment]
`ADMIN_GITHUB_TOKEN` has now been removed from the org secrets.

The new credentials for the GitHub app have been added to the Jupyter 1Password (cc @martinRenou as SSC rep for Voila)
