### ISSUE TITLE
voila.json file is not taken into account

### ISSUE THREAD

**Issue by djangoliv** [voila-dashboards/voila#1468]
The doc say:
The easiest way to change these settings is to provide a file named voila.json in the same folder containing the notebooks. 

But I notice that it is especially necessary to launch "voila" from the directory containing the voila.json file.

If you have the directory $HOME/app which contains index.ipynb and voila.json:

```
cd $HOME/app
voila index.ipynb   # works

```
```
cd /tmp
voila $HOME/app/index/ipynb  # doesn't work (the config file is not taken into account)

```

therefore the documentation is false. 
But, it would be better to correct the code so that the documentation becomes valid.
Even better, an option to indicate where the configuration file is located at launch.

Regards

**Comment by trungleduc** [comment]
Thanks for reporting the issue. It's more of a documentation issue since the current behavior is consistent with other Jupyter applications. 
A PR fixing this is very welcome!

**Comment by djangoliv** [comment]
Thanks for your response @trungleduc .

I understand the point of view, but on the other hand I think it would really be better to consider the voila.json file if it is next to the notebook. It would allow
- to have a complete directory representing an application (with its dependencies and its configuration)
and more important:
- to take into account the configuration in the case of the jupyterlab extension (jupyterlab-preview). Indeed, in the current state of affairs I don't see how to add a template (like flex or vuetify-default) when launching the extension.

Here a screenshot with @voila-dashboards/jupyterlab-preview (the voila.json **is not** taken into account)

![image](https://github.com/voila-dashboards/voila/assets/13416971/3bdd2334-ce3b-448a-88ba-b463bc688dfe)

Here the voila launch in the directory (the voila.json **is** taken into account)

![image](https://github.com/voila-dashboards/voila/assets/13416971/24c4a0d6-21a0-40e4-8e45-e1f638ec5603)

**Comment by trungleduc** [comment]
It will be the same behavior as `voila`, i.e. il will look for the config file in the current working directory and all jupyter paths

```python
config_file_paths = [os.getcwd(), *jupyter_config_path()]
```

**Comment by djangoliv** [comment]
Thank you very much for all this time @trungleduc .

I still mention my use case which motivated me to open this issue to share.

I'm building a sort of app library.
Several examples accessible from the same instance of jupyterlab (each example in its dedicated directory).
Some of these examples depend on different templates (flex, voila-vuetify, ...) and/or different kernels.

Unfortunately, in the current state, I will not be able to keep a different configuration for each example in a simple way. I imagine I will have to overwrite the configuration file before running each example.

I will continue to look for a simple solution.

Regards

**Comment by trungleduc** [comment]
Both template and kernel can be set in the notebook's metadata, and voila will read the config in each notebook, e.g. https://voila.readthedocs.io/en/stable/customize.html#controlling-the-nbconvert-template
