### ISSUE TITLE
It isn't possible to write a template that wraps "rendered_cells"

### ISSUE THREAD

**Issue by paddymul** [voila-dashboards/voila#1480]
## Description

After/during the call to `main.ts:    await app.start()` the rendered dom to `<div id="rendered_cells">` is reinserted into the page DOM at the bottom of `body`.

It should be possible to specify the parent of `<div id="rendered_cells">` via config or templates.

## Reproduce

Render an example notebook with `template=classic` then inspect the dom after the page has rendered.

The classic template has the following lines:
```
{% block body_header %}
<body data-base-url="{{resources.base_url}}voila/" data-voila="voila">
  {{ spinner.html() }}
  {{ voila_setup_helper_functions() }}
  <div tabindex="-1" id="notebook" class="border-box-sizing">
    <div class="container" id="notebook-container">
      <div id="rendered_cells" style="display: none">
```
but it renders like this 
<img width="551" alt="Screenshot 2024-07-15 at 10 29 53 AM" src="https://github.com/user-attachments/assets/8c590942-31ee-4caf-85d8-165c20a484b5">

## Expected behavior
I would first expect the template to just render cells to `<div id="rendered_cells">`

second I would expect to be able to specify `hostID` via pageConfig.  I will work on a PR for this

## Context

- voila version 
- Operating System and version:
- Browser and version:

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `voila` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

### If using JupyterLab
- JupyterLab version:

<details><summary>Installed Labextensions</summary>
<pre>
Paste the output from your command line running `jupyter labextension list`.
</pre>
</details>

**Comment by trungleduc** [comment]
Hi @paddymul, I'm curious about your use case. In Voila 0.5.0 you have an application shell (similar to JupyterLab) and you can create a JupyterLab extension targeting Voila to modify the rendered page (e.g https://github.com/voila-dashboards/voila-topbar). 

Do these options fulfill your needs?

**Comment by paddymul** [comment]
I could do something like that.  That solution is much more complex than the previous functionality of just editting the template and wrapping `<div id="rendered_cells" style="display: none">`.  Additionally, I think it's confusing to include a template like classic, and have `<div id="rendered_cells"` show up not in its location inside of template dom, but randomly appended somewhere else to `body`.

At a minimum this behavior should be documented.

Expecting users to write a jupyterlab extension to do something that should be templatized is a big stretch.

Maybe you could have a default value for `hostID` that is overrideable in VoilaConfiguration. 
The dom injection seems to be controlled by https://github.com/voila-dashboards/voila/blob/main/packages/voila/src/main.ts#L142 which is where you could pass in a different value for `hostID`.  Make the included templates include that default `hostID` in their markup.  Then users of Voila would have a much more straightforward path to implementing wrapping.

**Comment by trungleduc** [comment]
> I could do something like that. That solution is much more complex than the previous functionality of just editting the template

I agree, but simultaneously it gives users more possibilities to modify the rendered dashboard.

> I think it's confusing to include a template like classic

The classic template is going to be removed in the next release.

> Maybe you could have a default value for hostID that is overrideable in VoilaConfiguration.

We are aiming to have a JupyterLab-compatible application shell. Adding this feature would break the shell functionalities.

**Comment by trungleduc** [comment]
Close as not planned
