### ISSUE TITLE
Broken rendering of math/LaTeX using HTMLMath widget since 0.5.5

### ISSUE THREAD

**Issue by akielbowicz** [voila-dashboards/voila#1486]
Hello!
First of all, thanks for this tool it is awesome.

## Description

`HTMLMath` widget has not rendered Math/LaTeX content correctly since `0.5.5`. 

<img width="960" alt="repro-0 5 5-bad" src="https://github.com/user-attachments/assets/eef21090-88ab-48b7-9b3d-94f8cacc52fb">

Going back to `0.5.4` it renders OK.

<img width="960" alt="repro-0 5 4-ok" src="https://github.com/user-attachments/assets/9e2d5b02-a15d-497d-b7ed-66bc4bbae3b6">

From the changelog, #1410 might have introduced the issue.

## Reproduce

Create a notebook with the following content (or download [repro.ipynb](https://github.com/akielbowicz/ipywidgets-playground/blob/voila-issue/voila-issue/repro.ipynb
))

```python
from ipywidgets import HTMLMath
HTMLMath("Some text with math $E = m c^2$")
```

```sh
python -m venv .venv
# activate venv 
python -m pip install voila==0.5.5 ipywidgets jupyterlab
voila repro.ipynb
```

## Expected behavior

Math/LaTeX content of HTMLMath widget renders correctly.

## Context

- voila version 0.5.5, 0.5.6, 0.5.7
- Operating System and version: Tested on Windows 10/11 and within a docker container
- Browser and version: Edge, Librewolf, Brave

**Comment by trungleduc** [comment]
Thanks for reporting. I will work on it
