### ISSUE TITLE
custom labextension path?

### ISSUE THREAD

**Issue by dfguerrerom** [voila-dashboards/voila#1494]
I was navigating through the documentation and the code but I couldn't find an answer to the following.

My group has a system where we have a `jupyter server` running from where users can launch some voila applications, for each app, we set the kernel that the app has to use and it is then launched.
The problem surges when there's a tool that needs a new labextension which is not installed in the system library, causing the `no version of module xxx is registered`.

By running `jupyter --path` I know that the registered extensions are located at:

```
    /home/username/.local/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
```

I know I can `export JUPYTER_PATH=` var to add the folder of the venv that I'm using, but it won't solve my issue because the server is already running, I cannot change that...

Is there a way to set this path in a different way? or is there a way to use the `cdn` ?

**Comment by trungleduc** [comment]
It's not possible to set the lab extension paths dynamically. 
What we can do is to relax this [`fullLabextensionsUrl`](https://github.com/voila-dashboards/voila/blob/0ffd12ae476d843fa7f4f66c1f19e8cef41f1eeb/voila/utils.py#L100) to make it configurable. Then you can host your extension assets independently of `voila` and update them without touching voila server

**Comment by dfguerrerom** [comment]
I need this feature, and I could start a PR.
I thought that `fullLabextensionsUrl` would be the only entry point used afterwards to handle the extensions but not, to get the metadata from the extensions there's another call to the filesystem https://github.com/voila-dashboards/voila/blob/0ffd12ae476d843fa7f4f66c1f19e8cef41f1eeb/voila/utils.py#L114 ... 
To propose a generic solution I was thinking on adapting or adding  `gcp` method to work directly with the server instead of the filesystem, in which scenario I would have to add some directory listing methods to the server and adapt the logic.
What do you think about it?
