### ISSUE TITLE
Adding a release date alongside the release tag would be useful

### ISSUE THREAD

**Issue by joshy** [voila-dashboards/voila#1513]
### Problem
Browsing the page https://voila.readthedocs.io/en/stable/changelog.html lists all the releases however it is impossible to know when the release was done. For example release 0.5.8 is it from yesterday, last month or last year? 

### Suggested Improvement

Adding the release date to the version would show how active the project is and each visitors sees recent activity. I for example don't know which version I am using (out of my head) but I have a sense that it is a version from probably 6 month ago. A suggestion would be 0.5.8 / 2024-10-18. Or any other format or style would be fine as long as it is recognized as a date. Or maybe 0.5.8 (released on 2024-10-18).

**Comment by martinRenou** [comment]
It would indeed be a nice improvement 👍🏽 May I suggest moving this issue to https://github.com/jupyter-server/jupyter_releaser as we're using that module to build our releases and the changelo?

This would benefit many other projects

**Comment by joshy** [comment]
@martinRenou Thanks for considering it. Should I create a feature request on jupyter_releaser or can you move that this issue over to jupyter_releaser? Both fine with me.

**Comment by jtpio** [comment]
Not sure we can move issue across orgs. But if you open a new one there and copy paste the original message, it would be totally fine. Thanks!
