### ISSUE TITLE
Better handle tab-closing (closing kernels)

### ISSUE THREAD

**Issue by SylvainCorlay** [voila-dashboards/voila#173]
I am currently seeing some python errors in the terminal with respect to closing websockets.

**Comment by b060149ee** [comment]
I want the same thing.

I use Jupyter Lab and usually render my notebooks in voila using the "Render with voila" button available in the toolbar. 

As each user's session is different and a separate kernel is opened for each session - can we please close the kernel when a voila tab is closed in Jupyter Lab? Currently, the only way to actually close voila kernels is by clicking 'Close and Shutdown' in the File Menu of the Jupyter Lab which is not intuitive. So auto-close of kernels on voila tab close is appreciated.

I understand this is not - for example a notebook's kernel behaves. But notebook kernels are shown in the 'Running' section. So either show the voila kernels in the 'Running' section or auto-close them on tab close. Thanks.

And I'm a big fan of Voila!! :)
