### ISSUE TITLE
Template names homogeneity

### ISSUE THREAD

**Issue by martinRenou** [voila-dashboards/voila#194]
Some template files have the `.html` extension, others have the `.tpl` extension. We should have the same extension everywhere.

**Comment by SylvainCorlay** [comment]
Yep, tornado templates have the `html` extension and the nbconvert have `tpl` extension.

Originally they were in the same directory and we used the extension to distinguish. This will be fixed with the template system refactor.

**Comment by maartenbreddels** [comment]
Fixed in #208
