### ISSUE TITLE
Local html image links are "broken" in markdown output

### ISSUE THREAD

**Issue by AaronWatters** [voila-dashboards/voila#225]
I see that a related issue has been closed, but I'm (re)adding this anyway because I don't think I can recommend voila to my users unless markdown works the same in voila and notebook/lab:

When I try voila with a notebook that has references to local images the images are broken:

<img width="418" alt="Screen Shot 2019-06-12 at 8 58 39 AM" src="https://user-images.githubusercontent.com/13857252/59353165-5bb2e080-8cf0-11e9-9e2f-530d5e10d834.png">

The notebook I tried is here:

https://github.com/AaronWatters/jp_doodle/blob/master/notebooks/workshop/Set%20up%20verification.ipynb

The image links use standard HTML markup, not markdown

`<img src="button.png" width="200"/>`

**Comment by SylvainCorlay** [comment]
Hi @AaronWatters!

The reason why these images are not displayed is that unlike the notebook app, `voila` does not serve the content of the directory of the notebook, which may contain "private" information such as the source code powering the app, or other resources (data stored in files next to the notebook).

The case of markdown image tags is handled by inlining the images in the rendered HTML.

**Comment by SylvainCorlay** [comment]
There might be means to process the information in the HTML, and look for image tags to inline them...

**Comment by AaronWatters** [comment]
Would there be a way to "whitelist" all image MIME types and similar things like CSS and text in the web server configuration?

**Comment by jtpio** [comment]
@AaronWatters did you get any chance to try the latest versions of Voila? (which adds support for whitelists)

https://voila.readthedocs.io/en/latest/customize.html#serving-static-files

**Comment by maartenbreddels** [comment]
I'm assuming this is solved, if not, please reopen.
