### ISSUE TITLE
ERROR:asyncio:Task exception was never retrieved

### ISSUE THREAD

**Issue by hainm** [voila-dashboards/voila#237]
hi,
I am trying voila (latest release from conda-forge). It's pretty nice.
The error is not serious but I still see a series of warning/error in terminal: 

```
[Voila] Kernel shutdown: 82a56940-98ac-4280-9376-41f2d80fbe27
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /scr2/nguyen/miniconda3/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/scr2/nguyen/miniconda3/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scr2/nguyen/miniconda3/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
WARNING:tornado.general:Got events for closed stream None
```

cheers

**Comment by maartenbreddels** [comment]
Yeah, thansk for opening this issue, I've almost become blind to that warning. My guess is this is an issue upstream in jupyter_server. In any case, we keep this open until fixes.

**Comment by jtpio** [comment]
This seems to be triggered by:

https://github.com/voila-dashboards/voila/blob/919d57db3a143566009853f27ca05131c4b23da7/share/jupyter/voila/templates/default/static/main.js#L44

The `shutdown` call doesn't make it to the server all the time (especially with Firefox), which leads to other issues such as memory consumption (as already mentioned in https://github.com/voila-dashboards/voila/issues/173, https://github.com/voila-dashboards/voila/issues/209, https://github.com/voila-dashboards/voila/issues/479).

But when it does, a request to shut down the kernel is sent over Websocket, but the browser tab is closed immediately after, closing the WS connection abruptly.

**Comment by maartenbreddels** [comment]
So the websocket is closed from the browser side before the shutdown is send, maybe the shutdown call is async?

**Comment by jtpio** [comment]
Yes it looks like it is:

https://github.com/jupyterlab/jupyterlab/blob/f5e5b0e50873042c101e913c1403aab5c8b9447c/packages/services/src/kernel/default.ts#L456-L465

**Comment by jtpio** [comment]
We might actually want to dispose the kernel with `kernel.dispose()` in the `beforeunload` handler, which should clear the socket properly.

**Comment by jtpio** [comment]
Opened https://github.com/voila-dashboards/voila/pull/525.
