### ISSUE TITLE
ipympl example not properly working

### ISSUE THREAD

**Issue by martinRenou** [voila-dashboards/voila#251]
The ipympl example https://github.com/matplotlib/jupyter-matplotlib/blob/master/examples/ipympl.ipynb does not seem to work properly with Voila. I assume some CSS is missing, I'm not sure the issue comes from Voila or ipympl.

I installed the ipympl package with `conda install -c conda-forge ipympl`

Result with voila:
![ipympl-voila](https://user-images.githubusercontent.com/21197331/59590375-32c58d80-90ec-11e9-8087-9bf4ed71c1ee.png)

Result in a classic notebook:
![ipympl](https://user-images.githubusercontent.com/21197331/59590384-39ec9b80-90ec-11e9-8e7a-b4188c077368.png)

**Comment by SylvainCorlay** [comment]
The styling of the header and  buttons in the classic notebook is from boorstrap.js.

Voila is in line with jlab on this.

Eventually we ahould change ipympl to use ipywidget's css.

**Comment by SylvainCorlay** [comment]
Ah the second plot not showing on voila appears to be a race condition also occuring randomly in jlab and classic.

**Comment by martinRenou** [comment]
> the second plot not showing on voila appears to be a race condition also occuring randomly

Mmmh, the second plot always shows up in the classic Notebook. And it never shows up on voila for me...

Could it be related to the subplots?

**Comment by martinRenou** [comment]
It does show up when putting the second figure alone in a Notebook

**Comment by SylvainCorlay** [comment]
> Could it be related to the subplots?

No, I have other examples using a subplot that work well.

**Comment by SylvainCorlay** [comment]
> It does show up when putting the second figure alone in a Notebook

Could you try creating separate figure for the three examples?

**Comment by whimian** [comment]
When I'm using `jupyter-matplotlib` and `Voila`, I get `404 GET /voila/jupyter-matplotlib.js`.

**Comment by jtpio** [comment]
@whimian did you start Voila with the `--enable_nbextensions=True` option?

**Comment by jtpio** [comment]
@martinRenou is this still an issue? The ipympl should now work fine with Voila (at least it does on Binder)

**Comment by martinRenou** [comment]
I guess we can close it. The CSS issue should not appear in latest ipympl.
