### ISSUE TITLE
Custom develop command to link data files in setup.py

### ISSUE THREAD

**Issue by jtpio** [voila-dashboards/voila#255]
We can add a custom develop command to the `setup.py` to automatically link data files, as mentioned in https://github.com/QuantStack/voila/pull/253#issuecomment-502971527.

This would help with the development workflow and make the process more automated.

**Comment by vidartf** [comment]
Please note that the solution linked will break the `-e` install command on Windows due to CPython's poor symlink support on Windows. At the very least, please put the `symlink` call in a try/except clause :)

**Comment by jtpio** [comment]
Ah good to know :)

Maybe there is a better way to do it so it's more robust on Windows?

**Comment by vidartf** [comment]
I have one PR on Windows symlink support for CPython that was merged, and one that is still open. If you put the symlink call in a try/except clause, with the current behavior as fallback, that is likely the best way. Then, the symlinking should just work once CPython gets better support.

**Comment by maartenbreddels** [comment]
Could you link to the PR @vidartf ?
Will this be backported to Python3.6/3.7?

**Comment by vidartf** [comment]
> Will this be backported to Python3.6/3.7

No, I cannot believe it will (unless I have misunderstood how CPython works). I don't think it will be backported to 3.8 either, and given the speed things are going, I doubt it will be in for 3.9...

**Comment by vidartf** [comment]
Either way, it won't work on *all* Windows machines, so the try/except clause would still be needed no matter what.

**Comment by maartenbreddels** [comment]
What should we do instead, give a warning saying you should run it in admin mode? And if not possible (user cannot have admin right), what should a user do, just do a normal `pip install .`?

**Comment by vidartf** [comment]
You could just make a helper script (possibly an entry point) that does the copy for you, and ask the user to run that when the datafiles change.

**Comment by maartenbreddels** [comment]
Why not rerun `pip install .`? Would that be too slow?

**Comment by vidartf** [comment]
Sure, you could tell the user to:
- Either configure the symlinks themselves outside of Python (maybe list dirs that need to be linked).
- Or run `pip install .` for every change to the datafiles (preferably specifying what will trigger a change of theses)

**Comment by jtpio** [comment]
Closing as this was implemented as a hatch plugin in https://github.com/voila-dashboards/voila/pull/1197.
