### ISSUE TITLE
How do I make voila aware of multiple kernels?

### ISSUE THREAD

**Issue by xguse** [voila-dashboards/voila#324]
It only seems to see the default "python 3" kernel. Can I provide a list of kernels that I want it to "know" about?

**Comment by xguse** [comment]
OK I think that I figured this out but I would like to now post it here for confirmation that I am on the right track.

1. enter the virtual environment where you installed `voila`
2. run `jupyter kernelspec install /path/to/kernel` --sys-prefix
3. Confirm it worked with `jupyter kernelspec list`

**Comment by SylvainCorlay** [comment]
@xguse thanks for posting here.

Voila works with all jupyter kernels. There is an example with the xeus-cling C++ kernel.

Voila naturally picks the kernel specified in the notebook metadata.

**Comment by xguse** [comment]
@SylvainCorlay: Not always, I am afraid. 

I installed voila into its own conda env and am serving a notebook created using another conda env. Voila knows about its kernel and not the one from the notebook. I had to do what I mentioned above to inform the jupyter in the voila env about the kernel that the notebook was created in. 

**DEF** not an automatic process.

**Comment by SylvainCorlay** [comment]
@xguse the "automatic support" for kernels of other conda environments is not a Jupyter feature.

You are probably using the anaconda distribution that ships the [nb_conda_kernel](https://github.com/Anaconda-Platform/nb_conda_kernels) package.

nb_conda_kernel is an extension to the notebook server to make it aware of conda environments and it seems that it has not been updated to work with jupyter_server.
