### ISSUE TITLE
JS event when all cells have been rendered to page?

### ISSUE THREAD

**Issue by timkpaine** [voila-dashboards/voila#338]
I'm trying to hook in a materialize init of some select elements, but i need to know that they've been placed on the page first:

https://materializecss.com/select.html
@martinRenou (https://github.com/martinRenou/voila-material)

Also will be useful for a custom loading screen.

**Comment by timkpaine** [comment]
My workaround right now will be to inject a bit of javascript into the last cell of a notebook which create and emits a custom event.

As far as real solutions are concerned, would it make sense to emit an event when we receive the final "kernel idle" message from the last cell? This would let the front end know when the webpage is ready. I could then attach some javascript to this to initialize materialize, or to hide my loading screen, etc.

**Comment by jtpio** [comment]
Maybe something that can be achieved with progressive rendering? https://github.com/QuantStack/voila/pull/133

**Comment by timkpaine** [comment]
@jtpio I can try it but I was hoping to ship all the javascript at the beginning, if need be it looks like i can send a script block after the last execute and it will definitely be synchronous?

**Comment by maartenbreddels** [comment]
I think indeed that #133 should have per cell rendering, and call some js function that can show/update a progress bar, or some custom code. Would that solve your problem?

**Comment by timkpaine** [comment]
@maartenbreddels i think so!
