### ISSUE TITLE
Is there a way to detect that notebook is displayed in voila?

### ISSUE THREAD

**Issue by jodzga** [voila-dashboards/voila#342]
I am running into the issues where Altair charts do not display correctly when using voila. They do look ok in JupyterLab though. In order to make it work I need to use a different renderer. I could do it programmatically if I could detect that notebook is being displayed in voila. Is there any way to do that?

**Comment by maartenbreddels** [comment]
I think you can do it front-end only, e.g. what @mariobuikhuizen did for ipyvuetify is this:
https://github.com/mariobuikhuizen/ipyvuetify/blob/master/js/src/jupyterEnvironment.js
(basically you want `scriptExists('/voila/static/main.js')`)

Note that is may change soon to `/static/voila/main.js'.

I hope this helps.

**Comment by jtpio** [comment]
@jodzga it would also be interesting to know what kind of issue you are facing with Altair when using voila (feel free to open a new issue for that).

**Comment by jodzga** [comment]
@jtpio It is really the same problem as https://github.com/QuantStack/voila/issues/166
With default renderer charts are displayed as:
```
<VegaLite 3 object>

If you see this message, it means the renderer has not been properly enabled
for the frontend that you are using. For more information, see
https://altair-viz.github.io/user_guide/troubleshooting.html
```
Chart does render correctly in voila with `kaggle` renderer but then it does not render at all in JupyterLab. Perhaps I could solve it somehow by creating a custom template for voila but then preview buttons in JupyetrLab would not work again.

**Comment by jtpio** [comment]
ok, thanks for pointing to the other issue.

**Comment by jeffyjefflabs** [comment]
See also https://github.com/jupyter/nbconvert/issues/913.  There's a suggestion in the comments `get_ipython().get_parent()['content']['allow_stdin']` that returns True in Jupyter proper and False in Voila.  I agree that feels brittle so it might be nice to have a more "official" solution, probably upstream in nbconvert.  I don't have a specific use case for it but an idea that comes to mind is you might want to have more verbose output when you run interactively and less verbose in the dashboard.

**Comment by maartenbreddels** [comment]
With the latest alpha, you can check if voila is being used a the kernel side:
https://github.com/voila-dashboards/voila/blob/056e59accff2313c4ef7fe782524954e3f4f567b/voila/handler.py#L76

I hope that solved it, if not, please reopen.
