### ISSUE TITLE
Voila mode button renders blank page when clicked twice

### ISSUE THREAD

**Issue by deeplook** [voila-dashboards/voila#344]
When I create a notebook and click on the "Voila" button in the Jupyter notebook (classic) toolbar one time I get a new browser tab with that notebook rendered by voila as expected. When I click on the same button again I another tab opens, apparantly with the same URL, presumably trying to render the same thing, but never shows anything else, but a blank page. Tested in Firefox Quantum 69.0b8.

**Comment by jtpio** [comment]
Thanks for the report @deeplook.

This seems to be working fine when testing on Binder: https://mybinder.org/v2/gh/QuantStack/voila/stable?urlpath=tree%2Fnotebooks/basics.ipynb

Running Firefox Quantum 68.0.1.

**Comment by jtpio** [comment]
Closing, as this seems to be working fine on Binder (see comment above).

@deeplook feel free to comment here if you're still seeing the issue (or add a screencast)
