### ISSUE TITLE
does voila allow to get message from frontend?

### ISSUE THREAD

**Issue by hainm** [voila-dashboards/voila#346]
hi all,

I've been developing a feature in nglview for movie making of the trajectory snapshots.
Basically the backend will send 3D coordinates to frontend for rendering, the frontend will send back the image data (base64) to backend; once the backend got the image data, it will again send the next coordinates for next rendering.

I want to use `voila` to run the notebook app until it finished to get the movie output. However, it seems that voila does not allow the message from frontend. Is this correct? If yes, can voila have an option to allow that (which is similar to --enable_nbextensions=True).

thanks
PS: [The nglview feature is here](https://github.com/arose/nglview/pull/842#issue-304981667) and [related code is here](https://github.com/arose/nglview/blob/master/nglview/contrib/movie.py#L216)

**Comment by jtpio** [comment]
Right, voila doesn't allow arbitrary code execution (execute requests). Only the following message types:

https://github.com/QuantStack/voila/blob/21db1c318eb222f391fceb0ed4e6fc8670e0b6b3/voila/app.py#L378-L383

However this doesn't seem to be the case in this example (at first glance).
Maybe you have an example notebook / Binder we could use to see what is happening in voila?

**Comment by hainm** [comment]
hi @jtpio,
Can you please try this: https://mybinder.org/v2/gh/hainm/nglview/voila?filepath=notebooks%2Fmovie_making.ipynb

I don't know how to run voila there but everything you need is already included.

**Comment by jtpio** [comment]
@hainm thanks for sharing this, will have a look.

To run voila on Binder you can use the server extension endpoint: https://mybinder.org/v2/gh/hainm/nglview/voila?urlpath=voila/render/notebooks%2Fmovie_making.ipynb

**Comment by hainm** [comment]
thanks @jtpio. 

One possible explanation is that voila is trying to execute code from the the notebook cells before displaying the view. In my case, the view must be displayed before calling the movie maker.

**Comment by hainm** [comment]
Probably related to this issue: https://github.com/QuantStack/voila/issues/142

**Comment by hainm** [comment]
oops, likely not. I change the code a bit to only executing the movie making if a button clicked, but that does not help.



```python
from IPython.display import *
from ipywidgets import *
```


```python
import nglview as nv
from nglview.contrib.movie import MovieMaker
import pytraj as pt

traj = pt.load(nv.datafiles.XTC, nv.datafiles.PDB)[:5]
view = nv.show_pytraj(traj, default=False)
view.center()
view.add_surface('protein', opacity=0.5, color='residueindex')
view.control.orient([15.69986420582941,
 114.8276262266868,
 48.816742057652796,
 0,
 -18.22863682402078,
 -46.5629522451937,
 115.38869989652724,
 0,
 123.43490126182644,
 -21.481422658119275,
 10.831316500165215,
 0,
 -39.1268284890941,
 -46.69809684423501,
 -44.63013982367478,
 1])



movie = MovieMaker(view, in_memory=True, output='abc.gif')

def make(b):
    movie.make()
    
button = Button(description='click me')
button.on_click(make)

view
```

```python
display(button), display(movie._progress)
```

**Comment by jtpio** [comment]
> Probably related to this issue: #142

Yes. Also the notebook will display an error after running it with `Restart and run all`, since the animation is being asynchronously generated and not ready yet.

**Comment by hainm** [comment]
Hi,

How’s about my example above that uses the button click to generate the
animation?

**Comment by jtpio** [comment]
That should work.

Are you running voila in standalone mode with the `enable_nbextensions` flag enabled?

`voila --enable_nbextensions=True`

**Comment by hainm** [comment]
Yes, standalone mode (by running voila in terminal). 

I don’t recall I used enable_nbextensions=True but how does this help? I can see the rendering but the movie animation does not work.

**Comment by maartenbreddels** [comment]
the last example you pasted works fine here.

**Comment by hainm** [comment]
hi @maartenbreddels, that does not work in my computer with voila 0.1.9.

Here is the screenshot after 1 minute after I clicked the button. The expectation is the progress bar should be updated.

![voila](https://user-images.githubusercontent.com/4451957/63442453-223dd600-c401-11e9-9418-87575427b982.png)

**Comment by hainm** [comment]
here is correct behavior in the notebook ,where the progress bar is updated.
![voila1](https://user-images.githubusercontent.com/4451957/63442615-692bcb80-c401-11e9-9d78-a3d367959268.png)

**Comment by jtpio** [comment]
@hainm any updates on this or still the same issue?

**Comment by hainm** [comment]
Do you mean I should try the latest voila and report here? The issue happened with voila 0.1.9.

**Comment by jtpio** [comment]
Yes just to know if this was still an issue.

**Comment by hainm** [comment]
thanks @jtpio, [this example](https://github.com/voila-dashboards/voila/issues/346#issuecomment-520584455) works like a champ with voila `0.1.12`.
