### ISSUE TITLE
Best way to ulimit subprocesses?

### ISSUE THREAD

**Issue by timkpaine** [voila-dashboards/voila#360]
What is the best way to ulimit subprocesses right now? Something along the lines of https://github.com/QuantStack/voila/pull/218 that can be injected prior to kernel launch.

**Comment by timkpaine** [comment]
My current strategy is to use custom jupyter kernels that impose resource limits/niceness on startup

**Comment by jtpio** [comment]
By custom kernels do you mean wrappers around existing kernels?

**Comment by jtpio** [comment]
Using `resource.setrlimit()` from the standard library?

**Comment by timkpaine** [comment]
closing, using custom kernels
