### ISSUE TITLE
Performance: nbconvert blocks tornado ioloop

### ISSUE THREAD

**Issue by maartenbreddels** [voila-dashboards/voila#363]
During a review of #133 with @jtpio we observed that the progressive loading (i.e. the spinner) didn't work for firefox, or in chrome with the dev console open.

The issue was that tornado enters the voila handler, writes the chunks that are flushed out, but never returns control to the tornado IO loop.

Firefox (or chrome in dev mode with cache disabled), got some chunks of HTML, and tried to fetch js and css resources. But since the IO loop is blocked, the request only gets handled after all the chunks are pushed to the client/browser. The result is that the browser can only show the content after the js before the body tag is downloaded, making the progressive rendering fail. Chrome happens to cache the files, so there it worked.

This was solved by 33db3546a0691feb765686aa669137a6deddb6af which yields after writing and flushing each chunk. 

However, we realised another issue. Although we give control back to tornado's IO loop, nbconvert does not, it does a busy wait/polling on each cell execution. This means that if a cell takes 10 minutes to execute, the whole tornado server will be unresponsive.

There are two solutions possible:
 * Have the nbconvert cell execution in a thread (no worries about the GIL!).
 * Make nbconvert work async.

The first one is probably the easiest to implement.

PS: Note that this issue is not related to #133, it only revealed it.

**Comment by jtpio** [comment]
Here is a quick screencast:

![tornado-performance](https://user-images.githubusercontent.com/591645/63590579-8650cd80-c5ac-11e9-9fc3-36ad1d3a852a.gif)

**Comment by vidartf** [comment]
Could this be solved with a `ThreadPoolExecutor`? See e.g. this comment (not original post): https://gist.github.com/methane/2185380#gistcomment-1301483

**Comment by maartenbreddels** [comment]
I don't think jupyter_client/zmq likes being called from another thread. Although, now that I think about it, if the kernel is created from the same thread as the calls will original from, it might work.

**Comment by maartenbreddels** [comment]
Solved in https://github.com/voila-dashboards/voila/pull/403 continued in https://github.com/voila-dashboards/voila/pull/541
