### ISSUE TITLE
Voila vuetify templates

### ISSUE THREAD

**Issue by laserman781** [voila-dashboards/voila#365]
Hello, I am trying to get my voila app to look better with templates, I have used the voila-default template, but how could I use a vuetify template and use it to my needs? For example, the template I've found: [https://www.creative-tim.com/product/vuetify-material-dashboard?affiliate_id=104113&ref=madewithvuejs.com#](url).

Also, is there a way I can move my tab items to the navigation pane rather than have all those links?

I'm pretty new to all of this so any help is greatly appreciated!

**Comment by maartenbreddels** [comment]
cc @mariobuikhuizen 
Hi,

I think you should take a look at https://github.com/QuantStack/voila-vuetify/ it contains two templates, a base one, and a default one, that inherits from the base. You can make you own, just copy-paste the default one and start hacking :)
Does that help?

For integration with jupyter widgets, take a look at https://github.com/mariobuikhuizen/ipyvuetify/

**Comment by jtpio** [comment]
Closing as answered. As mentioned above, `ipyvuetify` and `voila-vuetify` are good resources to start using Vuetify with Voila.

@laserman781 feel free to comment here if you want to discuss more!
