### ISSUE TITLE
Show disconnect screen?

### ISSUE THREAD

**Issue by timkpaine** [voila-dashboards/voila#367]
If the backend is shut off or dies, should we provide visual feedback? Something akin to JupyterLab's grey circle being empty/full. Maybe a dialog or something?

**Comment by jtpio** [comment]
That would be useful yes.

There is a small `voila-debug` template / project that was started a while ago to show such indicators: https://github.com/QuantStack/voila-debug

![voila-debug-kernels](https://user-images.githubusercontent.com/591645/61577555-3da77f80-aae9-11e9-96dd-810fc08a9d7b.gif)

That was mostly for kernels but there should also be an indication when the whole server goes down.

**Comment by jtpio** [comment]
For debug purposes having it at the top is quite useful and more visible.

For production use maybe a popup that would only be shown when there is a connection issue?

**Comment by jtpio** [comment]
@timkpaine did you come up with something in the end?

**Comment by timkpaine** [comment]
just doing this for now https://github.com/timkpaine/voila-debug/tree/bottom/share/jupyter/voila/templates/debug_bottom

<img width="720" alt="Screen Shot 2019-10-01 at 4 05 56 PM" src="https://user-images.githubusercontent.com/3105306/65996490-807cc080-e465-11e9-8191-beee0547c971.png">

**Comment by jtpio** [comment]
Alright, thanks for sharing :+1:
