### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by jtpio** [voila-dashboards/voila#369]
We should add a CHANGELOG.md to list (or generate) the changes after each release (we already got some questions about things that were fixed in subsequent releases)

**Comment by jtpio** [comment]
@maartenbreddels you mentioned something about automatically generating the change log based on the commit messages (fix, feat, ...).

Is that still something to consider or are we fine taking a more "manual" approach? (and not enforce any commit style)

**Comment by maartenbreddels** [comment]
semantic commits, or https://www.conventionalcommits.org/en/v1.0.0/
This last page seems like a good standard, it lists a tool for generating a changelog. It does require that we should squash/edit commit messages of contributors, since I don't think we can require external people to do so.

What do you think about it?

**Comment by jtpio** [comment]
> It does require that we should squash/edit commit messages of contributors

While I like the idea of generating the changelog automatically, squashing and editing commits would add extra work and is not very friendly wrt the git history.

**Comment by jtpio** [comment]
`github-activity` generates nice changelogs based on GitHub labels (bug, enhancement, documentation...) with a list of contributors that have also been active in replying to issues: https://github.com/executablebooks/github-activity

This is also what the [Jupyter Releaser](https://github.com/jupyter-server/jupyter_releaser) uses, which will make things consistent if we adopt it for #805.

**Comment by slmg** [comment]
Thank you for this addition, it definitely make it easier to browse changes!

Would it be possible to add a date as part of each change? It would make it easier to see what changed in say the last two-months.

Thanks!
