### ISSUE TITLE
Plan to support .py or .md extension?

### ISSUE THREAD

**Issue by hainm** [voila-dashboards/voila#370]
hi,

is there any plan to support .py or .md extension?
The use case here is to avoid all the "troubles" to create a notebook with super simple example below

```
import nglview as nv
nv.demo()
```

cheers

**Comment by SylvainCorlay** [comment]
Hi @hainm the feature was just merged and is included in the 0.1.10 release that we announced earlier today!

**Comment by SylvainCorlay** [comment]
`voila mydir --VoilaConfiguration.extension_language_mapping='{".py": "python", ".jl": "julia"}'`

**Comment by SylvainCorlay** [comment]
> So I guess it will be available soon in conda-forge (the newer version does not exist there yet).

It seems that it is available.

**Comment by hainm** [comment]
hi @SylvainCorlay How's about `.md` extension? If this is not supported, how can I specify multiple cells in `.py`? May be just point me to the docs. thanks.

**Comment by hainm** [comment]
By the way, `0.1.10` works pretty well with `.py` extension.

**Comment by SylvainCorlay** [comment]
Cool! We don't really support for markdown files at the moment.
