### ISSUE TITLE
Best way to pass login information to started kernel?

### ISSUE THREAD

**Issue by jembishop** [voila-dashboards/voila#380]
Hi I have created a custom login handler for doing kerberos authentication, and I wanted to make the user that authenticated available in a spawned kernel so for example I can raise a JIRA ticket on their behalf. What is the best way to pass the information aquired in the login handler to the spawned kernel?

Ideally I could have something like 
```python 
import user_info
user = user_info.user
```
in my cell. 

Thanks

**Comment by timkpaine** [comment]
@jembishop a prelaunch hook can inject arbitrary cells, I use it for auth while i wait for https://github.com/QuantStack/voila/pull/270

https://github.com/QuantStack/voila/pull/218

**Comment by jembishop** [comment]
Interesting! Currently I am using voila as an extension to jupyter server. Unfortunately there doesn't seem to be any plans for an abilty to run a hook before a kernel has been started up in jupyter server AFAIK, which looks like it is what I need.

**Comment by trungleduc** [comment]
Hi, https://github.com/voila-dashboards/voila/pull/724 is merged so you can inject code cells into the notebook before execution
