### ISSUE TITLE
Extra padding in empty cells

### ISSUE THREAD

**Issue by derek-pyne** [voila-dashboards/voila#387]
Cells that contain code but no output, still take up some space in the output. Looks like there might be a 5px padding?

Example Notebook:
![image](https://user-images.githubusercontent.com/13180565/65626927-478fa800-df9c-11e9-85e4-0b3c7c9ff959.png)

Example Output:
![image](https://user-images.githubusercontent.com/13180565/65626733-f1bb0000-df9b-11e9-9f83-554bc43461f8.png)

Extra Padding:
![image](https://user-images.githubusercontent.com/13180565/65626950-537b6a00-df9c-11e9-99f9-2b856a2287b2.png)

Expected behaviour is that the two lines should not have a gap between them.

**Comment by jtpio** [comment]
Thanks @derek-pyne for the report.

You're right, empty cells are created with the padding (with the `jp-Cell` class from the JupyterLab themes).

**Comment by jtpio** [comment]
Ideally these cells should be stripped if they don't have any output.

**Comment by CodingKorie** [comment]
Hello All, 

I am having this same issue currently. My Voila is version 0.4.0. Is there another package / setting that I need to change to address this issue?

**Comment by helsharif** [comment]
I am using the latest version of Voila 0.5.8, and this issue is not resolved. Cells with no output render as empty, but padded div's when I run my app with Voila.
