### ISSUE TITLE
Autodetection of free port

### ISSUE THREAD

**Issue by JoergVanAken** [voila-dashboards/voila#392]
First of all: voila is just great! 

Last week I deployed a little application which the user can easily start by double clicking a windows batch file. This works fine but there is one little thing: The app cannot be started in multiple windows because the port number is fixed. I fixed this on my own by looping over a a few port numbers in the calling batch script. But when I start a new jserver a free port is autodetected. I would love to see this feature in voila, too.

**Comment by jtpio** [comment]
Thanks @JoergVanAken, that would indeed be very useful.

This is something that should normally come for free once https://github.com/voila-dashboards/voila/pull/270 lands.

In the meantime, we could replicate the [logic of the notebook server](https://github.com/jupyter/notebook/blob/4a9cfa7518c911d1b89b201acd0083adc6fb680e/notebook/notebookapp.py#L1440-L1459) in voila.
