### ISSUE TITLE
Progressive rendering is super slow

### ISSUE THREAD

**Issue by martinRenou** [voila-dashboards/voila#395]
Since progressive rendering has been added, rendering a Notebook in voila became super slow...

Taking a Notebook that prints "hello" 30 times:
![note](https://user-images.githubusercontent.com/21197331/66110883-fd27b000-e5c7-11e9-8ac3-aa3b07c08be8.png)

I assume we all agree this Notebook should take less than a second to be executed, starting time of the kernel included.

Without the progressive rendering (using a dev version that simply removes this feature):
![without](https://user-images.githubusercontent.com/21197331/66111087-76270780-e5c8-11e9-8c69-4aa1fbb84e09.gif)

With the progressive rendering:
![with](https://user-images.githubusercontent.com/21197331/66111169-a373b580-e5c8-11e9-8d79-f918d2e8203f.gif)

We should either improve this feature, or make it optional

**Comment by martinRenou** [comment]
And maybe we should turn it off by default until the speed is decent

**Comment by SylvainCorlay** [comment]
It is not that progressive rendering is slow, it is that we wait on the each cell to be run before sending the next execute request. This is not an issue IMO when we don't run a large number of nearly noop cells.

**Comment by martinRenou** [comment]
Also, progressive rendering is only useful if you have lots of cells. But progressive rendering is slower when you have lots of cells... This is quite problematic to me.

**Comment by martinRenou** [comment]
Sorry for adding 3 comments in a row...

> we wait on the each cell to be run before sending the next execute request

Not really, the core issue is that each cell is treated as a single Notebook in the current logic.

**Comment by martinRenou** [comment]
Fixed in #396
