### ISSUE TITLE
Access Query Params

### ISSUE THREAD

**Issue by derek-pyne** [voila-dashboards/voila#410]
We've started launching some epic Voila dashboards in our team. One big thing that we would like to do is click a link from one dashboard to open another dashboard with some parameters set. The usually case for this is for drilling down into a more detailed dashboard.

We could do this by adding query params to the link. 

This is doable inside Notebooks by accessing the url in a javascript cell like this:
```
%%javascript
IPython.notebook.kernel.execute("URL = '" + window.location + "'");
```

However this doesn't work in Jupyter Lab or Voila (https://github.com/jupyterlab/jupyterlab/issues/5888). Assuming Voila is using Jupyter lab behind the scenes?

Any ideas on how to open a link to a Voila dashboard with some data in params?

**Comment by jtpio** [comment]
Thanks @derek-pyne for opening this issue!

Voila doesn't allow arbitrary code execution so this code snippet will not work.

This is slightly related to https://github.com/voila-dashboards/voila/issues/105 and https://github.com/voila-dashboards/voila/pull/201 too but more towards using them in notebooks.

Linking to the gitter conversation here for reference: https://gitter.im/QuantStack/Lobby?at=5d9f33c4fcf7602cc5657eb2

**Comment by timkpaine** [comment]
https://github.com/voila-dashboards/voila/pull/218#issuecomment-553653123

**Comment by maartenbreddels** [comment]
Solved in https://github.com/voila-dashboards/voila/pull/414
