### ISSUE TITLE
Output does not render 

### ISSUE THREAD

**Issue by tonywang531** [voila-dashboards/voila#412]
Voila works fine on my PC and another PC, however nothing is rendered on tablet.  The tablet is Dell Latitude 5285 if it matters. 

I can confirm that there is "communication" between the addresses. 

[Voila] Executing notebook with kernel:
WARNING:tornado.general:403 GET /voila/files/favicon.ico (10.214.90.200): File not whitelisted
WARNING:tornado.access:403 GET /voila/files/favicon.ico (10.214.90.200) 0.00ms
[Voila] Adapting to protocol v5.1 for kernel 9e11f84d-2318-4f17-b057-e0da74cfd84b
WARNING:tornado.general:403 GET /voila/files/voila/plotlywidget.js (10.214.90.200): File not whitelisted
WARNING:tornado.access:403 GET /voila/files/voila/plotlywidget.js (10.214.90.200) 0.00ms

Both machines are using chrome. The execution of the widgets also seem to be completed. In the end, nothing is displayed. Is there any library needs to be installed on the user end?

**Comment by jtpio** [comment]
@tonywang531 thanks for the report.

Would you mind sharing the notebook so we could try to reproduce it?

Also, did you start voila with the `--enable_nbextensions=True` flag?

**Comment by maartenbreddels** [comment]
I would not be surprised if this is a plotly issue, I'd make sure first that you can create a static html page with the same plotly plot, and see if that works or does not work on your tablet.

**Comment by tonywang531** [comment]
> @tonywang531 thanks for the report.
> 
> Would you mind sharing the notebook so we could try to reproduce it?
> 
> Also, did you start voila with the `--enable_nbextensions=True` flag?

@jtpio Thank you for your reply. I tried to start voila again with --enable_nbextensions=True and now it is working. Thank you very much! Also chrome can open the page fine, but IE seem to be display blank page even with True flag enabled.

**Comment by jtpio** [comment]
@tonywang531 Glad to hear it worked.  IE is not supported, so it's better to switch for Firefox, Chrome.

**Comment by sruthiiyer** [comment]
Hi can someone help me out with the error File not whitelisted when i read a json file. There are two json files in the directory. while one gets fetched, another not. what shall i do?


voila mydir --VoilaConfiguration.file_whitelist="['.*\.(png|jpg|gif|svg|mp4|avi|ogg)']"

how do i add this in procfile.
