### ISSUE TITLE
Serve a RISE slideshow

### ISSUE THREAD

**Issue by DougRzz** [voila-dashboards/voila#43]
Enable Voila to serve a [RISE](https://github.com/damianavila/RISE)  slideshow 

This would be a great way of hosting and sharing Jupyter notebook content in a slidey way.  I suggest Voila should directly make use of the RISE slide-type dropdown menus and other parts of the RISE Jupyterlab extension UI.  

@damianavila , what do you think about this proposal?     ref: https://github.com/QuantStack/voila/issues/36#issuecomment-445200786

**Comment by SylvainCorlay** [comment]
Quick note, voila supports special nbconvert templates

See e.g. the example with a screencast template:

![screencap-voila-gridstack](https://user-images.githubusercontent.com/1765949/48071165-eae79b00-e1d9-11e8-86e3-df9901179e8c.gif)

The idea is to encode layouts / extra information in the notebook metadata to 

 - encode layout in the case of the gridstack template (e.g. with the same spec as the deprecated jupyter dashboard)
 - another section for layout in a phosphor dock area layout.
 - another section for rendering as a presentation with rise...

**Comment by maartenbreddels** [comment]
An example of this is in #54, however, I am not sure voila should include this PR. It does show how you could (if you tweak the template further) build a RISE slideshow using the current template system, and even release it on pypi.

**Comment by jtpio** [comment]
Note: there is now a `voila-reveal` template to serve slideshows with Voila: https://github.com/voila-dashboards/voila-reveal

cc @DougRzz

**Comment by SylvainCorlay** [comment]
Closing as addressed by voila-reveal.
