### ISSUE TITLE
Error loading server extension voila

### ISSUE THREAD

**Issue by eromoe** [voila-dashboards/voila#434]
I got error when install extension
```
E:\ts_notebooks>jupyter serverextension enable voila --sys-prefix
Enabling: voila
- Writing config: C:\Anaconda3\etc\jupyter
    - Validating...
Error loading server extension voila
      X is voila importable?
```

**Comment by jtpio** [comment]
@eromoe are `jupyter` (notebook) and `voila` installed in the same environment?

Also, what is the output of `jupyter --paths`?

**Comment by eromoe** [comment]
Now install extension is fine  , I don't know what happen .
