### ISSUE TITLE
Failing to render an extending widget

### ISSUE THREAD

**Issue by sradomski** [voila-dashboards/voila#439]
Hey there,

first of all, thank you for all your efforts, I feel like voilá fills an important gap in the jupyter / ipython ecosystem.

I managed to have voilá render custom ipywidgets just fine when extending `widgets.DOMWidgetView`, e.g. as given in the [custom widget guide](https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Custom.html).

However, I'd like to have a custom widget with the default behavior of e.g. the `Combobox` widget and extend that one (as in the ipynb notebook [Voila Failed Rendering.ipynb.zip](https://github.com/voila-dashboards/voila/files/3764839/Voila.Failed.Rendering.ipynb.zip)). It is rendered just fine as a jupyter notebook but voilá is unable to load the module (via require.js) and even falls back to an attempt to load it from unpkg.com. I am very used to python, but only have a passing familiarity with JS development and can not make heads or tails from the error messages.

Can anyone tell me if extending existing ipython widgets is supported for voilá and there is something I need to account for first, or if this is a fools errand as voilá does not / can never support such an approach?

**Comment by sradomski** [comment]
Turns out that ComboBox is not in `"@jupyter-widgets/base"` when run from voilá but in `"@jupyter-widgets/controls"`. It was available in the former when run from within the jupyter notebook though.

**Comment by maartenbreddels** [comment]
Yes, that is the right package, in the classical notebook they are all aliased to the same bundle, that's why it probably worked there.
