### ISSUE TITLE
Create and hide widgets

### ISSUE THREAD

**Issue by tonywang531** [voila-dashboards/voila#451]
Currently it seems more like a feature issue. The following code below allows me to display 2 widgets, clear everything once and only display one widget when it is clicked (clear output is optional). Also the text box value is updated. 

import ipywidgets as widgets
from IPython.display import clear_output

```
def on_button_click(b):
    clear_output()
    Text.value = "2"
    display(Text)

button = widgets.Button(description='寄与度計算', icon='check')
button.on_click(on_button_click)

Text = widgets.Text(
    value=("rmse"),
    placeholder='Type something',
    description='RMSE:',
    disabled=False
)

display(button, Text)
```
It works in Jupyter notebook but clear_output(), clear_output and display(Text) seem not to be functional in Voila. Is it going to be implemented or did I miss something? In terms of security it seems to be safe enough.

**Comment by tonywang531** [comment]
I have found a way to hide the widgets using Accordion

https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html#Accordion

If I put Accordion after display widgets and call Accordion it will work in voila as well. While not being able to create widget seems to limit the design somehow, I think this is no longer a big issue.

**Comment by jtpio** [comment]
Thanks @tonywang531 for sharing your solution :+1:

**Comment by DougRzz** [comment]
Tony,

I suggest you put both your widgets in a Vbox or HBox. If you want to
remove one of the widgets, do something similar below

```
import ipywidgets as widgets
box = widgets.HBox([text, button])

box.children = [box.children[0]] # remove 2nd widget

box.children = box.children + [button] # put the button back.
```
