### ISSUE TITLE
JupyterLab extension logo

### ISSUE THREAD

**Issue by martinRenou** [voila-dashboards/voila#461]
I would suggest not using the spinner logo for the JupyterLab extension button.

I suppose this logo with a transparent background would be better:
![BLEU-illustration-2](https://user-images.githubusercontent.com/21197331/68207719-d34f1800-ffcf-11e9-83d8-d25a6a79d398.png)

**Comment by jtpio** [comment]
Good idea :+1: 

Also a bit cropped, maybe something like this:

![image](https://user-images.githubusercontent.com/591645/68325021-ebef2900-00c8-11ea-9e22-ce66ac54a2a2.png)

**Comment by martinRenou** [comment]
Yes! Wasn't there a requirement for the button logo since JupyterLab `1.0`? I remember there was an issue with the logo when JLab `1.0` was released.
