### ISSUE TITLE
JupyterLab preview doesn't respect contents manager

### ISSUE THREAD

**Issue by timkpaine** [voila-dashboards/voila#466]
Looks like the voila preview attempts to grab the file from disk, regardless of what JupyterLab has set its contents manager to be. It should instead try to grab the data through the contents manager.

**Comment by maartenbreddels** [comment]
Hi Tim,

thanks for the report. Is this on master/latest release? Or is this maybe with the jupyter_server/extensionapp PR #270 .

cheers,

Maarten

**Comment by timkpaine** [comment]
@maartenbreddels apologies, was accidentally pointing at a stale 0.1.14 instead of 0.1.17. Works fine!

**Comment by maartenbreddels** [comment]
No problem, rather have a false report than no feedback :)
