### ISSUE TITLE
`Error: No running kernel with id` on JupyterHub

### ISSUE THREAD

**Issue by JamesSample** [voila-dashboards/voila#478]
I have a JupyterHub running on Google Kubernetes with a setup based on the [z2jh tutorial](https://zero-to-jupyterhub.readthedocs.io/en/latest/). I'd like to install Voila so that users can create dashboards based on their notebooks and share them with other users on the Hub (e.g. via a shared drive; I don't need any further authentication or security etc.).

The issue [here](https://github.com/voila-dashboards/voila/issues/112) has been very helpful as a starting point - especially the comments from @gedankenstuecke [here](https://github.com/voila-dashboards/voila/issues/112#issuecomment-512364629). Based on this, I've modified my Dockerfile and Voila _almost_ works: I can click the Voila button on the JupyterLab `Launcher` menu and navigate to a notebook. The notebooks seem to render OK **_except_** **all the interactive widgets are missing**. For example, here's a screenshot of `basics.ipynb` from the `examples` folder (note that the "slider" widget is missing):

![basics](https://user-images.githubusercontent.com/12967176/68841957-d039e300-06c5-11ea-9538-0ea9111b83c1.png)

Inspecting the page shows the error `No running kernel with id`:

![voila_error](https://user-images.githubusercontent.com/12967176/68841762-79340e00-06c5-11ea-8e71-4b3b145e1fe5.png)

I don't really understand how the Voila <-> widget interactions work, but Voila must be managing to run a kernel somehow, since non-widget elements (including e.g. Altair charts and Folium/Leaflet maps) show up fine. In the notebook itself, the widgets work fine too.

I guess there must be some additional configuration that I'm missing that specific to widgets? Can anyone point me in the right direction, please? 

Thank you! :-)

**Comment by gedankenstuecke** [comment]
Glad to hear that you got that working on your end so far! I just ran the same notebook on our JupyterHub setup as well and it gives the same result.

**Comment by JamesSample** [comment]
@gedankenstuecke Thanks for the code to get me this far! Even without widgets, it's still possible to create some nice dashboards using just Altair and Voila.

I'd love to get the widgets working, though. I'll keep experimenting and will post an update here if I find a solution.

**Comment by martinRenou** [comment]
Would it be possible that your setup overwrites the kernel id server side? It seems that widgets cannot connect to the Python kernel because of a wrong kernel id information.

**Comment by gedankenstuecke** [comment]
@JamesSample: Thanks, that would be great!

**Comment by JamesSample** [comment]
After a depressingly long time staring at this, I think the issue was a single extra forward slash in my `jupyter_notebook_config.py`!

I added the following to `jupyter_notebook_config.py` to get a Voilá button to appear on the Launcher screen:

```
c.ServerProxy.servers = {
    "voila": {
        "command": ['voila', '--port', '{port}', '--server_url', '/', '--base_url', '{base_url}/voila/'],
        "launcher_entry": {
            "title": "Voilà",
        },
    },
}
```

However, the `--base_url` argument for the `command` entry should be

`'{base_url}voila/'`

and not

`'{base_url}/voila/'`

My original version produced a `//` in the URL, which apparently isn't a problem for many notebook components, but does seem to interfere with Voilá <-> widget interactions. Removing the forward slash seems to fix the problem. Hopefully it'll work for you too, @gedankenstuecke!

**Comment by gedankenstuecke** [comment]
Looks like this might be the issue in our case too, as we’re having the same `//` issue from my look at the image we’re using. I’ll check it out later this week when back in the office!
