### ISSUE TITLE
Datashader does not refresh on zoom in voila

### ISSUE THREAD

**Issue by afonit** [voila-dashboards/voila#480]
I am not sure if this is supposed to work in Voila - but I think it would be nice in some scenarios.
When zooming with Datashader it is not refreshing the plot when it is hosted with voila.

A reproducible example:
```python
import numpy as np
np.random.seed(42)

import holoviews as hv
from holoviews.operation.datashader import datashade
from holoviews import opts, dim
hv.extension('bokeh')

from colorcet import fire
datashade.cmap=fire[50:]

def gaussians(specs=[(1.5,0,1.0),(-1.5,0,1.0)],num=100):
    """
    A concatenated list of points taken from 2D Gaussian distributions.
    Each distribution is specified as a tuple (x,y,s), where x,y is the mean
    and s is the standard deviation.  Defaults to two horizontally
    offset unit-mean Gaussians.
    """
    np.random.seed(1)
    dists = [(np.random.normal(x,s,num), np.random.normal(y,s,num)) for x,y,s in specs]
    return np.hstack([d[0] for d in dists]), np.hstack([d[1] for d in dists])

dist = gaussians(specs=[(2,2,0.02), (2,-2,0.1), (-2,-2,0.5), (-2,2,1.0), (0,0,3)], num=10000000)
datashade(hv.Points(dist))
```

Here is what it looks like in both jupyterlab and the notebook:
![lab_working](https://user-images.githubusercontent.com/1798497/68965002-bfae6900-07a8-11ea-87dd-8136870d2517.gif)

Here it is not working in voila:
![voila_datashader_not_working](https://user-images.githubusercontent.com/1798497/68965016-cb019480-07a8-11ea-9656-7fe64ccf5e88.gif)

**Comment by maartenbreddels** [comment]
Hi,

I can think of two solutions: 
 1. Use [Vaex](https://github.com/vaexio/vaex) (hey, I'm biased).
 2. Use ipybokeh, which uses ipywidgets for communication, I think vanilla bokeh will not work.

**Comment by afonit** [comment]
Regular holoviews with bokeh works fine with zoom - so it just appears to be an issue with datashader.  I will research the ipybokeh you mention and see if that resolves it.

**Comment by maartenbreddels** [comment]
> Regular holoviews with bokeh works fine with zoom

For normal datapoints I guess. What I think it happening is that the zooming happens only in the frontend (all in the browser) and doesn't need to communicate with the browser. For datashader (and also vaex + bqplot) it needs to talk to the kernel each time to aggregate the new data.

You may also want to take a look at https://pyviz-dev.github.io/panel/user_guide/Deploy_and_Export.html#ipywidgets

**Comment by afonit** [comment]
oh - I thought voila allowed that communication to happen back to the kernel?

Yes I have tried out Panel - it is great in some circumstances and Voila is so great in others.

**Comment by afonit** [comment]
closing and will test in the next holoviews release per:
https://github.com/holoviz/datashader/issues/832
