### ISSUE TITLE
Custom ipywidget

### ISSUE THREAD

**Issue by saulshanabrook** [voila-dashboards/voila#482]
Hello.

Let's say I have am making a custom widget library, that has lots of magic JS code in it. I make it following https://github.com/jupyter-widgets/widget-cookiecutter, so I get out a a jupyterlab extension, as well as a classic notebook extension.

How do I then use that custom widget with voila?

**Comment by martinRenou** [comment]
Hello!

It should work out of the box. If you did not push your JS to `npmjs` then you would need to specify the option: `--enable_nbextensions=True` to Voila

**Comment by saulshanabrook** [comment]
Ah cool! So it magically runs `require` on an NPM package? Can you point me to where this `require` statement is generated?

**Comment by saulshanabrook** [comment]
I am just trying to wrap my head around here how ipywidget packages are distributed then included in voilla.

**Comment by martinRenou** [comment]
If I'm not mistaken, it is around here: https://github.com/voila-dashboards/voila/blob/master/js/src/loader.js

I did not write that code so I might be wrong :)

**Comment by martinRenou** [comment]
And the `--enable_nbextensions=True` option is useful for using a locally installed version of your notebook extension, instead of downloading it online.

**Comment by saulshanabrook** [comment]
Ah I see and I think that comes from the `_model_name` property here? https://github.com/jupyter-widgets/widget-cookiecutter/blob/ab5ded296bdc887a0b86e0af0768cefbfb6b55a9/%7B%7Bcookiecutter.github_project_name%7D%7D/%7B%7Bcookiecutter.python_package_name%7D%7D/example.py#L10

**Comment by martinRenou** [comment]
Yes, I suppose it's how it looks for the npm package name.

**Comment by saulshanabrook** [comment]
Thanks for the pointers here.

**Comment by jtpio** [comment]
This part is also relevant for loading the bundles:

https://github.com/voila-dashboards/voila/blob/6700300f041cff08bfe6cf9f77c20860157086b2/share/jupyter/voila/templates/default/nbconvert_templates/base.tpl#L49-L59
