### ISSUE TITLE
Display output from a function

### ISSUE THREAD

**Issue by DanielConlin** [voila-dashboards/voila#483]
I am having trouble getting anything to display in voila that comes as the output from a function. Below is a simple example that works great in a jupyter notebook, but shows no output once running in voila.

```python
import ipywidgets as widgets
 
def on_run_button_clicked(b):
    print('running...')
 
my_button = widgets.Button(
    description='Run Button',
    disabled=False,
    button_style='info', # 'success', 'info', 'warning', 'danger' or ''
    tooltip='Run button function',
    icon='play'
)
display(my_button)
my_button.on_click(on_run_button_clicked)

```

**Comment by gareth-j** [comment]
You can use an Output widget to output your data. I've modified your code to include this widget and use a `with output:` within the function.

```python
import ipywidgets as widgets
 
def on_run_button_clicked(b):
    with output_box:
        print('running...')
 
my_button = widgets.Button(
    description='Run Button',
    disabled=False,
    button_style='info', # 'success', 'info', 'warning', 'danger' or ''
    tooltip='Run button function',
    icon='play'
)
output_box = widgets.Output()
display(my_button, output_box)
my_button.on_click(on_run_button_clicked)
```
I'm not sure if this is the best way to be doing it but it works in this simple example. One of the voila team might be able to suggest another way.

**Comment by DanielConlin** [comment]
@gareth-j This works perfectly for me. Thanks for the help!
