### ISSUE TITLE
Mathjax not working for ipywidgets.HTMLMath output

### ISSUE THREAD

**Issue by cnydw** [voila-dashboards/voila#488]
Example input:
``` py
import ipywidgets
import markdown
math_html = markdown.markdown("$y= \int x^2 dx $")
math_widget = ipywidgets.HTMLMath(value=math_html)
math_widget
```

The output of this code renders correctly in jupyterlab.
![image](https://user-images.githubusercontent.com/10969537/69816457-b980a980-11f8-11ea-9b11-4ea64b36ff4a.png)

However, in voila it's just showing the LaTeX code.
![image](https://user-images.githubusercontent.com/10969537/69816538-e208a380-11f8-11ea-9c51-263f1a9c348d.png)

**Comment by maartenbreddels** [comment]
Which version of voila is this in?

**Comment by cnydw** [comment]
> Which version of voila is this in?

It's `0.1.20`
