### ISSUE TITLE
Read the current URL in a voila served notebook

### ISSUE THREAD

**Issue by marketneutral** [voila-dashboards/voila#502]
I have a third party web app which allows me to stick in links. I want to link to a notebook served by `voila` and I need to pass arguments in the URL that the notebook can read. In a Jupyter notebook session I can do this like:

the notebook url, for example, is

```
http://myserver/.../notebooks/voila-example/get_url_args.ipynb?arg1=this_is_arg1&arg2=another_arg
```

then in the notebook I can do

```python
%%javascript
IPython.notebook.kernel.execute("url = '" + window.location + "'");
```

and

```python
from urllib.parse import urlparse, parse_qs
parsed = urlparse(url)
print(parse_qs(parsed.query))
```

which returns

```
{'arg1': ['this_is_arg1'], 'arg2': ['another_arg']}
```

perfect!

But when I run this as a `voila` served notebook, I get

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-3-4cbfa8a28430> in <module>
      1 from urllib.parse import urlparse, parse_qs
----> 2 parsed = urlparse(url)
      3 print(parse_qs(parsed.query))

NameError: name 'url' is not defined
```

So `voila` is not running the javascript.

**How can I get a `voila` served notebook to know its URL?**

**Comment by timkpaine** [comment]
@marketneutral my [prelaunch hook](https://github.com/voila-dashboards/voila/pull/218) can give you some of this, though it is not merged

**Comment by jtpio** [comment]
An alternative to pass the request URI to the kernel environment, such as in this PR: https://github.com/voila-dashboards/voila/pull/414

**Comment by maartenbreddels** [comment]
Solved in https://github.com/voila-dashboards/voila/pull/414
