### ISSUE TITLE
Is there a way to create your own third-party widgets?

### ISSUE THREAD

**Issue by wanderso** [voila-dashboards/voila#503]
I've noticed that arbitrary Javascript code execution is disabled (for a variety of good reasons). There's a minor issue, though - I am currently running an app that I made as a tool for my team that uses a couple of widgets I programmed myself. (The changes to the widgets themselves are fairly simple - a Label and Image that have an opacity feature added, so I can make them slowly fade out over time.) But without the ability to communicate the correct Javascript code to the Voila instance - even by creating a cell with the %%javascript tag - the two widgets no longer work.

Is there a way to solve this issue? Again, putting the relevant Javascript code in a %%javascript cell above the application itself does not seem to work to enable my widgets.

**Comment by jtpio** [comment]
@wanderso one way would be to create your own custom widget using the [widget cookiecutter](https://github.com/jupyter-widgets/widget-ts-cookiecutter).

Many third-party widgets are built using this cookiecutter.

**Comment by jtpio** [comment]
Closing as answered.

@wanderso feel free to comment here if you have more questions, or on the [widget cookiecutter](https://github.com/jupyter-widgets/widget-ts-cookiecutter) / [ipywidgets](https://github.com/jupyter-widgets/ipywidgets) repos directly.
