### ISSUE TITLE
NBconvert templates cannot connect to kernels, maybe add a hook so that templates can monitor the kernel status?

### ISSUE THREAD

**Issue by timkpaine** [voila-dashboards/voila#505]
xposting here for visability. 

CC https://github.com/voila-dashboards/voila-debug/issues/5

Would need to add a "hook" here for templates to use info like kernel disconnected, etc. 
https://github.com/voila-dashboards/voila/blob/91fb3ce829e5bd4f8e6962ac5ee5281b3ba6b190/share/jupyter/voila/templates/default/static/main.js#L51

**Comment by timkpaine** [comment]
for now im going to modify my template to not load main.js, and just modify that script to hook  in, should work just fine

**Comment by jtpio** [comment]
@timkpaine what workaround did you end up using?

Do you think the `init` function / hook should expose the kernel object directly?

**Comment by timkpaine** [comment]
I took the initialization hook from static/main.js and put it inside my template, then didn't call super in that section of the jinja template.

I think this is an ok workaround for now, it would be nice to be able to expose this in an easier way, maybe put it in its own template similar to spinner.tpl which could then be overloaded by others? If there is no security concern then exposing the kernel could also work.

**Comment by timkpaine** [comment]
https://github.com/voila-dashboards/voila-debug/issues/5#issuecomment-577439333
