### ISSUE TITLE
TLS Support?

### ISSUE THREAD

**Issue by ch-pub** [voila-dashboards/voila#508]
I'm running Jupyter in a remote server, with TLS certificates, so my Jupyter notebooks are available at https://[my website]. I've also installed Voila in that remote Jupyter instance. When I launch Voila from the Jupyter terminal, I am then able to access the Voila dashboards at **http**://[my website]:8866. 

Is there any way to enforce the same TLS certificate at the Voila dashboards endpoint as well?

**Comment by Jul3k** [comment]
Yes. First enable the Jupyter Notebook voila extension with
`jupyter serverextension enable voila --sys-prefix`
Then you are able to access the voila representation at
`https://[your website]/voila`
