### ISSUE TITLE
Incomplete installation with `pip install --user voila` on Windows

### ISSUE THREAD

**Issue by dr-1** [voila-dashboards/voila#509]
When installing as a user with `pip install --user voila` on Windows, pip confirms that the package has been installed, but the templates directory does not get created. As a result, `voila` immediately fails with
```
ValueError: No template sub-directory with name 'default' found in the following paths:
        C:\Users\myuser\AppData\Roaming\jupyter\voila\templates
        c:\program files\python37\share\jupyter\voila\templates
        C:\ProgramData\jupyter\voila\templates
```
The problem does not occur when installing as an administrator instead.
On Linux, the problem does not occur even with the --user flag.

Python 3.7.4, pip 19.3.1, Windows 10 1909

**Comment by clouds56** [comment]
same here (with windows store's python-38), any workaround?

**Comment by vidartf** [comment]
If you run the install command with `-v` (verbose), does any of the output lines give any indication of where pip is putting the templates?

**Comment by dr-1** [comment]
The `-v` flag did not give me feedback on whether or where the templates are installed.

On Python 3.12 and with voila 0.5.4, this does not seem to be a problem anymore. `voila` runs successfully for me after installing with `--user`.

**Comment by martinRenou** [comment]
Thanks for commenting back, closing as fixed then!
