### ISSUE TITLE
Voila cannot show the custom widgets by widgets-ts-cookiecutter

### ISSUE THREAD

**Issue by dou-du** [voila-dashboards/voila#514]
Hi,

We had developed several custom widgets by using the widgets-ts-cookiecutter. (https://github.com/jupyter-widgets/widget-ts-cookiecutter). 

I found none of the widgets can be shown with voila in Jupyter notebook or Jupyter Lab. Could you give some suggests to solve this problem ? Thanks.

**Comment by martinRenou** [comment]
If those extensions are not deployed to npmjs, you should use the `--enable_nbextensions=True` with Voila

**Comment by martinRenou** [comment]
But if your extensions don't show up in Jupyter Notebook or JupyterLab, I would say it is more an issue with your extension that is not building?

**Comment by jtpio** [comment]
> If those extensions are not deployed to npmjs, you should use the `--enable_nbextensions=True` with Voila

I thought this was already in the docs but it hasn't been merged yet: https://github.com/voila-dashboards/voila/pull/507 (cc @martinRenou if you want to have a look)

**Comment by dou-du** [comment]
> If those extensions are not deployed to npmjs, you should use the `--enable_nbextensions=True` with Voila

Thank you very much. This fix my problem.

**Comment by martinRenou** [comment]
Sure! :)
