### ISSUE TITLE
Voila cannot show Greek letter (latex format) correctly

### ISSUE THREAD

**Issue by uu1477** [voila-dashboards/voila#516]
When I marked widgets with description, it is working well in JupyterLab. 

![Screenshot from 2020-01-16 15-16-18](https://user-images.githubusercontent.com/20816399/72532226-4e0b9d80-3873-11ea-8ed5-83acecdbf741.png)

However, when I use Voila, it cannot show the Greek letter correctly. 
![Screenshot from 2020-01-16 15-16-29](https://user-images.githubusercontent.com/20816399/72532267-62e83100-3873-11ea-9b43-1d7ad37f7218.png)

I am using the least Voila version, which compiled from this Git repository.

**Comment by jtpio** [comment]
Thanks @uu1477.

That looks related to https://github.com/voila-dashboards/voila/pull/470 and https://github.com/voila-dashboards/voila/pull/489.

**Comment by maartenbreddels** [comment]
I think this is a regression, only markdown cells render to math.

**Comment by maartenbreddels** [comment]
Correction: this does seem to work in master (browser cache made it not work). Could you try opening the dev console and disable your cache?

**Comment by jtpio** [comment]
The `basics.ipynb` notebook still seems to be an issue on master.

![image](https://user-images.githubusercontent.com/591645/73257712-8c368480-41c4-11ea-8021-dbd55a4450e7.png)

**Comment by jtpio** [comment]
But adding a cell below with the following content seems to load the font, which applies to the slider description above:

```python
x = widgets.Checkbox(value=True, description='$\Psi$ Real')
x
```

![image](https://user-images.githubusercontent.com/591645/73258374-d9ffbc80-41c5-11ea-96c5-38a22c3a52c3.png)

**Comment by jgunstone** [comment]
adding here because I'm guessing it could be related... 

Math not display in Voila. 


```py
from IPython.display import Math, display, clear_output
import ipywidgets as w

out = w.Output()
with out: 
    clear_output()
    display(Math('\\frac{\\rm{kg}}{\\rm{m}^{2} \\cdot \\rm{s}^{2}}'))
    
out
```
![image](https://user-images.githubusercontent.com/21370980/182820257-fce430c6-f5a4-45df-9cb7-59b3e99ea7fa.png)


## env 

ubuntu2004

```bash
(aectemplater-dev) jovyan@PORT4028:/mnt/c/engDev/git_mf/tmp/aectemplater/ui$ conda list jupyter
# packages in environment at /home/jovyan/miniconda3/envs/aectemplater-dev:
#
# Name                    Version                   Build  Channel
jupyter_client            7.2.2            py39h06a4308_0  
jupyter_core              4.11.1           py39hf3d152e_0    conda-forge
jupyter_server            1.18.1           py39h06a4308_0  
jupyterlab                3.4.4            py39h06a4308_0  
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_server         2.12.0           py39h06a4308_0  
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1  
(aectemplater-dev) jovyan@PORT4028:/mnt/c/engDev/git_mf/tmp/aectemplater/ui$ conda list ipywidgets
# packages in environment at /home/jovyan/miniconda3/envs/aectemplater-dev:
#
# Name                    Version                   Build  Channel
ipywidgets                7.6.5              pyhd3eb1b0_1  
(aectemplater-dev) jovyan@PORT4028:/mnt/c/engDev/git_mf/tmp/aectemplater/ui$ conda list voila
# packages in environment at /home/jovyan/miniconda3/envs/aectemplater-dev:
#
# Name                    Version                   Build  Channel
voila                     0.3.6              pyhd8ed1ab_0    conda-forge
```

**Comment by martinRenou** [comment]
Thanks John for commenting on both issues!
