### ISSUE TITLE
Assertion error causing voila to shut down

### ISSUE THREAD

**Issue by tonywang531** [voila-dashboards/voila#520]
Recently I start to get assertion error for voila after leaving it for more than 1 day. This is the error message:

```
Assertion failed: error not defined [0] (C:\ci\zeromq_1549025594292\work\src\err.cpp:383)
[IPKernelApp] WARNING | Parent appears to have exited, shutting down.
```

That is the only error that is displayed from the command prompt. I do not think this file even exists.

Update: I got the same error yesterday as well. It is not a critical error, as it can be fixed by restarting voila. I just want to know whether this is the problem of voila.

**Comment by maartenbreddels** [comment]
Hi,

I am not sure this is voila's fault. This error seems to come from 0mq/zeromq. Maybe you can try installing a different version of it. Google didn't seem to give me more ideas, except a different report:
https://github.com/spyder-ide/spyder/issues/9964

Would be great if you can let us know if you find more about it, or find a solution/workaround!

Regards,

Maarten

**Comment by tonywang531** [comment]
> Hi,
> 
> I am not sure this is voila's fault. This error seems to come from 0mq/zeromq. Maybe you can try installing a different version of it. Google didn't seem to give me more ideas, except a different report:
> [spyder-ide/spyder#9964](https://github.com/spyder-ide/spyder/issues/9964)
> 
> Would be great if you can let us know if you find more about it, or find a solution/workaround!
> 
> Regards,
> 
> Maarten

Hello Maarten,

Yes I have seen this report. At first I did not believe that firewall/antivirus is the cause. The voila is deployed in a cooperate environment which has both firewall and antivirus. It is difficult to change configuration and I cannot just "disable" these things like my own PC. I may try a few things to see if it can fix this issue.

**Comment by rmmoreira** [comment]
@tonywang531 did you found a solution?
I am facing exactly the same issue.
The only workaround I found is to schedule a Windows Task to re-run voila

**Comment by tonywang531** [comment]
> @tonywang531 did you found a solution?
> I am facing exactly the same issue.
> The only workaround I found is to schedule a Windows Task to re-run voila

Sorry recently I do not encounter this issue anymore without changing anything. I think it has to do with the antivirus or firewall you have. Try disable it if you can and see if the issue persists.

**Comment by rmmoreira** [comment]
Thank you for replying Tony.

In the local server I am running the app, we don’t have active anti-virus and firewall.

So now your app is running 24/7 with the same activity and no issues?

**Comment by tonywang531** [comment]
> Thank you for replying Tony.
> 
> In the local server I am running the app, we don’t have active anti-virus and firewall.
> 
> So now your app is running 24/7 with the same activity and no issues?

Yes that's right. I am not sure what fixed it.
