### ISSUE TITLE
voila dashboard on mybinder 500 error

### ISSUE THREAD

**Issue by cornhundred** [voila-dashboards/voila#521]
My voila dashbaord example that runs on MyBinder stopped working: https://github.com/ismms-himc/codex_dashboard 

It used to display the interactive widget correctly, but not it now shows a 500 internal server error. I'm not sure it it is an issue with MyBinder or Voila. I have myself pinned to voila 0.1.9 (https://github.com/ismms-himc/codex_dashboard/blob/master/requirements.txt) so I think it might be a mybinder problem. 

The same Codex dashboard is still working on the voila gallery (https://github.com/voila-gallery/voila-gallery.github.io/blob/master/_data/gallery.yaml#L43, https://voila-gallery.org/)

**Comment by martinRenou** [comment]
Could it be another package that got upgraded? 

Maybe it is not related, but I tried executing your Notebook from the classic Jupyter Notebook on binder and it seems to hang at this cell:
```python
net.load_df(df['tile-neighbor'])
net.normalize(axis='row', norm_type='zscore')
net.clip(-5,5)
net.widget()
net.widget_instance.observe(on_value_change, names='value')
```

**Comment by martinRenou** [comment]
Sorry, actually it works. But it took more than 20 seconds to execute.

I wonder if that would be possible to start Voila from a terminal on binder, so you can see the actual error message in the terminal.

**Comment by jtpio** [comment]
The one in the gallery uses this commit: https://github.com/ismms-himc/codex_dashboard/commit/b8c8fb820c918d4fc343cf6d8a25bd81cad837c9

While the one in the repo is built from `master`, so as of today this commit: https://github.com/ismms-himc/codex_dashboard/commit/aa7f8fdd5fb3cac5321a064f33097cf725bee5e1

So it's possible the two Binders were built at different times, and something changed in between.

Have you tried to reproduce the issue locally using [repo2docker](https://repo2docker.readthedocs.io/en/latest/)? mybinder.org is usually using the latest version of it: https://github.com/jupyterhub/mybinder.org-deploy/blob/c1440f66c4c05ca421b53c49a045771e963d4d4d/mybinder/values.yaml#L72

**Comment by jtpio** [comment]
@cornhundred have you tried changing the dashboard, for example by updating voila to 0.1.20?

This would trigger a new build on mybinder.org the next time the binder link is used, and might give some more information on whether something was wrong with the previous build.

**Comment by cornhundred** [comment]
Hi @jtpio I updated the version of voila (https://github.com/ismms-himc/codex_dashboard/blob/master/requirements.txt#L3) but now it is getting stuck on cell 9. I'll try to run it locally and let you all know what happens.

**Comment by jtpio** [comment]
What does cell 9 do?

**Comment by cornhundred** [comment]
It defines a function see: https://github.com/ismms-himc/codex_dashboard/blob/master/index.ipynb

It runs on my computer, but I want to try the repo2docker suggestion you made above.

**Comment by cornhundred** [comment]
The notebook was getting stuck at cell 10, which does the hierarchical clustering and generate the widget.

I tried running the notebook (index.ipynb) using mybinder (https://mybinder.org/v2/gh/ismms-himc/codex_dashboard/master) and the notebook ran correctly. However clicking the voila button in the classic notebook did not render the Voila dashboard correctly (it got stuck at cell 9 again). 

Suspecting the mybinder instance ran out of memory, I lowered the number of matrix columns that were being clustered from 5,000 to 3,000 and then the voila button worked correctly. I updated the current notebook to reduce the size of the matrix and now it is rendering correctly using the launch binder button. 

So I suspect that the mybinder instance is running out memory.

**Comment by jtpio** [comment]
Thanks @cornhundred for the update.

Memory on mybinder.org Instances is indeed [limited to 1GB](https://mybinder.readthedocs.io/en/latest/faq.html#how-much-memory-am-i-given-when-using-binder).

Ideally there should be some indication when the kernel is not available anymore (https://github.com/voila-dashboards/voila/issues/67).
