### ISSUE TITLE
voila render button on Jupyter Lab

### ISSUE THREAD

**Issue by cornhundred** [voila-dashboards/voila#524]
<img width="126" alt="Screen Shot 2020-01-24 at 11 49 36 AM" src="https://user-images.githubusercontent.com/8352840/73086987-b07e2280-3e9f-11ea-8061-993ea0b01264.png">

This button works great for rendering the current notebook as a Voila dashboard using the classic Jupyter Notebook, but is there an equivalent for Jupyter Lab?

**Comment by martinRenou** [comment]
Yes you can install it with 
```
jupyter labextension install @jupyter-voila/jupyterlab-preview
```

**Comment by martinRenou** [comment]
It is not exactly the same behavior though. The JupyterLab extension button will open a sidepane with your Voila dashboard preview :)

**Comment by cornhundred** [comment]
Okay, I actually like the different tab behavior from classic notebook. Thanks for the prompt reply :)

**Comment by jtpio** [comment]
But there is also the "Open with Voila in New Browser Tab" command if you prefer:

![image](https://user-images.githubusercontent.com/591645/73088665-facdc680-3ed4-11ea-978d-96e4fa8ce643.png)

**Comment by cornhundred** [comment]
Great @jtpio, but I guess there'e not currently a button for that. Seems to work fine though. Thanks all.

**Comment by jtpio** [comment]
Maybe we could add it to the toolbar of the preview window? https://github.com/voila-dashboards/voila/issues/486

**Comment by cornhundred** [comment]
That sounds great @jtpio
