### ISSUE TITLE
Nested @interact widgets stop working after first state change

### ISSUE THREAD

**Issue by deluksic** [voila-dashboards/voila#533]
Congrats on making Voila, it's a great solution for our team!

We are hitting a problem where this code does not work as expected:
```python
from ipywidgets import interact

@interact
def test_outer(value1=(0, 10, 1)):
    @interact
    def test_inner(value2=(0, value1, 1)):
        print(value1, value2)
```

In our standard jupyterlab environment, moving the top slider changes the range of the bottom one, and moving any of them changes the print values.

In voila, moving the bottom slider works fine, but after the top slider has been moved, moving the bottom one does not change the output anymore.

Happy to do more tests!

**Comment by Ivorforce** [comment]
I'm also encountering this issue.

**Comment by deluksic** [comment]
Upon further investigation, we found out it's a problem with `voila-material` template we are using.
