### ISSUE TITLE
Execution timeout doesn't make it to the UI

### ISSUE THREAD

**Issue by jeffyjefflabs** [voila-dashboards/voila#538]
If cell execution times out, you get the `Timeout waiting for execute reply (30s)` message in the console, but the UI keeps spinning on the "Executing m of n" message.

**Comment by davidbrochart** [comment]
This is the default behavior, and it will show a `TimeoutError: Cell execution timed out` error in the terminal. If you want to skip the cell execution on timeout, please use the `--VoilaExecutePreprocessor.interrupt_on_timeout=True` option. All options are available with `voila --help-all`.

**Comment by jeffyjefflabs** [comment]
Sorry, maybe I didn't explain very well.  Here's the option you refer to, emphasis added:

> --VoilaExecutePreprocessor.interrupt_on_timeout=<Bool>
>     Default: False
>     If execution of a cell times out, interrupt the kernel and continue
>     executing other cells ***rather than throwing an error and stopping.***

I don't want to skip the cell execution on timeout.  I want it to throw an error and stop; i.e. the default value of False.  The problem is ***the UI*** (the dashboard, in the browser) neither displays an error nor stops.  The spinner with the "Running" or "Executing m of n" message remains indefinitely.   Showing a message in the terminal isn't helpful because the end user of the dashboard doesn't see the terminal.  I'm pretty sure this is a change from earlier versions of Voila, and I'd be surprised if it's the intended behavior.  I would think you'd want the user to know that the execution has failed and will not recover.

**Comment by davidbrochart** [comment]
You are right @jeffyjefflabs, I opened a PR here: https://github.com/voila-dashboards/voila/pull/544

**Comment by jeffyjefflabs** [comment]
Awesome, thanks so much for looking into it!
