### ISSUE TITLE
viola - command not found 

### ISSUE THREAD

**Issue by edoson** [voila-dashboards/voila#545]
Hi,

I've installed viola via pip and conda, but when running `$ viola` i get an error command not found. I guess it's something environmental as I don't see anybody else running into this but I still would appreciate some help.. 

Thanks.

**Comment by SylvainCorlay** [comment]
:smile:

**Comment by SylvainCorlay** [comment]
This is by design :smirk:

**Comment by timkpaine** [comment]
🎻
