### ISSUE TITLE
Font color </a> tag is showing up in the render

### ISSUE THREAD

**Issue by afonit** [voila-dashboards/voila#552]
Versions
|package|version|
|--|--|
|voila|0.1.21|
|python|3.7.6|
|jupyterlab|2.0.0|

In `jupyterlab`, if I render this:
```raw
|Range|Color of Range|
|--|--|
|<= 0|<font color='gray'>Gray</a>|
|1-34|<font color='green'>Green</a>|
|35-59|<font color='orange'>Orange</a>|
|60-99|<font color='red'>Red</a>|
|>=100|At Capacity|
```

It will look like this:
![image](https://user-images.githubusercontent.com/1798497/76084606-42d51400-5f7e-11ea-8ac0-45fe33367589.png)

But when I render it with `voila` the </a> part is getting rendered (unlike when it is in jupyterlab):
![image](https://user-images.githubusercontent.com/1798497/76084675-66985a00-5f7e-11ea-8eb8-10f6952adbad.png)

**Comment by jeffyjefflabs** [comment]
Your tags are mismatched - if you close with `</font>` instead of `</a>` it goes away.  Still an interesting discrepancy though!

**Comment by afonit** [comment]
thanks for the second pair of eyes looking at it - I suppose I just got so fixated on it working in jupyterlab I did not allow myself to see that.

I will probably file a but in jupyterlab so they are aware that mismatch of tags is being allowed.
