### ISSUE TITLE
--enable_nbextensions=True with Binder

### ISSUE THREAD

**Issue by dou-du** [voila-dashboards/voila#559]
Hello,

I want to use Binder with Voila. I also want to show my custom widgets which are not published with npm. How can I show my custom widgets with voila in Binder ? 

I know the command for **voila --enable_nbextensions=True** can show my custom widgets. But I have no ideas how to do it with Binder. Could you give some suggestions ? Thanks.

**Comment by jtpio** [comment]
It's possible to configure Voila to make this work with Binder yes:

https://voila.readthedocs.io/en/latest/deploy.html#customizing-voila-on-binder

For example the voila-demo repo does this here: https://github.com/maartenbreddels/voila-demo/blob/24afc749a3cffc91a555b200a9e39ef9d7bb9c7a/jupyter_config.json#L3
