### ISSUE TITLE
404 for data file created by notebook

### ISSUE THREAD

**Issue by rcpurdue** [voila-dashboards/voila#560]
Hello, my notebook creates a data file (.CSV) and provides a link to download it. The notebook is being served by Voila correctly. The data file is successfully created in the same directory as the notebook. However, when the link is followed, the user's browser gets a 404 error (not found). Also, Voila outputs:

WARNING:tornado.access:404 GET /voila/files/home/jovyan/depot/tmpwf1g6ojd.csv (172.17.0.1) 0.70ms"

Finally, I run Voila using:

voila --no-browser mynotebook.ipynb --VoilaConfiguration.file_whitelist="['.*.(png|csv)']"

Thank you for any help or advice. (And thanks for creating Voila! It is wonderful.)

**Comment by SylvainCorlay** [comment]
Hi @rcpurdue this is actually more of a feature than a bug!

The logic is that voilà actually does not serve the notebook file or anything in the notebook directory which is considered private.

(Obviously, when Voilà runs as a notebook server extension, the notebook application serves all of that, but the point of Voilà is to be usable to produce secure web apps that don't expose the source of the notebook...)

**Comment by maartenbreddels** [comment]
This works with voila I have now (master/ latest alpha, 0.2.0a, but earlier versions should work as well)

Example code:
```
with open('test.csv', "w") as f:
    f.write('tech,grade,greet\n')
    f.write('voila,1,"Hi"\n')
```


Running voila using:
```
$ voila issue/csv.ipynb --VoilaConfiguration.file_whitelist="['.*.(png|csv)']"
```

Download url `http://localhost:8866/test.csv`
