### ISSUE TITLE
404 : Not Found when running voila from jupyterlab

### ISSUE THREAD

**Issue by tylerburleigh** [voila-dashboards/voila#561]
I've installed voila

`pip install voila`

and I've installed the jupyterlab extension

`jupyter labextension install @jupyter-voila/jupyterlab-preview`

When I try to `Render Notebook with Voila` or `Open with Voila in New Browser Tab`, I get a 404 : Not Found error.

![image](https://user-images.githubusercontent.com/3513754/77256554-6a4a0300-6c45-11ea-8a93-182bbaff971a.png)

However when I launch the same notebook using voila from the command line (`voila index.ipynb`) I am able to then access it in a web browser. I think maybe when I launch voila from Jupyterlab it's looking in the wrong place for the file, but I'm not sure how to fix this.

**Comment by tylerburleigh** [comment]
I saw this issue, but I'm not using JupyterHub so I figured this warranted a new issue:
https://github.com/voila-dashboards/voila/issues/560

**Comment by tylerburleigh** [comment]
Oh I found the issue: voila was installed in `/home/tyler/.local/bin` but jupyterlab was trying to run it as root. I fixed it by adding this line to `~/.bashrc`:

`export PATH=/home/tyler/.local/bin:$PATH`

and then 

`source .bashrc`

**Comment by 28-08-2000** [comment]
i got the same error as above( Page you requested does not exist).
Then i followed this
conda install -c conda-forge jupyter
conda install notebook
and then ran jupyter notebook. 
and it worked!!!

**Comment by jasoriya** [comment]
I'm facing this issue and none of the above methods resolves it

**Comment by SylvainCorlay** [comment]
Could you please report the output of

`jupyter serverextension list`?

**Comment by jasoriya** [comment]
`~$ jupyter serverextension list
config dir: /home/cyc/.jupyter
    jupyterlab  enabled
    - Validating...
      jupyterlab 3.0.15 OK
`

**Comment by Skware-Cyber** [comment]
> i got the same error as above( Page you requested does not exist).
> Then i followed this
> conda install -c conda-forge jupyter
> conda install notebook
> and then ran jupyter notebook.
> and it worked!!!

thanks it worked!!
