### ISSUE TITLE
Question: how to achieve true fullscreen?

### ISSUE THREAD

**Issue by AdamJel** [voila-dashboards/voila#564]
Hello, I am creating some app using ipywidgets and voila. I would like the app to span across entire screen.
What I am using is:

```
import ipywidgets as ipw

main_box_layout = ipw.Layout(
    height='100vh',  # viewport height
    width='100%',
    grid_gap='5px',
    overflow='auto',
    align_items='stretch',
    #align_content='stretch',
    margin='0px',
    border='0px',
    padding='0px',
    display='grid',
    grid_template_rows='10% 87% 3%',
    grid_template_columns='8% 92%',
    grid_template_areas='''
        "header header"
        "left_sidebar center"
        "footer footer"
    ''',
)

main_box = ipw.GridBox(
    children=[
        header_box,
        footer_box,
        left_box,
        center,
    ],
    layout=main_box_layout,
)
```

The problem is, no matter how much I try (margin, border, padding = 0), but there is still some space around all edges. And as a consequence, there are width and height scroll bars (see the enclosed images).

One part seems to be 'padding: var(--jp-notebook-padding);' in index.css, which makes 10 px. But it seems, there are other 10px somewhere else. I cannot find it. I don't understand css much, I only briefly excavated it because of my Voila app.

And I have no clue, how to deal with that padding. How can I get rid off that space, please?

![01](https://user-images.githubusercontent.com/33990009/77856670-fdaca680-71f8-11ea-9c93-219aa905ced8.png)
![02](https://user-images.githubusercontent.com/33990009/77856674-04d3b480-71f9-11ea-832a-8a899edeb715.png)
![03](https://user-images.githubusercontent.com/33990009/77856677-08673b80-71f9-11ea-95c5-7b2cb20a5e22.png)

**Comment by timkpaine** [comment]
@AdamJel you need to create your own template for this. As an example, my plaintemplate reduces the padding:
https://github.com/timkpaine/voila-plain/blob/master/share/jupyter/voila/templates/plain/nbconvert_templates/voila.tpl#L21

**Comment by AdamJel** [comment]
> 
> 
> @AdamJel you need to create your own template for this. As an example, my plaintemplate reduces the padding:
> https://github.com/timkpaine/voila-plain/blob/master/share/jupyter/voila/templates/plain/nbconvert_templates/voila.tpl#L21

Thank you @timkpaine  for answering. I hoped for something easier, but I guess I will have to look at how to work with templates.

Though I think, it would be nice to have it at least as an option for calling voila  - like `voila app.ipynb --padding=None`, or as a theme `voila app.ipynb --theme="fullscreen"`

I will go through the templates docs and your example and see. Thank you.

**Comment by timkpaine** [comment]
You can probably inject custom css by using IPython HTML('<style>...') but this can break your view in jupyter, so exercise caution.

**Comment by maartenbreddels** [comment]
Assuming this can be closed, the solution is a custom template or custom css.

**Comment by dfialaire** [comment]
Effectively, 
In my notebook, in the first cell, i just wrote : 
%%HTML
<style>
div.jp-Cell-inputWrapper,
div.jp-Cell {
  overflow: auto;
  border: none;
  padding: 0px;
}
</style>
..... And it works a little : I won some space !
Thank U.
