### ISSUE TITLE
Serve multiple notebooks.

### ISSUE THREAD

**Issue by nanoschm** [voila-dashboards/voila#565]
Hi Guys!

Is it possible serve multiple notebook on a single server?

Thanks!

**Comment by aadrian** [comment]
@nanoschm see at https://voila.readthedocs.io/en/stable/using.html#as-a-standalone-application the *"To serve a directory of Jupyter Notebooks"* section.

**Comment by jtpio** [comment]
Yes indeed, thanks @aadrian!

Closing as answered, but don't hesitate to comment here if you have more questions.

**Comment by gokul-uf** [comment]
Hi @jtpio 
I have a related question.
Is it possible to serve multiple notebooks but without showing the entire directory interface.
For example
`voila.server.com/foo` serves `foo.ipynb` and `voila.server.com/bar` serves `bar.ipynb`

**Comment by jtpio** [comment]
> `voila.server.com/foo` serves `foo.ipynb` and `voila.server.com/bar` serves `bar.ipynb`

This should work yes, it will start 2 different processes. You might have to use a different port with the `--port` command line argument for one of them.
