### ISSUE TITLE
voila not rendering widgets with JS resources on jupyterhub (jupyterlab)

### ISSUE THREAD

**Issue by pbadenski** [voila-dashboards/voila#567]
I have JupyterLab 2.0.1 running via zero-to-jupyterhub-k8s.

I have added `VoilaConfiguration.enable_nbextensions = True` to my jupyterhub_config.py.

But when I open voila in preview I get (example for qgrid):
`require.min.js:1 GET https://jupyter.pricingmonkey.com/user/pawel@pricingmonkey.com/voila/qgrid.js net::ERR_ABORTED 404`
.. and then fallback to unpkg - I have a custom build of qgrid, so that doesn't work.

`jupyter nbextension list`:
```
Known nbextensions:
  config dir: /opt/conda/etc/jupyter/nbconfig
    notebook section
      jupyter-matplotlib/extension  enabled 
      - Validating: OK
      plotlywidget/extension  enabled 
      - Validating: OK
      voila/extension  enabled 
      - Validating: OK
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
```

`jupyter labextension list`:
```
JupyterLab v2.0.1
Known labextensions:
   app dir: /opt/conda/share/jupyter/lab
        @bokeh/jupyter_bokeh v2.0.0  enabled  OK
        @jupyter-voila/jupyterlab-preview v1.0.0  enabled  OK
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        jupyter-matplotlib v0.7.2  enabled  OK
        jupyterlab-plotly v4.6.0  enabled  OK
        plotlywidget v4.6.0  enabled  OK
        qgrid2 v1.1.3  enabled  OK
```

**Comment by jtpio** [comment]
> I have added `VoilaConfiguration.enable_nbextensions = True` to my jupyterhub_config.py.

Was this line added to the `args` option of the spawner?

**Comment by maartenbreddels** [comment]
This needs more info/feedback, please reopen if this issue continues.
