### ISSUE TITLE
Is it possible to open a new voila jupyter from inside another voila

### ISSUE THREAD

**Issue by joseberlines** [voila-dashboards/voila#572]
Hi guys, amazing work with voila.

I am wondering if I can open a voila instance of a jupyter notebook from within another one by clicking a button.
Is that possible?

User case:  There are cases where you want to have several dashboards dedicated to different things open simultaneously. so there might be a central dashboard from where depending on data and on circumstances I would like to open voila jupyter notebook X or Y or Z. Above all when working with several screens that could be very handy.

thanks.

**Comment by davidbrochart** [comment]
In Python you could have a button calling a function with that in it:
```python
import subprocess
subprocess.Popen(['voila', 'other_notebook.ipynb'])
```
And that will open a new tab with a dedicated Voila server.

**Comment by joseberlines** [comment]
So great!!!! thanks a lot

**Comment by jtpio** [comment]
Closing as answered. Thanks @joseberlines and @davidbrochart!
