### ISSUE TITLE
Add _jupyter_server_extension_paths to extension app for next version of jupyter server

### ISSUE THREAD

**Issue by Mistobaan** [voila-dashboards/voila#590]
I am running jupyter-server 0.3.0 and it refuses to load the extension:

> [W 2020-05-04 15:05:18.529 ServerApp] Error loading server extensions in voila.server_extension module. There is no `_jupyter_server_extension_paths` defined at the root of the extension module. Check with the author of the extension to ensure this function is added.

Searching for that strings in the code seems that is the case.

**Comment by Mistobaan** [comment]
Actually is there:
> https://github.com/voila-dashboards/voila/blob/master/voila/__init__.py#L14
for some reason the github search does not find it.

**Comment by davidbrochart** [comment]
Also please note that the current version of Voila doesn't support jupyter-server 0.3.0 (see https://github.com/voila-dashboards/voila/blob/7a774e6b17ce67be2423fb53a90bb5c31750b6fd/setup.py#L379).
