### ISSUE TITLE
Jupyter notebook timout for long computations

### ISSUE THREAD

**Issue by dmahoney1213** [voila-dashboards/voila#596]
You are unable to increase the timeout if running on a Jupyter notebook server. You will receive the same errors mentioned here.

_Originally posted by @Chinmay4400 in https://github.com/voila-dashboards/voila/issues/286#issuecomment-601019658_

**Comment by b060149ee** [comment]
You can add a line in `c.ExecutePreprocessor.timeout = 600` in jupyter_notebook_config.py when usually resides in .jupyter folder in your home directory.

If you do not have that file already there in that folder, you should run a command to generate it. You should easily find the command on the internet.

Although the documents says -1 or None are valid values to that parameter, it does not seem to work in 0.1.21. So give some high value based on your needs

**Comment by jtpio** [comment]
Thanks @b060149ee.

@dmahoney1213  Closing as answered, but don't hesitate to open a new issue for any other question.
