### ISSUE TITLE
Allow installer to choose different CDN

### ISSUE THREAD

**Issue by timkpaine** [voila-dashboards/voila#598]
- [ ] CSS and themes https://github.com/voila-dashboards/voila/blob/master/setup.py#L237
- [ ] loader https://github.com/voila-dashboards/voila/blob/master/js/src/loader.js#L10
- [ ] base template https://github.com/voila-dashboards/voila/blob/master/share/jupyter/voila/templates/default/nbconvert_templates/base.tpl#L12
- [ ] page.html https://github.com/voila-dashboards/voila/blob/master/share/jupyter/voila/templates/default/templates/page.html#L16

**Comment by trungleduc** [comment]
Loading extensions from CDN is removed in 0.5.0
