### ISSUE TITLE
[master] theme=dark does not appear to be taken into account on master

### ISSUE THREAD

**Issue by SylvainCorlay** [voila-dashboards/voila#601]

**Comment by maartenbreddels** [comment]
Using git bisect, I know it is 1e36145dcd7640b631fd92a706adf807ed9a36b5 not sure if this issue is due to voila or upstream libraries (nbconvert)?

**Comment by maartenbreddels** [comment]
Ok, this issue was fixed in https://github.com/voila-dashboards/voila/pull/208/files#diff-da3df63b00696d9c775762da2f14fa41R82 I think we should rebase and merge that, so we don't again find issues that are already solved on that PR.

**Comment by jtpio** [comment]
Closing as this seems to be fixed on master.
