### ISSUE TITLE
Voila drop down widget not working

### ISSUE THREAD

**Issue by prachi-tripathi** [voila-dashboards/voila#603]
In Jupyter  Notebook  my ipywidgets Drop down working fine. But when i am using same Jupyter notebook and hosting using Voila(using material theme) to local host my drop down not showing. Can anyone please suggest why its not working . Thank you!!

- 1st image  working fine with jupyter.

- 2nd image not working using voila.

![USING JUPYTER NOTEBOOK WORKING FINE](https://user-images.githubusercontent.com/64902564/82114718-1c9cd300-977c-11ea-86cd-1f6e5ce6b265.PNG)
![USING VOILA NOT WORKING](https://user-images.githubusercontent.com/64902564/82114721-1dce0000-977c-11ea-85cc-3d426844c533.PNG)

**Comment by SylvainCorlay** [comment]
Hi @prachi-tripathi, thanks for reporting.

Could you please report if you see any error in the JS console of the browser in the Voilà case?

**Comment by prachi-tripathi** [comment]
Hi Sylvain ,

Many thanks for quick reply, please find below the screenshot of JS
console. FYI, all the widgets which i have used in my project are working
except Drop down.
Note : I have removed the header section from voila material template
(Voila Radio button + Image)

Thanks & Regards,a
Prachi Tripathi

**Comment by SylvainCorlay** [comment]
@prachi-tripathi it seems the JS console log was not included in your message. It may be that email attachments are not added to GitHub issues. It is probably more convenient to respond from GitHub.

**Comment by prachi-tripathi** [comment]
@SylvainCorlay  please refer below screenshot.
![Capture](https://user-images.githubusercontent.com/64902564/82151652-20168400-987a-11ea-9432-52a849b84b8c.PNG)

**Comment by SylvainCorlay** [comment]
Thanks, this is not the js console though. The js console can be displayed in the web browser by launching the developer tools. Crtl + Shift + J.  A minimal code reproducer would help too!

**Comment by prachi-tripathi** [comment]
@SylvainCorlay  please refer below.

![Capture 3](https://user-images.githubusercontent.com/64902564/82153982-78548280-9888-11ea-9298-834721062646.PNG)
![Capture 4](https://user-images.githubusercontent.com/64902564/82153983-7a1e4600-9888-11ea-80e4-a3dea770af79.PNG)
[error js.txt](https://github.com/voila-dashboards/voila/files/4640574/error.js.txt)

**Comment by maartenbreddels** [comment]
Hi,

does this only occur the material theme? Did you check the normal theme? If could also be a CSS issue

Regards,

Maarten

**Comment by prachi-tripathi** [comment]
@maartenbreddels  Hi, 

Using normal theme drop down working but name of the drop down is partially showing. 
![Capture](https://user-images.githubusercontent.com/64902564/82248771-4ca7ca00-9966-11ea-935d-f71e01fe5527.PNG)

**Comment by SylvainCorlay** [comment]
This may be plotly's css interfering with the rest of the page?

@prachi-tripathi do you have a minimal code reproducer?

**Comment by prachi-tripathi** [comment]
menu = np.array(country_df['country'].values.tolist()) 
menu = np.unique(menu)

CountryBarWidget = widgets.Dropdown(options=menu,
    value='US',
    description='<p style = "font-family:Trebuchet MS;font-size:15px;font-style:bold;font- 
 color:#999999;"><b>Countries</b></p> :</br></br>',
    disabled=False
)

def countryBar(country):
    country = country_df.loc[country_df['country'] == country]
   
    figBar = go.Figure(
        data=[
            go.Bar(
                name="Confirmed",
                x= country['country'],
                y= country['confirmed'],
                marker=dict(color='#0000FF')
               
                
            ),
            go.Bar(
                name="Deaths",
                x=country['country'],
                y=country['deaths'],
                marker=dict(color='#FF0000')
                
            ),
            go.Bar(
                name="Recovered",
                x=country['country'],
                y=country['recovered'],
                marker=dict(color='#7CFC00')
                
            ),
        
        ],
        layout=go.Layout(
            title="Confirmed Recoverd And Death Cases over the world",
            yaxis_title="Count of Confirmed Recoverd & Death Cases",
            xaxis_title="Country",
            font=dict(family="Trebuchet MS",size=16,color="#778899"),
            xaxis_showgrid=True,
            yaxis_showgrid=True,
            width=700,
            height=600,
            paper_bgcolor='rgba(0,0,0,0)',
            plot_bgcolor='rgba(0,0,0,0)'
        )
        
    )

    figBar.update_xaxes(zeroline=True, zerolinewidth=2, zerolinecolor='#DCDCDC')
    figBar.update_yaxes(zeroline=True, zerolinewidth=2, zerolinecolor='#DCDCDC'),
    fig.update_yaxes(automargin=True)
    
    
    figBar.show();
  

  
widgets.interact(countryBar,country = CountryBarWidget);

**Comment by prachi-tripathi** [comment]
@SylvainCorlay please refer below code.

menu = np.array(country_df['country'].values.tolist()) 
menu = np.unique(menu)

CountryBarWidget = widgets.Dropdown(options=menu,
    value='US',
    description='<p style = "font-family:Trebuchet MS;font-size:15px;font-style:bold;font-color:#999999;"><b>Countries</b></p> :</br></br>',
    disabled=False
)

def countryBar(country):
    country = country_df.loc[country_df['country'] == country]
   
    figBar = go.Figure(
        data=[
            go.Bar(
                name="Confirmed",
                x= country['country'],
                y= country['confirmed'],
                marker=dict(color='#0000FF')
               
                
            ),
            go.Bar(
                name="Deaths",
                x=country['country'],
                y=country['deaths'],
                marker=dict(color='#FF0000')
                
            ),
            go.Bar(
                name="Recovered",
                x=country['country'],
                y=country['recovered'],
                marker=dict(color='#7CFC00')
                
            ),
        
        ],
        layout=go.Layout(
            title="Confirmed Recoverd And Death Cases over the world",
            yaxis_title="Count of Confirmed Recoverd & Death Cases",
            xaxis_title="Country",
            font=dict(family="Trebuchet MS",size=16,color="#778899"),
            xaxis_showgrid=True,
            yaxis_showgrid=True,
            width=700,
            height=600,
            paper_bgcolor='rgba(0,0,0,0)',
            plot_bgcolor='rgba(0,0,0,0)'
        )
        
    )
    #figBar.update_xaxes(showgrid=True, gridwidth=1, gridcolor='#DCDCDC')
    #figBar.update_yaxes(showgrid=True, gridwidth=1, gridcolor='#DCDCDC')
    figBar.update_xaxes(zeroline=True, zerolinewidth=2, zerolinecolor='#DCDCDC')
    figBar.update_yaxes(zeroline=True, zerolinewidth=2, zerolinecolor='#DCDCDC'),
    fig.update_yaxes(automargin=True)
    
    display(HTML('<br><br><br><br>'))
    figBar.show();
    display(HTML('<br><br><br><br>'))

display(HTML('<br><br><div style = "font-family:Trebuchet MS;font-size:24px;color:#999999;">Select the Country from Drop Down</div><br>'))    
widgets.interact(countryBar,country = CountryBarWidget);

**Comment by prachi-tripathi** [comment]
@SylvainCorlay Please refer below code !!

```
menu = np.array(country_df['country'].values.tolist()) 
menu = np.unique(menu)

CountryBarWidget = widgets.Dropdown(options=menu,
    value='US',
    description='<p style = "font-family:Trebuchet MS;font-size:15px;font-style:bold;font-color:#999999;"><b>Countries</b></p> :</br></br>',
    disabled=False
)

def countryBar(country):
    country = country_df.loc[country_df['country'] == country]
   
    figBar = go.Figure(
        data=[
            go.Bar(
                name="Confirmed",
                x= country['country'],
                y= country['confirmed'],
                marker=dict(color='#0000FF')
               
                
            ),
            go.Bar(
                name="Deaths",
                x=country['country'],
                y=country['deaths'],
                marker=dict(color='#FF0000')
                
            ),
            go.Bar(
                name="Recovered",
                x=country['country'],
                y=country['recovered'],
                marker=dict(color='#7CFC00')
                
            ),
        
        ],
        layout=go.Layout(
            title="Confirmed Recoverd And Death Cases over the world",
            yaxis_title="Count of Confirmed Recoverd & Death Cases",
            xaxis_title="Country",
            font=dict(family="Trebuchet MS",size=16,color="#778899"),
            xaxis_showgrid=True,
            yaxis_showgrid=True,
            width=700,
            height=600,
            paper_bgcolor='rgba(0,0,0,0)',
            plot_bgcolor='rgba(0,0,0,0)'
        )
        
    )
    
    figBar.update_xaxes(zeroline=True, zerolinewidth=2, zerolinecolor='#DCDCDC')
    figBar.update_yaxes(zeroline=True, zerolinewidth=2, zerolinecolor='#DCDCDC'),
    fig.update_yaxes(automargin=True)
    

    figBar.show();
   

display(HTML('<br><br><div style = "font-family:Trebuchet MS;font-size:24px;color:#999999;">Select the Country from Drop Down</div><br>'))    
widgets.interact(countryBar,country = CountryBarWidget);
```

**Comment by prachi-tripathi** [comment]
@SylvainCorlay ,

Hi any update please?

**Comment by martinRenou** [comment]
Hi, this is all related to the material template actually.

It has been fixed in the template: https://github.com/voila-dashboards/voila-material/pull/13 and released in voila-material 0.3.0. Please try to update.

This issue can be closed.

**Comment by prachi-tripathi** [comment]
@martinRenou 
hi, 
Thank you drop down is working fine for material template but the name of the drop down still partially coming please refer the screenshot. And same problem also with default template. 
![Capture](https://user-images.githubusercontent.com/64902564/83562588-78ff4100-a537-11ea-9e35-da712a444187.PNG)

**Comment by martinRenou** [comment]
Are you confortable with browser developer tools?

You can right click on the dropdown label and click `Inspect` or `Inspect Element` depending on your browser. And maybe you could find if there is another element in front of the label?

**Comment by martinRenou** [comment]
Would you be able to provide a sample of code that helps us replicate the issue? I see you provided some code, but it relies on variables that are not defined. It would be easier for us if we could just copy and paste the code and replicate the issue. Thanks a lot!

**Comment by prachi-tripathi** [comment]
@martinRenou  please refer the below screenshots and code text file of inspected elements - multiple layers of div is the over label.
[DrropDown Error.txt](https://github.com/voila-dashboards/voila/files/4721690/DrropDown.Error.txt)


![Screenshot (119) - Copy](https://user-images.githubusercontent.com/64902564/83609129-71718380-a59b-11ea-9309-920cc102170e.png)
![Screenshot (119)](https://user-images.githubusercontent.com/64902564/83609132-73d3dd80-a59b-11ea-9509-58442a6dc00d.png)
![Screenshot (120) - Copy](https://user-images.githubusercontent.com/64902564/83609137-746c7400-a59b-11ea-8b7b-9ee3631fa76e.png)
![Screenshot (120)](https://user-images.githubusercontent.com/64902564/83609139-75050a80-a59b-11ea-8466-e73ef84af35b.png)
![Screenshot (121) - Copy](https://user-images.githubusercontent.com/64902564/83609147-76cece00-a59b-11ea-8986-3c76b478072b.png)
![Screenshot (121)](https://user-images.githubusercontent.com/64902564/83609149-77676480-a59b-11ea-890f-39d2a9d54186.png)

**Comment by martinRenou** [comment]
Thanks a lot. I will look into it.

**Comment by martinRenou** [comment]
I might be wrong, but it looks like the plotly plot takes to much space and hides the label a bit. Let me suggest to try a bit of CSS.

Your last line of code is:
```python
widgets.interact(countryBar,country = CountryBarWidget);
```

Would you mind trying to replace it with:
```python
w = widgets.interactive(countryBar,country = CountryBarWidget)

w.layout.height = '800px'  # Feel free to tweak this value to get what you want
display(w)
```

**Comment by prachi-tripathi** [comment]
@martinRenou @SylvainCorlay @maartenbreddels 
Thank you so much all of you for coordinating !! Drop down issues resolved and working perfectly !!

@martinRenou  I have tried above code that is working perfectly in voila but the thing is, when use interact there is no need to use display(w) because by default it will show the widget. So, when i am using this display(w) its displaying  2 drop down. But i tired something else that issue also resolved.


![solved](https://user-images.githubusercontent.com/64902564/83631083-91fd0600-a5ba-11ea-950c-6cb3880bcdea.PNG)

**Comment by prachi-tripathi** [comment]
Since, issue been resolve we can close the issue now.
Thank you so Much!!
