### ISSUE TITLE
re-render specific cell after initial execution

### ISSUE THREAD

**Issue by TristanK27** [voila-dashboards/voila#614]
For my use-case I want to execute a specific cell when a button is pressed to update the data present in the plot.
I created this demo to make clear what I want to achieve:
```
import altair as alt
import pandas as pd
import ipywidgets as widgets
import functools
from IPython.display import Javascript
``` 
```
data = {
    'id': ['test1'],
    'fuel': [1]
}
df = pd.DataFrame(data, columns=['id', 'fuel']) # dataframe with original data
```
```
def on_click(b, new_df):
    new_df.loc[len(new_df)] = ['test2', 5] #adding data to existing df
    display(Javascript("Jupyter.notebook.execute_cells([3])"))
    
button = widgets.Button(description="Refresh")
button.on_click(functools.partial(on_click, new_df=df))
display(button)
```
```
alt.Chart(df).mark_point().encode(
    x='id',
    y='fuel',
)
```
Before button press | After button press
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/20356336/82545822-7e33b780-9b57-11ea-878c-dac2bba19db8.png)  |  ![image](https://user-images.githubusercontent.com/20356336/82545881-91468780-9b57-11ea-8856-4c8d6578d657.png)

This works just fine when executed in Jupyter notebook directly but this doesn't seem to work when the notebook is executed with voila. Why is this happening and is there a way to get the desired result some other way?

**Comment by SylvainCorlay** [comment]
Note: this "trick" is specific to the classic notebook and will not work in JupyterLab either.

This will not be supported by Voilà. In Voilà, the front-end never has access to the notebook file so that you cannot request execution of a cell.

One way to have charts update on button click is to use a plotting widget library like bqplot, ipyvolume, etc. Altair is really for display only.

**Comment by TristanK27** [comment]
Thank you, I didn't know that it works like that. Bqplot ended up being perfect for my use case :)
