### ISSUE TITLE
Widgets not defined

### ISSUE THREAD

**Issue by dmadeka** [voila-dashboards/voila#615]
Using voila 0.1.21 and bqplot 0.12.11 I get an `HBox is not defined` error

Do i need to upgrade something or use voila dev?

**Comment by jtpio** [comment]
@dmadeka can `HBox` be imported from `ipywidgets`?

```python
from ipywidgets import HBox
```

**Comment by dmadeka** [comment]
the code does run outside voila. See here - https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html

```python
widgets.HBox([widgets.Label(value="The $m$ in $E=mc^2$:"), widgets.FloatSlider()])
```

**Comment by dmadeka** [comment]
@jtpio It definitely works outside voila. Seems to be a [recurring issue](https://github.com/voila-dashboards/voila/issues/15)

**Comment by jtpio** [comment]
> Using voila 0.1.21 and bqplot 0.12.11 I get an `HBox is not defined` error

Can you post a screenshot of what you get with voila?

**Comment by dmadeka** [comment]
@jtpio it just says `HBox is not defined`

**Comment by jtpio** [comment]
This is what it should look like with the latest Voila:

![image](https://user-images.githubusercontent.com/591645/82686932-e7e6bb00-9c56-11ea-9aec-d0b18562fd74.png)

(showing it in JupyterLab to have the notebook code and the voila dashboard side-by-side)

**Comment by dmadeka** [comment]
@jtpio yeah seems to be a kernel issue - but its not clear why running with the right kernel wouldnt work

**Comment by jtpio** [comment]
Normally voila starts the right kernel by looking at the kernel name from the notebook metadata.

Whats does `jupyter kernelspec list` give?

**Comment by jtpio** [comment]
> Its strange because Im running `~/anaconda3/bin/python3.7 -m voila ....`

This looks like the python from the base environment? Would it be possible to try in a fresh new environment?

**Comment by dmadeka** [comment]
Different environment worked! Thanks!
