### ISSUE TITLE
Add option to show error tracebacks to user without logging everything

### ISSUE THREAD

**Issue by vidartf** [voila-dashboards/voila#616]
Currently, if you start voila in `--debug` mode almost *everything* gets logged. It would be nice to have a way to enable traceback for "developer" dashboards deployments without having the logs be as verbose as they are. Currently they are linked one-to-one here:

https://github.com/voila-dashboards/voila/blob/80b120c805fba3f3b33bc5b46f9eea52473b6f78/voila/execute.py#L36-L38

A possibility would be to add a separate config option "send_tracebacks" that defaults to the current value (dependent on log level) if unset.

**Comment by SylvainCorlay** [comment]
Maybe `show_tracebacks` instead of `send_tracebacks`.

**Comment by vidartf** [comment]
Agreed. I would make a PR for this, but for the dev install on Windows a bunch of tests fail on master, so I assume Windows contributors are not supported 😉
