### ISSUE TITLE
Custom Widget results are not shown on voila dashboard.

### ISSUE THREAD

**Issue by sackh** [voila-dashboards/voila#627]
I really liked the voila library and I have used it along with `ipyleaflet` and it works fine and I could see the results on the dashboard link. I have created a custom widget similar to `ipyleaflet` and it works fine in Jupyter notebook and Jupyter lab but when I run it using voila I do not see results on the dashboard link only black page appears.
Can someone please guide me on how I can debug this issue?
Please let me know if any additional details are required.

<img width="740" alt="Screenshot 2020-06-10 at 12 13 13 PM" src="https://user-images.githubusercontent.com/8600927/84235802-19df9480-ab14-11ea-9fb3-6f7367d38ba5.png">

**Comment by gbrault** [comment]
I have the same issue: an ipywidget runing well in a given Jupyter Lab server and the voila lab extension not working.
It seems voilà is not reusing the jupyter Lab "context" and tries to rebuild it's own...
Off course, voila tries to upload the custom ipywidget and as this one is not in npm nor pypi, it fails loading it.
Is there a way to parameter jupyter config file to have voila share the same python environment and the same javascript files and other resources as the jupyter lab server?
Thx

**Comment by martinRenou** [comment]
No if your JavaScript package is not uploaded to npmjs, you need to pass the option `--enable_nbextensions=True` to Voila to make it work.

By default Voila downloads the extension on npmjs, and apparently you did not upload it to it, so you need to tell Voila to use the local nbextensions.

**Comment by jtpio** [comment]
> If your JavaScript package is not uploaded to npmjs, you need to pass the option --enable_nbextensions=True to Voila to make it work.

There is also some documentation about this option here: https://voila.readthedocs.io/en/latest/using.html#using-third-party-widgets-with-voila

Closing as answered, but feel free to comment here if you have any question.

**Comment by sackh** [comment]
Thank you this is resolved 👍

**Comment by gbrault** [comment]
It doesn't work for me, but my extension is not a "classic notebook" but a jupyter lab extension...

Any idea?

**Comment by martinRenou** [comment]
Is it a local extension you built?

You might be able to install an nbextension by doing:
```bash
jupyter nbextension install --py --symlink --sys-prefix package_name
jupyter nbextension enable --py --sys-prefix package_name
```

And then start Voila with the  `--enable_nbextensions=True` option.

**Comment by gbrault** [comment]
Many thanks @martinRenou , I am moving forward.
But still some small issues pending

![voila issue](https://user-images.githubusercontent.com/7886676/84254522-a177d400-ab11-11ea-8be7-6bf659dd46d2.png)


The widget works in the "classic Notebook" now.

![work_in_classic](https://user-images.githubusercontent.com/7886676/84253872-bf910480-ab10-11ea-82e8-65599dd7bd52.png)

**Comment by gbrault** [comment]
As you can see, I have started the jupyter lab with the voila parameter...
How can I check programatically that this is taken into effect in a notebook, importing voila?

![image](https://user-images.githubusercontent.com/7886676/84254899-2367fd00-ab12-11ea-89c1-712c3c96b942.png)

**Comment by gbrault** [comment]
I have try just with voilà

![image](https://user-images.githubusercontent.com/7886676/84259711-2c100180-ab19-11ea-876b-e604de902700.png)

**Comment by gbrault** [comment]
And have the same issue with nbdime?

**Comment by jtpio** [comment]
@gbrault nbdime is mostly meant to be used as an extension in JupyterLab and the classic notebook (not sure it's relevant for a voila dashboard?)

**Comment by jtpio** [comment]
@gbrault 

> The widget works in the "classic Notebook" now.

Does it work with Voila too? If not, would it be possible to post a screenshot of what it looks like when rendered with Voila?

**Comment by gbrault** [comment]
![image](https://user-images.githubusercontent.com/7886676/84353585-bd39b380-abbf-11ea-9ef7-3d8372f46182.png)

**Comment by gbrault** [comment]
It seems I get it fixed...
My assumption is that voila stops everything if any required javascript is missing. In that case it was base/js/dialog (which is in the classic notebook but not in the lab nor in voila) and as it was not defined but required, everything failed. I suppressed this from the js code of the sqlgrid component and now "c'est tombé en marche"...

**Comment by gbrault** [comment]
@jtpio , @martinRenou (@SylvainCorlay) and All: Do you know where I can find a spec which describes how an ipywidget derived component must declare its resources from a js and py perspective?
Many thanks! Would help me a lot!

**Comment by gbrault** [comment]
Works with the Jupyter Lab voila extension as well?
![image](https://user-images.githubusercontent.com/7886676/84354292-e575e200-abc0-11ea-9215-12932bbb597d.png)

**Comment by jtpio** [comment]
Looking good, thanks @gbrault for the updates!

> Do you know where I can find a spec which describes how an ipywidget derived component must declare its resources from a js and py perspective?

We usually recommend starting from the TypeScript cookiecutter, which takes care of all the TS and Python boilerplate that make widgets work in JupyterLab, the classic notebook and Voila: https://github.com/jupyter-widgets/widget-ts-cookiecutter

It looks like the issues you have been facing were however more related to qgrid (also reported several times in https://github.com/voila-dashboards/voila/issues/72).

**Comment by gbrault** [comment]
You are right @jtpio it's linked to sqlgrid (which is my fork of qgrid) and I have found the same corrective action as mentioned in #72 !
Thanks for your support.

**Comment by anxhelahyseni** [comment]
@jtpio I am trying to display voila with itables, but when voila gets rendered only the table header shows up no content of the table. Do you have any idea why it might happen?

**Comment by jtpio** [comment]
> I am trying to display voila with itables

Does this refer to this project? https://github.com/mwouts/itables

It would be better to open an issue there if it's really specific to this widget.

**Comment by jtpio** [comment]
@anxhelahyseni it looks like itables is specific to the classic notebook (and could explain why it doesn't work with voila): https://github.com/mwouts/itables/issues/3

**Comment by anxhelahyseni** [comment]
@jtpio Thank you for you reply. It was weird because on a normal jupyter notebook it was working but in jupyterlab it is not working either.

**Comment by jtpio** [comment]
>  Is there any table package that is currently working with voila? I tried a couple and none worked either.

`ipysheet` should work with Voila: https://github.com/QuantStack/ipysheet

Although it's more of a spreadsheet widget, it may work for your use case?

**Comment by anxhelahyseni** [comment]
@jtpio I have large data and i want something more interactive with pagination and a good looking as it is for researchers to show their work,

**Comment by DougRzz** [comment]
@anxhelahyseni you could try my implementation of the ipyvuetify table https://github.com/mariobuikhuizen/ipyvuetify/issues/71#issue-630953624

**Comment by heng2j** [comment]
Hi @anxhelahyseni @DougRzz , we are also trying to interact with a large dataset (1-3GBs) in Voila. However as in Voila version `0.2.7`, we observed that Voila is not responsive if it needs to interact with more than 1.5GB of data. Any recommendation?

**Comment by jtloong** [comment]
@anxhelahyseni late to the thread but for anyone else trying to get `itables` to work with Voila there seems to be a fix. I had the same issue with blank tables in Voila but seeing it in Jupyter. With the newer versions of `itables>=0.4.0` if you enable the below:

``` python
from itables import init_notebook_mode, show
init_notebook_mode(all_interactive=True)
```

That should enable itables to work nicely with a Voila dashboard. I got the fix from this thread as they've had a lot of issues with JupyterLab and Colab: https://github.com/mwouts/itables/issues/26
