### ISSUE TITLE
Widget loading indicator

### ISSUE THREAD

**Issue by maartenbreddels** [voila-dashboards/voila#634]
Loading widgets can take a while, especially since user sometimes create 1000's of widgets (#534). I think it would be good to show an indicator of when the widgets are loading, instead of a white screen (as is the case now). This is also implemented in voila-vuetify https://github.com/voila-dashboards/voila-vuetify/commit/90d84a615aa87e0ec8150c9cd9c949fab29672b7

**Comment by maartenbreddels** [comment]
Related #460

**Comment by mgmarino** [comment]
(First off, we are very happy about the work being done here, thank you for that.)  A feature like this would be incredibly helpful.  We are using voila extensively in production to build/serve dashboards.  A major question we get from our users is: why is the screen white for so long?  

I have two points:

- I think it may possibly be confusing to have the current "cell" execution indicator and *then* another indicator that's also counting up.  Maybe it's out of scope for this issue, but at least having the possibility to customize the output (e.g. so we can tailor the text/output so as not to confuse our C-level users) would be helpful.
- Do you see this as a good starting issue to work on to help out?
