### ISSUE TITLE
Voila on Heroku - error connecting to mongodb

### ISSUE THREAD

**Issue by tomnewg** [voila-dashboards/voila#641]
Hi guys,

I have a jupyter notebook that loads data out of mongodb with the help of arctic.
The connection works fine on my localhost with voila. It also works fine on my Jupiterhub server. When deploying it on heroku I get the "there is an error executing cell" 

I tried the connection with pymongo and arctic, both don't work. I am not an expert on server and database settings but it seems to me that it is a voila issue as I can perfectly access the database with jupyterhub.

Procfile: web: voila --port=$PORT --no-browser notebooks/db_test.ipynb
runtime.txt: python-3.8.3

example with pymongo:
import pymongo
client = pymongo.MongoClient("mongodb+srv://<user and db details>?retryWrites=true&w=majority")
client.list_database_names()
-> "There was an error when executing cell [3]. Please run Voila with --debug to see the error message." (by the way I don't know how to run the voila --debug on Heroku)

Any idea what to change either in settings? heroku? or in the code? 
Should it work in general?

Many thanks for your help in advance

Tom

**Comment by martinRenou** [comment]
Hey!

Can you try passing the `--debug` option to Voila? You just need to change your `Procfile` by adding `--debug` behind your voila command.

**Comment by martinRenou** [comment]
`web: voila --debug --port=$PORT --no-browser notebooks/db_test.ipynb`

**Comment by tomnewg** [comment]
thanks @martinRenou 
I can now debug haha and actually found a mistake. I forgot to install dnspython which I also installed on my jupyterhub.
I thought now it should work but the voila build up gets stuck now on the cell "client.list_database_names()"

It doesn't give me an error message the wheel just keeps spinning and looking in the logs it also just stuck and gives a timeout error eventually.
2020-06-25T10:02:38.911512+00:00 app[web.1]: [Voila] ERROR | Timeout waiting for execute reply (30s).
and then: 
2020-06-25T10:03:03.909435+00:00 heroku[router]: at=error code=H15 desc="Idle connection" method=GET path="/" 

Any other suggestions?

Many thanks

**Comment by martinRenou** [comment]
Is your database online or is it next to your Jupyter Notebook?

**Comment by tomnewg** [comment]
online in the mongodb atlas cloud

**Comment by martinRenou** [comment]
Do you see any error in the JavaScript console? Any `404` error? (`ctrl` + `shift` + `J` for opening the console on Chrome, `ctrl` + `shift` + `K` on Firefox)

**Comment by tomnewg** [comment]
nope 
I get: Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING

**Comment by tomnewg** [comment]
I am so sorry. I found my mistake. I didn't white list the heroku ip.
It works fine now.

Thank you for your help Martin. We can close this issue.
