### ISSUE TITLE
ipywidgets interact dataframe not displaying on Voila

### ISSUE THREAD

**Issue by ishan42d** [voila-dashboards/voila#645]
Hello,
I have been trying to display an interactive data frame that I have created using interact, on the jupyter notebook it is showing fine but when I am seeing the same on Voila, it is not showing up there and also it is not showing if I convert my notebook to an HTML. My code is a basic one;it has a dropdown basis which I am able to filter on different columns
`import ipywidgets as widgets
from ipywidgets import interact, interact_manual
                  @interact
                 def show_case(column=['TotalCases', 'NewCases', 'TotalDeaths', 'NewDeaths','ActiveCases'], 
                            x=(10,10000,10)):
    return df_final.loc[df_final[column] > x]`

I have the latest versions of voila and nbconvert installed on my system. Then what is the reason that the interactive table is not showing up on Voila?

**Comment by afonit** [comment]
@ishan42d , 
* what versions specifically are you using, both of jupyterlab and voila?
* do you have code you can share to reproduce the table and interaction
* could you take some screenshots to give more context?

**Comment by ishan42d** [comment]
this is resolved now. added clear_ouput and it worked fine.
