### ISSUE TITLE
Unable to see pymc3 progressbar running in Voila-dashboard view

### ISSUE THREAD

**Issue by atharvahans1** [voila-dashboards/voila#648]
Hello,

I am trying to display a progressbar for my pymc3 code. I cannot see the progressbar running using the Voila-dashboard view. All i see is a grey box.
<img width="834" alt="Screen Shot 2020-07-13 at 11 26 16 AM" src="https://user-images.githubusercontent.com/56398096/87322884-01401100-c4fc-11ea-8461-fff5b0b98684.png">

When I use the Voila-gridstack view it work fine. 
<img width="824" alt="Screen Shot 2020-07-13 at 11 24 51 AM" src="https://user-images.githubusercontent.com/56398096/87323310-9d6a1800-c4fc-11ea-94d7-5aad1cb04015.png">.

How can I fix this?

Thanks,
Atharva

**Comment by jtpio** [comment]
Thanks @atharvahans1.

Do you use a specific package for the progress bar?

Are there any error logged in the browser dev tools console?

**Comment by atharvahans1** [comment]
@jtpio thanks for the quick reply. 

I use the progress bar that is in-build in the pymc3 module. 

There are no errors logged in the browser dev tools console.

**Comment by jtpio** [comment]
@atharvahans1 would it be possible to create a small example that runs on Binder?(for example as a GitHub gist)

**Comment by atharvahans1** [comment]
@jtpio i created an example (https://gist.github.com/atharvahans1/68044ff6d1f093b7d1d788929231754d). Is that what you meant?

**Comment by jtpio** [comment]
Yes, thanks!

Now we just need to add a file called `environment.yml` to the gist, that would look like the following:

```yaml
name: voila-pymc3
channels:
  - conda-forge
dependencies:
  - ipywidgets
  - pymc3
  - voila=0.1.21
```

So the example can be tested on https://mybinder.org/

**Comment by atharvahans1** [comment]
@jtpio i added the `environment.yml` to the gist (https://gist.github.com/atharvahans1/68044ff6d1f093b7d1d788929231754d)

**Comment by jtpio** [comment]
Thanks @atharvahans1.

Looks like `mkl-service` should also be added to the `environment.yml` to have everything working on Binder:

```yaml
name: voila-pymc3
channels:
  - conda-forge
dependencies:
  - ipywidgets
  - mkl-service
  - pymc3
  - voila=0.1.21
```

Then it can be tested here:

https://mybinder.org/v2/gist/atharvahans1/68044ff6d1f093b7d1d788929231754d/2af7888a6daf587ee337dfa437feded3f71ae5ba

It is indeed the case that the progress bar doesn't render in Voila:

![image](https://user-images.githubusercontent.com/591645/87515993-f8c31400-c67c-11ea-956e-70b80b41b7bb.png)

But the same seems to be happening in JupyterLab:

![image](https://user-images.githubusercontent.com/591645/87516414-a33b3700-c67d-11ea-98db-6e0c2d2fffff.png)

Could it be an issue with the `pymc3` package, which relies on elements specific to the classic notebook?

**Comment by atharvahans1** [comment]
@jtpio you are right, the issue is with `pymc3`. The progress bar in the lastest version of pymc3 (3.9) does not work with Voila. 

I tried running the same code in the older version (3.7) and it worked just fine. Thanks for the help!
