### ISSUE TITLE
Build the documentation on CI

### ISSUE THREAD

**Issue by jtpio** [voila-dashboards/voila#649]
It would be nice to have a job on CI that builds the documentation.

Either as a simple GitHub Actions workflow that does:

```bash
cd docs/
python -m pip install -r doc-requirements.txt
make html
```

Or maybe using the readthedocs "Autobuild Documentation for Pull Requests": https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html

**Comment by maartenbreddels** [comment]
Yeah, that last thing sounds like a good idea. What is the purpose of it, to check if it builds at all, or if it renders correctly? If the last, I don't know how we can preview it with GHA.

**Comment by jtpio** [comment]
> What is the purpose of it, to check if it builds at all, or if it renders correctly?

To check that it builds correctly. If we can have the rendered version it would be even nicer!

**Comment by maartenbreddels** [comment]
I enabled it in RTD, do you wanna test it out?

**Comment by jtpio** [comment]
Closing and opening an existing PR might be enough to trigger the build event?

**Comment by jtpio** [comment]
Opened https://github.com/voila-dashboards/voila/pull/650, but the readthedocs check doesn't seem to be triggered.

![image](https://user-images.githubusercontent.com/591645/87416492-1174f080-c5cf-11ea-81a5-440fa6fb47fa.png)

**Comment by jtpio** [comment]
Fixed by https://github.com/voila-dashboards/voila/pull/650#issuecomment-658120051.

Check out https://github.com/voila-dashboards/voila/pull/650 and https://github.com/voila-dashboards/voila/pull/650#issuecomment-658122443 for more info.
