### ISSUE TITLE
visualizing pdfs with voila (embedded in a voila Dashboard)

### ISSUE THREAD

**Issue by joseberlines** [voila-dashboards/voila#659]
User case: The user wants to visualize one or several pdfs rendering them with voila.
Why? wants to compared pdfs, with ipywidgets a gui is provided letting the user to choose pdfs from a list.

I tried the following:
```
myleft = widgets.Output(layout=mylayout)
mycenter = widgets.Output(layout=mylayout)
myright = widgets.Output(layout=mylayout)

with myleft:
    display(IFrame(rel_path_1, width=500, height=600))
with mycenter:
    display(IFrame(rel_path_2, width=500, height=600))
with myright:
    display(IFrame(rel_path_3, width=500, height=600))

mybox = HBox([myleft,mycenter,myright])
mybox

```
Where rel_path is a relative path to a local stored pdf.

This works within the jupyter notebbok, but when rendering with voila a 403: Forbidden error appears for every of the pdfs.

FIRST WORKAROUND:
Trying with HTML widget:
```
value=r'<iframe width="500" height="600" src="C:\....\mypdf.pdf" frameborder="1" allowfullscreen></iframe>'
myhtml =widgets.HTML(
    value=value,
    placeholder='Some HTML',
    description='Some HTML',
)
myhtml
```
does not work in jupyter notebook, nor in voila

SECOND WORKAROUND
```
value=r'<div><embed type= "application/pdf" src="C:\Users\JF30443\Desktop\PDFs_letters\applicants_letter.pdf" style="width:100%; height:620px"</embed></div> '
myhtml =widgets.HTML(
    value=value,
    placeholder='Some HTML',
    description='Some HTML',
)
myhtml
```

does not work in jupyter notebook, nor in voila.

I can not really tell if this is me not knowing how to do it or voila missing something.

LATE EDIT:
In case someone is wondering the use case here. When checking data across different documents it voila could be use to provide a small dashboard to allow the user which docs to see in parallel, i.e. side by side, where the user is able to copy and paste text to further paste in a report, email or whatever.

LATE EDIT 2:
Voila version 0.1.20

**Comment by joseberlines** [comment]
Adding some graphical info here.

using HBox with three ipywidgets Ouputs seems to work WITHIN THE NOTEBOOK.
![image](https://user-images.githubusercontent.com/33203439/88304481-9e732480-cd08-11ea-89c4-1b05da62ed04.png)

but when running voila it doesnt.

**Comment by DougRzz** [comment]
Voila prefers the base ipywidgets. Output widgets with Jupyter IFrames don't work.    Convert the pdf (1st page only in example below) to a png and then render the image as a image widget. 

```python
import ipywidgets as widgets
# !pip install pdf2image
from pdf2image import convert_from_path
from io import BytesIO

pages = convert_from_path(r"C:\Users\your\path\sample.pdf", 500)

b = BytesIO()  
pages[0].save(b, format='png')  

imageWidget = widgets.Image(
    value=b.getvalue(),
    format='png',
    width=300,
    height=400,
)

imageWidget  # this should also display in Voila
```

**Comment by joseberlines** [comment]
Ok, I will, but this is a different case scenario. i.e. pdfs visualized within the cell allow you to mark and copy text. I guess this ability goes away when converting to png. But it is definitely an interesting approach worth a try. I will report results here.

**Comment by DougRzz** [comment]
I can't test pdfs on my Jupyter setup.  I can't seem get any pdf to display using your IFrame method. I just get a grey square. I get the same grey square using this HTML widget so it might be work trying this on your computer.
```python
import ipywidgets as widgets
path = "./try.pdf" # relative path
widgets.HTML(value = f'<iframe width="500" height="600"  src={path} type="application/pdf"></iframe> ')
```

**Comment by joseberlines** [comment]
thanks @DougRzz 
I tried it with no success:
![image](https://user-images.githubusercontent.com/33203439/88391177-f61d9880-cdb9-11ea-9188-40c503e3cfb9.png)

**Comment by joseberlines** [comment]
The streamlit version (I consider streamlit the natural alternative) has already implemented iframe:

 https://github.com/streamlit/streamlit/issues/686

Components.iframe

**Comment by jeffyjefflabs** [comment]
You mentioned a 403 Forbidden in your original comment - have you tried changing the [configuration for serving static files](https://voila.readthedocs.io/en/stable/customize.html#serving-static-files)?  I don't think pdfs are allowed by default.

**Comment by joseberlines** [comment]
Hei @jeffyjefflabs I see that in this list:

voila mydir --VoilaConfiguration.file_whitelist="['.*\.(png|jpg|gif|svg|mp4|avi|ogg)']"
there is no pdf.
Could you please provide here also the command or the way to list all this configuration variables of voila? 

before changing anything I would like to see how are the variables.

thx.

**Comment by joseberlines** [comment]
After running 
voila --VoilaConfiguration.file_whitelist="['.*\.(png|jpg|gif|svg|pdf)', 'public.*']"

voila is running in:

http://localhost:8866/voila/tree

but when navigating to a folder containing pdfs those would not appear, i.e. voila does not "see them".

In order to be sure that the pdf's are not in the black list I run:

voila --VoilaConfiguration.file_blacklist="['private.*', '.*\.(ipynb)']"

Voila can not yet open pdfs, nor are they visualized with the code above pasted.

**Comment by maartenbreddels** [comment]
Hi,

debugging this where the problem lies, I found this works:
```
import ipywidgets as widgets
value=r'<iframe width="500" height="600" src="https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf" frameborder="1" allowfullscreen></iframe>'
myhtml =widgets.HTML(
    value=value,
    placeholder='Some HTML',
    description='Some HTML',
)
myhtml
```

So there is no voila/ipywidget issue per se.

If you try:
```
import ipywidgets as widgets
value=r'<iframe width="500" height="600" src="file:///Users/maartenbreddels/src/QuantStack/voila/issue/dummy.pdf" frameborder="1" allowfullscreen></iframe>'
myhtml =widgets.HTML(
    value=value,
    placeholder='Some HTML',
    description='Some HTML',
)
myhtml
```
You'll get a warning, because you try to load a local resource, which you shouldn't do besides for testing purposes maybe.

If you download the pdf, and put it in the same directory, and use:
```
import ipywidgets as widgets
value=r'<iframe width="500" height="600" src="./dummy.pdf" frameborder="1" allowfullscreen></iframe>'
myhtml =widgets.HTML(
    value=value,
    placeholder='Some HTML',
    description='Some HTML',
)
myhtml
```

You will get a 403 (Forbidden).

However, running `$ voila issue/pdf.ipynb --VoilaConfiguration.file_whitelist="['.*.(pdf|png)']"` works.

So I don't think this is a voila issue, but maybe a misunderstand of how things works, and I hope I clarified some of it.

Feel free to reopen if you still think this is a voila issue.

Regards,

Maarten
