### ISSUE TITLE
Support conf.json - listed preprocessors

### ISSUE THREAD

**Issue by SylvainCorlay** [voila-dashboards/voila#665]
We lack support for preprocessors listed in conf.json which were added in nbconvert 6.0.

This is required for the new voila-reveal (for metadata preprocessing).

**Comment by martinRenou** [comment]
Are you talking about this option? https://nbconvert.readthedocs.io/en/latest/config_options.html?highlight=conf#preprocessor-options

**Comment by SylvainCorlay** [comment]
Voilà does not appear to take into account the conf.json file such as:

https://github.com/jupyter/nbconvert/blob/master/share/jupyter/nbconvert/templates/reveal/conf.json
