### ISSUE TITLE
can't embed it into IFrame

### ISSUE THREAD

**Issue by LukaPitamic** [voila-dashboards/voila#672]
Hello, I must say I love voila.

However I bumped into one issue, googled for hours, tried tons of stuff, banged my head against the wall, and still haven't solved it. Does anyone have any idea how to approach embedding voila into IFrame.

I'm getting:
```bash
WARNING:tornado.access:405 POST /api/security/csp-report
```
in the backend, and:

```
Refused to frame 'https://site.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'".
```
on the front-end (browser console)

Jupyter config has option to configure CSP (Content Security Policy), however Voila appears to block it by default, and there is no option to allow it. Or is it??

Any help is highly appreciated.

Anyways, keep on rockin`

L

**Comment by davidbrochart** [comment]
See #609

**Comment by LukaPitamic** [comment]
wow, amazing!!!
thank you so much @davidbrochart
