### ISSUE TITLE
Voila cant be started

### ISSUE THREAD

**Issue by tigon1508** [voila-dashboards/voila#684]
Dear team,
I'm struggling to start voila. I tried many times in 2 weeks, but it never worked for me. I attach some pictures in this email and I hope your team can help me sort this out. 

![image](https://user-images.githubusercontent.com/47066802/91230402-4a30db00-e6e0-11ea-9d8a-4a08324eeb08.png)
![image (1)](https://user-images.githubusercontent.com/47066802/91230444-5b79e780-e6e0-11ea-9e0c-603c8e699f9a.png)

When I click on "click here...", it opens another kernel, but that's it, nothing comes up, even after some hours.
![image (2)](https://user-images.githubusercontent.com/47066802/91230489-74829880-e6e0-11ea-8814-934521641c6f.png)

Please help me to investigate what I'm doing wrong. My python is 3.7.
Thank you and Best Regards!
Chi Tran

**Comment by maartenbreddels** [comment]
Hi,

Did you try a different browser? Do you see an error in the javascript dev console?

Regards,

Maarten

**Comment by maartenbreddels** [comment]
Closing as stable, please reopen if you have more information.

**Comment by tigon1508** [comment]
Hi Maarten,
Sorry for late reply, I tried with Google Chrome, Microsoft Edge, and IE. And I got the same result as the pic I sent you.

**Comment by tigon1508** [comment]
Hi Maarten,
I solved the issue by upgrading jupyter-client.
