### ISSUE TITLE
voila can't show math text in voila

### ISSUE THREAD

**Issue by DohunLee** [voila-dashboards/voila#688]
The last slider can not show math text (in this case x_value2). Jupyter Notebook shows all sliders correctly. Voila does not.

Cell 1:
```
from ipywidgets import interactive, Label, widgets

def output_sv(slidervalue = 5):
    print(slidervalue)
```
Cell 2:
```
interactive_plot=interactive(output_sv, slidervalue=widgets.FloatSlider(
    min=0,
    max=100,
    step=1,
    value = 5,
    description='$x_\mathrm{value1}$ $ $'
))
interactive_plot
```
Cell 3:
```
interactive_plot=interactive(output_sv, slidervalue=widgets.FloatSlider(
    min=0,
    max=100,
    step=1,
    value = 5,
    description='$x_\mathrm{value2}$ $ $'
))
interactive_plot
```

Software:
voila 0.1.21
python 3
Jupyter Notebook 6.0.3

installation of voila in Anaconda Navigator environment:
pip install voila

[TEST.zip](https://github.com/voila-dashboards/voila/files/5156332/TEST.zip)

**Comment by afonit** [comment]
@DohunLee ,
A while ago I reproduced what you saw.
I recently upgraded to voila=0.2.3 and it appears to have resolved the issue you reported.

Could you upgrade to 0.2.3 and see if it resolves your issue?

Here is a screenshot of it working for me:
(on the left is the notebook, on the right is the notebook being served by voila 0.2.3)

![image](https://user-images.githubusercontent.com/1798497/94687408-389fac00-02fa-11eb-8387-b65941961e99.png)

**Comment by DohunLee** [comment]
@afonit 

The updated version did fix the minimal example, but not the full code. I am guessing, that using the description with style and layout causes some unwanted interactions.

Here is a screenshot. 
(on the left is the notebook, on the right is the notebook being served by voila 0.2.3)

![grafik](https://user-images.githubusercontent.com/70583102/95062219-fe207f80-06fc-11eb-8c8e-d1b192cc9c6c.png)

**Comment by afonit** [comment]
I think I copied your updates down correctly, I am not getting the truncated second example that you are seeing:

![image](https://user-images.githubusercontent.com/1798497/95141808-1fef2600-0740-11eb-8dd6-8b6fa00b4915.png)

At the moment - not sure what the difference is.

**Comment by DohunLee** [comment]
@afonit 
The only difference I am seeing is your function names. In my opinion this should make no difference. Maybe you could try giving your functions unequal names and then use the corresponding names when executing the function.

**Comment by afonit** [comment]
Sorry about that - it was rough reading through to see differences from the screenshot, I have now done that and mine looks the same without visual issues:
![image](https://user-images.githubusercontent.com/1798497/95453930-b8042f80-0939-11eb-8134-59344cfbf4d0.png)

I don't have any ideas as to what the difference may be between our environments - maybe create a new conda environment and only install voila and see if you have the same issue - just to remove any environment issues.
