### ISSUE TITLE
Integrating with existing stack - question on suitability

### ISSUE THREAD

**Issue by archienorman11** [voila-dashboards/voila#702]
Hi- firstly, thank you for this project. It looks fantastic. 

I was hoping someone here might be able to help with me with a question around integrating voila into our data science workflow. We tend to build notebooks locally and i'd like to publish the interactive output into our public facing platform. 

Our stack comprises of a number of dockerised services including a go backend and vue frontend. I'm wondering if Voila would be able to run inside a docker container and send interactive cell output directly to a vue container and then render the interactive output (with jinja templates). 

The goal is to embed the notebooks directly into our application with our existing authentication and the ability to customise the notebook output with our design system. 

My feeling is that I might need to run jupyter-server in its own container and extend our golang backend to send/retrieve the notebooks and build our own vue pages to render the output. 

So my question, is Voila designed to run a single notebook / application in its entirety, or could it easily be used as a module in a wider ecosystem? 

Any thoughts useful. 

Best

**Comment by maartenbreddels** [comment]
Hi,

thanks!

> I'm wondering if Voila would be able to run inside a docker container and send interactive cell output directly to a vue container and then render the interactive output (with jinja templates).

What do you mean by vue container?



> My feeling is that I might need to run jupyter-server in its own container and extend our golang backend to send/retrieve the notebooks and build our own vue pages to render the output.

I think so too, you'd run jupyter-server/voila in a container, but I'd access it directly. You could also consider making your own template, that will output the cells output in json form, and render on the frontend.

https://github.com/mariobuikhuizen/voila-embed might also be of interest.

Regards,

Maarten

**Comment by archienorman11** [comment]
by vue container, i meant my vue app running inside its docker container. 

thanks for this, much appreciated.

**Comment by maartenbreddels** [comment]
afaik vue is frontend only, what exactly do you have running in the docker container?
