### ISSUE TITLE
Generating and downloading a file from Voila

### ISSUE THREAD

**Issue by panangam** [voila-dashboards/voila#711]
I have been using this sort of function to generate a file and download it dynamically within a Jupyter notebook

```python
def js_download(text, filename, kind='text/json'):
    # see https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs for details
    content_b64 = b64encode(text.encode()).decode()
    data_url = f'data:{kind};charset=utf-8;base64,{content_b64}'
    js_code = f"""
        var a = document.createElement('a');
        a.setAttribute('download', '{filename}');
        a.setAttribute('href', '{data_url}');
        a.click()
    """
    display(Javascript(js_code))
````

This doesn't seem to work in Voila because arbitrary JS execution is not supported?

I have seen in #578 that it's possible to display a download link using HTML. But is there a way for the download link to be clicked programmatically?

**Comment by agoose77** [comment]
You can display an `HTML` element inside an `Output` widget to do this.

**Comment by panangam** [comment]
@agoose77 Can you give a more concrete example? My understanding is that I can display a download HTML link in a Output widget, but I wouldn't be able to issue a JS command to click and download it programmatically.

**Comment by agoose77** [comment]
Create an output widget, and in your code, use it to display an HTML object containing your example script in script tags

**Comment by agoose77** [comment]
I was on mobile at the time, so I didn't paste a code snippet.

```python
import ipywidgets as widgets
from IPython.display import HTML

out = widgets.Output()
display(out)

...

def create_download_html(file_name: str, url: str) -> HTML:
    return f"""
<script>
 var a = document.createElement('a');
        a.setAttribute('download', '{file_name}');
        a.setAttribute('href', '{url}');
        a.click()
</script>
"""

def example_trigger_download():
    with out:
        display(create_download_html("elgoog", "http://google.com"))
```

**Comment by panangam** [comment]
OH MY GOD THAT ACTUALLY WORKS. Thank you so much! I only had to made a small change, as I had to wrap the output of `create_download_html` as an `HTML` object. For reference, this is what I ended up using.

```python
from ipywidgets import Output, Button
from IPython.display import HTML, clear_output
from base64 import b64encode

download_output = Output()
display(download_output)
def trigger_download(text, filename, kind='text/json'):
    # see https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs for details
    content_b64 = b64encode(text.encode()).decode()
    data_url = f'data:{kind};charset=utf-8;base64,{content_b64}'
    js_code = f"""
        var a = document.createElement('a');
        a.setAttribute('download', '{filename}');
        a.setAttribute('href', '{data_url}');
        a.click()
    """
    with download_output:
        clear_output()
        display(HTML(f'<script>{js_code}</script>'))

btn = Button(description='download some shit')
def download_shit(e=None):
    trigger_download('shit', 'shit.txt', kind='text/plain')
btn.on_click(download_shit)
display(btn)
```

**Comment by panangam** [comment]
Just wanna say, this is still one of my first times actually getting help from an open source community, and you guys rock.

**Comment by agoose77** [comment]
I think we helped each-other; I recently needed this functionality, but completely forgot about the `.click()` method so I had an "export" button that generated a download link for the user. When you posted your snippet I realised I could remove that second step! :rocket:

**Comment by chuckmandu** [comment]
This is fantastic; I just wish I'd found it before spending a day searching and playing!
Incidentally, I came across a fair few StackOverflow and GitHub issues asking how to achieve this outcome within a Jupyter notebook, no Voila; I'll attempt to point those here for a solution. 
Thanks, once again - this made my day!

**Comment by joseberlines** [comment]
Hi, the issue is closed, but it is not clear to me if this is supposed to work under voila or not.
The code is phantastic. It works in Jupyter notebook but NOT WHEN RENDERING WITH VOILA
any ideas?

**Comment by agoose77** [comment]
@joseberlines I haven't tested it on voila recently, but I'm not under the impression that the underlying mechanisms have changed.

The approach taken in these examples is as follows:
1. Encode the file contents
2. Serve the file contents to the frontend (e.g. via an output widget)
3. Run front-end logic to trigger a download

These examples do this by
1. Encoding the file contents into ASCII base64
2. Generating a JS payload to trigger the browser download action for this data
3. Sending the payload to the frontend via an `Output` widget

The output widget is only strictly required on voila, which [does not serve `display()`ed data to the frontend  after notebook execution](https://github.com/voila-dashboards/voila/issues/532)

**Comment by joseberlines** [comment]
when I run the Jupyter notebook it works wonderfully, but when i then render voila and clicked the "download some shit" button I get:
There was an error when executing cell [2]. Please run Voilà with --show_tracebacks=True or --debug to see the error message, or configure VoilaConfigurion.show_tracebacks.

**Comment by joseberlines** [comment]
Perhaps I should open a new issue

**Comment by agoose77** [comment]
The code in https://github.com/voila-dashboards/voila/issues/711#issuecomment-695872958 works for me in voila. You should check the JS console in your browser to see if it has any errors.

**Comment by joseberlines** [comment]
OK, I know my problem now, I am using a Jupyterlab in a hub (not in ma computer)

**Comment by agoose77** [comment]
I don't think that should be the issue. I've used this technique with voila on JupyterHub myself.

**Comment by joseberlines** [comment]
This is the situation:
https://www.youtube.com/watch?v=I2P31HauFA0
1 minute video.

**Comment by chuckmandu** [comment]
I see the same symptom, i.e. nothing downloaded, but only when the execution environment is Jupyter Hub.

The console log shows the following error:

`error: Host is not attached at Function.t.attach (widget.js:913)`

When executing locally both directly from the notebook, and via Volia, everything works beautifully, which leads me to believe the issue is _not_ Voila. I only see this issue when executing using Voila on Jupyter Hub.

**Comment by agoose77** [comment]
@joseberlines can you visit the `/voila` serverextension endpoint and see if that works. I *think* the JupyterLab extension also uses that endpoint, but it's in an iframe.

**Comment by chuckmandu** [comment]
/voila works.

My production JupyterHub proxy configuration grabs /volia requests  and starts a voila instance in debug mode with kernel culling and points to a particular directory for blessed notebooks:

`#configure hub to manage voila requests 
c.ServerProxy.servers = { 'voila':
        { 'command': ['voila', '--enable_nbextensions=True', '--MappingKernelManager.cull_interval=60',
'--MappingKernelManager.cull_idle_timeout=120',
'--no-browser',
'--port', '{port}',
'--base_url', '{base_url}voila/',
'--server_url', '/', '--Voila.notebook_path=', '/srv/voila'],
'launcher_entry': {'enabled': False, 'title':'Goldmine'
              }
          }
      }
}
` 

but no other magic beyond that.

**Comment by chuckmandu** [comment]
I've verified that the standalone code snippet presented as the topic of this thread work flawlessly in my production Jupyter Hub environment with the proxy Volia configuration as detailed directly above. The cause of [this error](https://github.com/voila-dashboards/voila/issues/711#issuecomment-796951557) is elsewhere in my application code.

**Comment by jtpio** [comment]
Also if it's in the JupyterLab preview only, maybe this change is relevant: https://github.com/voila-dashboards/voila/pull/834

(hasn't been published yet)

**Comment by agoose77** [comment]
That will be the fix, excellent. Thanks @jtpio !
