### ISSUE TITLE
displays empty rows for cells with no output

### ISSUE THREAD

**Issue by mehdielamrani** [voila-dashboards/voila#713]
Hi,
In voila 0.2.2 an empty row is displayed even if the notebook cell has no output which was not the case in 0.1.21 version. For long notebooks a large space is displayed above the app.
Thanks

**Comment by SylvainCorlay** [comment]
Thanks @mehdielamrani. This is fixed in #718. Voilà 0.2.3 should include that change and be released shortly (today or tomorrow).
