### ISSUE TITLE
Voila page open but remains blank

### ISSUE THREAD

**Issue by iadjali** [voila-dashboards/voila#717]
When I launch Voila whether from the command line or within the Jupyter notebook the Voila page opens but remains blank.
I tried with different notebooks but no luck. 
Below is the error message I get. Appreciate any help with this.
![2020-09-23_20h43_12](https://user-images.githubusercontent.com/51908456/94063224-b0904280-fddf-11ea-82f5-6e96e02d473b.png)

**Comment by SylvainCorlay** [comment]
Thanks for reporting! This was an issue with Tornado 6.0 that was just released.

I just pushed out Voilà 0.2.3 which should work with tornado 6. You can also downgrade tornado to an earlier version.

Closing!

**Comment by iadjali** [comment]
Great! Will update to 0.23.
Thanks, Sylvain!
