### ISSUE TITLE
Running cells with `display(Javascript(...))` using voila fails with ReferenceError on Javascript side

### ISSUE THREAD

**Issue by igozali** [voila-dashboards/voila#727]
I have a cell in my Jupyter notebook that look like this so that I can grab the URL query parameters from the address bar and feed it into the IPython kernel.

```python
from IPython.display import display, Javascript
display(Javascript("""
    const params = new URLSearchParams(window.location.search);
    const myparams = params.get("myparams");
    console.log(`myParams: ${myparams}`)
    IPython.notebook.kernel.execute(`myparams = '${myparams}'`);
"""))
```

When I try to run the notebook via voila using the following command:
```
voila --no-browser --template=lab --Voila.ip=0.0.0.0 --port 57384 --enable_nbextensions=True --VoilaConfiguration.file_whitelist="['.*']" --debug my_notebook.ipynb
```

I can't seem to get this cell to work, and would see this error in the Firefox dev console (on the Javascript side):
```
Uncaught ReferenceError: IPython is not defined
```

Is it possible to access the IPython global in this manner when using voila? Thank you!

Similar to https://github.com/voila-dashboards/voila/issues/354

**Comment by igozali** [comment]
This pull request happens to solve my specific use case: https://github.com/voila-dashboards/voila/pull/414, but leaving this issue open in case there's interest in accessing the `IPython` variable from Javascript. Otherwise, please feel free to close :)

**Comment by maartenbreddels** [comment]
Hi,

great to find you solved your problem. Note that IPython is only available from the Jupyter notebook, not from voila or Jupyter Lab.

cheers,

MAarten
