### ISSUE TITLE
ipympl.ipynb doesn't work on Safari/Firefox

### ISSUE THREAD

**Issue by abunimeh** [voila-dashboards/voila#729]
I am running on macos 10.15.

steps to reproduce

```
git clone ...
conda env update -f environment.yml
cd notebooks/
voila ipympl.ipynb
```
The notebooks renders correctly on Chrome Version 85.0.4183.121
It doesn't work on Safari v14/Firefox v81.0.

Screenshots attached
<img width="1682" alt="image" src="https://user-images.githubusercontent.com/8106823/94356644-ab343180-0045-11eb-94b6-5498b2648379.png">
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/8106823/94356661-c8690000-0045-11eb-98d0-c1c15e571a3f.png">
<img width="1258" alt="image" src="https://user-images.githubusercontent.com/8106823/94356682-ee8ea000-0045-11eb-9515-a8f18efe79a2.png">

**Comment by martinRenou** [comment]
@abunimeh Do you think it's the same issue an in here: https://github.com/voila-dashboards/voila/issues/693? Can you look at the JavaScript console and confirm you see the following error message:
`Uncaught (in promise) DOMException: The object could not be cloned.`

**Comment by abunimeh** [comment]
yes it seems to be the same error reported in that ticket.

Safari spits out:
```
[Error] Unhandled Promise Rejection: DataCloneError: The object can not be cloned.
postMessage (localhost:30)
(anonymous function) (localhost:30)
(anonymous function) (voila.js:137:111880)
promiseReactionJob
```
Firefox:
```
Uncaught (in promise) DOMException: The object could not be cloned. localhost:8866:30
```

**Comment by martinRenou** [comment]
Thanks, this should be fixed on master. It will be included in the next release. Thanks for reporting.
