### ISSUE TITLE
When using `--enable_nbextensions=True`, getting lots of 403 errors on `base/js/*.js` files

### ISSUE THREAD

**Issue by igozali** [voila-dashboards/voila#733]
When starting with a fresh virtualenv with only these packages:
```bash
python3 -m venv venv
source venv/bin/activate
pip install jupyter jupytext voila ipyaggrid
```

And I try to serve an empty notebook with voila using the following command:
```bash
voila --no-browser --port 32674 --enable_nbextensions=True Untitled.ipynb
```

I get errors like the following (on the browser dev console, Firefox):
```
Loading failed for the <script> with source “http://localhost:32674/voila/jquery.js”. localhost:32674:1:1
Uncaught Error: Script error for "jquery", needed by: /voila/nbextensions/jupytext/index.js
http://requirejs.org/docs/errors.html#scripterror
    makeError http://localhost:32674/voila/static/require.min.js:1
    onScriptError http://localhost:32674/voila/static/require.min.js:1
    load http://localhost:32674/voila/static/require.min.js:1
    ...lots more lines...
    requirejs http://localhost:32674/voila/static/require.min.js:1
    <anonymous> http://localhost:32674/:264
require.min.js:1:1067

Loading failed for the <script> with source “http://localhost:32674/voila/base/js/dialog.js”. localhost:32674:1:1
Uncaught Error: Script error for "base/js/dialog", needed by: /voila/nbextensions/jupytext/index.js
http://requirejs.org/docs/errors.html#scripterror
    makeError http://localhost:32674/voila/static/require.min.js:1
    onScriptError http://localhost:32674/voila/static/require.min.js:1
    load http://localhost:32674/voila/static/require.min.js:1
    ...lots more lines...
require.min.js:1:1067
```

Seems like some extensions need `jquery` and `base/js/*.js` files to be loadable via RequireJS?

I'm on `voila 0.2.3` and `python 3.8.5`. Please let me know if more info is needed to triage this issue. I'd be happy to contribute if this is a legitimate issue as well!

**Comment by igozali** [comment]
Additionally, if I add the `--VoilaConfiguration.file_whitelist="['.*']"` option (full command below):
```
voila --no-browser --port 32674 --enable_nbextensions=True --VoilaConfiguration.file_whitelist="['.*']" Untitled.ipynb
```

I now get 404 errors on the backend side:
```
WARNING:tornado.access:404 GET /voila/files/voila/jquery.js (::1) 1.07ms
WARNING:tornado.access:404 GET /voila/files/voila/base/js/namespace.js (::1) 1.56ms
WARNING:tornado.access:404 GET /voila/files/voila/base/js/dialog.js (::1) 0.61ms
WARNING:tornado.access:404 GET /voila/files/voila/base/js/events.js (::1) 1.42ms
WARNING:tornado.access:404 GET /voila/files/voila/base/js/utils.js (::1) 0.98ms
WARNING:tornado.access:404 GET /voila/files/favicon.ico (::1) 0.66ms
```

**Comment by igozali** [comment]
Linking #727 since the `IPython`/`Jupyter` variable is accessible from the `base/js/namespace.js` static file, which seems to be part of the Python [notebook](https://pypi.org/project/notebook/) module?

**Comment by maartenbreddels** [comment]
That is because voila cannot see the difference between extensions that are for jupyter-widgets, and jupyter notebook specific extensions (which will not, and cannot be supported). So these extensions assume a Notebook environment, where these modules are defined (or available), but they are not. The 404's are ok, they just aren't there, and even if they were there they wouldn't work. Best approach is not to install extensions in the Python environment that are notebook specific.

**Comment by GaGaMan1101** [comment]
@maartenbreddels  hi, thanks for the above comments. Sorry I am not very clear about the solution, 0.2 doesn't work for me 

keep getting the below errors
WARNING:tornado.access:404 GET /voila/@finos/perspective-jupyterlab.js (::1) 0.26ms
WARNING:tornado.access:404 GET /voila/@finos/perspective.js (::1) 1.07ms
WARNING:tornado.access:404 GET /voila/@finos/perspective-viewer.js (::1) 0.87ms
WARNING:tornado.access:404 GET /voila/@finos/perspective-viewer-datagrid.js (::1) 1.30ms
WARNING:tornado.access:404 GET /voila/@finos/perspective-viewer-d3fc.js (::1) 1.39ms
WARNING:tornado.access:404 GET /voila/@finos/perspective/dist/esm/api/client.js (::1) 1.51ms
WARNING:tornado.access:404 GET /voila/@lumino/widgets.js (::1) 1.54ms
