### ISSUE TITLE
Classic template bug

### ISSUE THREAD

**Issue by dcnadler** [voila-dashboards/voila#734]
I get the following error when running a notebook in voila with the "classic" template when in directory mode (does not occur for single-notebook mode)
`WARNING:tornado.general:404 GET /voila/render/voila/static/require.min.js (172.20.0.1): No such file or directory: voila/static/require.min.js`

I can get rid of it if I pass the arguments `resources.base_url` and `resources.nbextensions` to `voila_setup`, following the pattern in the 'lab' template.
Line to modify:
https://github.com/voila-dashboards/voila/blob/b003a7fc62023e5b4c8dab7dd64b94a920610c15/share/jupyter/voila/templates/classic/index.html.j2#L46

I didn't look too much into the purposes of the different templates, but this seems like a bug

**Comment by maartenbreddels** [comment]
Thanks for the report, this should be fixed in #741, and is covered by a test.
