### ISSUE TITLE
State management not consistent between jupyter and voila

### ISSUE THREAD

**Issue by erikgaas** [voila-dashboards/voila#736]
I have an issue where I'm dynamically creating custom widget classes within other widgets. For instance I have a small form and I add another identical form when a specific button is clicked. Once the user has entered in their desired number of sub-forms, a submit button aggregates this data and processes it.

In jupyter this works fine. I just look into a parent_widget.children and extract all the data from the underlying widgets.

This fails as soon as I convert this into a voila dashboard. I'm not sure why this is I can try to sketch out a reduced example, but I was wondering if this was a known issue. I think I would be able to overcome this if I had a better idea of what is happening with state with respect to parent and child widgets. But for now I'm pretty baffled as how to make it work.

**Comment by maartenbreddels** [comment]
What do you mean by 'fail'? Apart from `display(...)` without an Output widget context, everything should work the same (unless you are using notebook or lab-specific JS APIs)

**Comment by erikgaas** [comment]
I was able to solve this! Turns out having material theme with custom theming led to problems with widget registration.
