### ISSUE TITLE
New release with PR #730 and #731? 

### ISSUE THREAD

**Issue by paugier** [voila-dashboards/voila#737]
With recent versions of Voilà (> 0.1.21), ipympl figures are not shown for users using Firefox or Safari (see #693 and #729). The web browsers used by people is not something that one can control so all voilà applications using ipympl are broken for some users.

This was fixed with PR #730 and #731. (Thanks @maartenbreddels!)

However, since `pip install git+https://github.com/voila-dashboards/voila.git#egg=voila` does not seem to work (or maybe is very very very slow), I don't see how we can use these fixes for applications hosted on Binder or Heroku.

Moreover, it seems that there is a bug with Voila 0.1.21 and Heroku, so it is not possible to have voila apps using ipympl hosted on Heroku that work for users using Firefox or Safari.

All that to say that a release including #730 and #731 would be very useful :slightly_smiling_face:

**Comment by pelson** [comment]
This would be indeed useful. In in the prototype phase and was caught out by the linked bugs and am currently shipping a built sdist from master in my project to install on openshift (same approach would be possible with heroku).

**Comment by pelson** [comment]
P.S. It was my first time using voila yesterday, and it is really quite awesome! Great job all! :+1:

**Comment by maartenbreddels** [comment]
I agree we should have a new release, I'll probably get to it next week! (if someone else doesn't get to it first)

**Comment by pelson** [comment]
Thanks for doing this! https://pypi.org/project/voila/0.2.4/ :tada:

**Comment by maartenbreddels** [comment]
Hah, you are quick to notice :). Thanks!

**Comment by pelson** [comment]
Using it already in prod :joy:
