### ISSUE TITLE
Sidebar or Navigation options

### ISSUE THREAD

**Issue by DohunLee** [voila-dashboards/voila#738]
Is there a possibility to have a functioning sidebar in your application when streaming your noteebook with voila? 
If not are there any other options to ease navigation on long pages?

Voila is amazing, yet it seems not to fit for such applications.

**Comment by maartenbreddels** [comment]
Did you have this in mind?:
https://github.com/maartenbreddels/voila-demo
![img](https://user-images.githubusercontent.com/1765949/61897777-1bae6280-af18-11e9-8fd0-7243510f2e1e.gif)

**Comment by DohunLee** [comment]
@maartenbreddels 

Thank you. Yes this is what I was thinking of. Are the docs enough to get this working?
