### ISSUE TITLE
Execution timeout change

### ISSUE THREAD

**Issue by jeffyjefflabs** [voila-dashboards/voila#742]
I just noticed the default cell execution timeout changed from 30s in 0.1 to None in 0.2.  I realize this is inherited from upstream (https://github.com/jupyter/nbconvert/issues/791) and that I can set a timeout myself, but I thought it might be worth mentioning here.  From a UX perspective, at some point the user will get tired of watching the "Executing" spinner and wonder if something is wrong.  So, does it make sense for Voila to set its own default?  If no, that's fine (as discussed in the nbconvert thread, the "right" number might be different for everyone), but maybe it's worth calling attention to the configuration setting in the docs.

**Comment by jtpio** [comment]
Thanks @jeffyjefflabs.

Do you think this should be in the user documentation? There could be a small section to cover this.

If so, would you like to open a PR? Thanks!

**Comment by jeffyjefflabs** [comment]
Sure - I opened #797.  It seemed to fit best on the "Customizing Voila" page, but feel free to move it elsewhere.
