### ISSUE TITLE
Injecting Javascript when rendering notebooks with voila (disabled?)

### ISSUE THREAD

**Issue by joseberlines** [voila-dashboards/voila#743]
I am developing an app to be served rendering with voila from jupyter hub.
I am interested in copying text into the clipboard of the user after clicking a ipywidget button.

We are trying to solve this problem by "injecting" Javascript into the code as follows:

```
import ipywidgets as widgets
from IPython.display import display, HTML, Javascript
mybtn = widgets.Button(description='copy to clipboard',button_style='success')
output = widgets.Output()
display(mybtn, output)
def mybtn_event_handler(b):
    with output:
        display(Javascript('''
        var copyText = document.getElementById("myInput");
        copyText.select();
        copyText.setSelectionRange(0, 99999); /*For mobile devices*/
        document.execCommand("copy");
        alert("Copied the text: " + copyText.value);
        ''')) 
mybtn.on_click(mybtn_event_handler)
display(HTML('<input type="text" value="Hello World" id="myInput">'))
```

First we try to get some text into the console to see if we can manage it, and afterwards we would try to find a way to using JS to pass the content of the variable into the clipboard of the user.

The result is nevertheless the following:
![image](https://user-images.githubusercontent.com/33203439/118473057-dde08680-b709-11eb-90e9-34108368470f.png)

It seems that when Rendering with voila Javascript can not be used because it is disabled.
Is that right? Is there any way around this? 

NOTE for completeness. 
The code works in Jupyter Lab when simple run without rendering (Despite of this the error displayed when rendering with voila is "Javascript is disabled in Jupyter lab". (note: be aware that the code of the following screenshot is slightly different but the essence of it is the same. JS will not be injected from voila.)
![image](https://user-images.githubusercontent.com/33203439/96724318-faa11f80-13af-11eb-804a-98bf151660ad.png)

**Comment by jtpio** [comment]
Maybe the cleanest in the long term couple be to have a custom clipboard widget, so that it could be combined with other widgets and used entirely from Python?

**Comment by joseberlines** [comment]
We developed clipboard widget using  ipyvuetify template. But indeed a widget to pass whatever text content to the clipboard would be cool. So it would be contained in the widgets ecosystem and it will not be neccesary to resort to JS.

**Comment by guimillet** [comment]
@jtpio Is there a reason for disabling Javascript code execution in an Output widget but enabling it in a cell execution (in Voilà)?

I saw a comment from @SylvainCorlay in issue [108](https://github.com/voila-dashboards/voila/issues/108#issuecomment-506035099) "We indeed disallow arbitrary javascript injection in JupyterLab and this is very unlikely to be supported." in June 2019. Eventually, it now seems to be supported in JupyterLab (as a cell execution as well as in an Output widget) and in a cell in Voilà. Has there been security restrictions implemented to support those cases?

**Comment by 12rambau** [comment]
I want ot perform the same trick as @guimillet and @joseberlines with Ipywidget, following their advices I created a ipyvuetify class that should display text in an alert (it will then be replaced by a copy-to-clipboard func): 

```python 
import ipyvuetify as v 
import ipywidgets as w 
from IPython.display import Javascript

class Clip(v.TextField):
    """
    Custom textField that provide a handy copy to clipboard javascript behaviour. 
    When the clipboard btn is clicked the v_model will be copied in the local browser clipboard
    """
    output = w.Output()
    
    def __init__(self, **kwargs):
        
        self.class_ = "ma-5"
        self.placeholder = ms.clip.placeholder
        self.outlined = True
        self.label = ms.clip.label
        self.readonly = True
        self.append_icon = "mdi-clipboard-outline"
        self.v_model = None
        
        super().__init__(**kwargs)
        
        # js behaviour
        self.on_event('click:append', self._copy_to_clipboard)
    
    @output.capture()
    def _copy_to_clipboard(self, widget, event, data):
        """copy the content of the textfield in the clipboard"""
        
        js =  f"alert('{self.v_model}');"
        display(Javascript(js))
        
        return self
    
    def _ipython_display_(self):
        display(super(),self.output)
```

This work rxactly as expected in Jupyter Notebook and JupyterLab. when I want to execute it in a voila dashboard I get the following error : 

> JavaScript output is disabled in JupyterLab

and the script is not executed. Any chance that this behaviour will change in the future ?

**Comment by gunstonej** [comment]
I'm having exactly the same issue as @12rambau. 

I'd also be interested to know if anyone has a hacky short-term fix to this? 

As a user, the fact it works fine in JupyterLab leads one to expect it will continue to work in Voila...

**Comment by gunstonej** [comment]
to give a simple example, the code below opens the link from JupyterLab, but doesn't from Voila: 

```python

import ipywidgets as widgets
from IPython.display import display, Markdown, clear_output, Javascript

def javascript_open_url(url):
    """uses Javascript in the browser to open a new tab with URL
    
    Code:
        return Javascript('window.open("{url}");'.format(url=url))
    """
    return Javascript('window.open("{url}");'.format(url=url))

def fn_open(click):
    with out:
        clear_output()
        display(Markdown('works in JupyterLab - doesnt work in Voila'))
        display(javascript_open_url(url))
    
url = 'https://jupyter.org/'
out = widgets.Output()
button_open = widgets.Button(icon='fa-link', button_style='success')
button_open.on_click(fn_open)
display(button_open)
display(out)

```

error in Voila:

![image](https://user-images.githubusercontent.com/21370980/123793493-a99be080-d8d9-11eb-82c0-901c890a582f.png)

**Comment by josselex** [comment]
I have the same issue. My Javascript works in Jupyterlab but not voila.

**Comment by joseberlines** [comment]
I am wondering if this situation applyes to any js "injection" (sorry for the bad connotations of this word) not only related to voila, not just in attempting to display things to the user.

**Comment by trungleduc** [comment]
https://github.com/voila-dashboards/voila/pull/931 merged, we can close this issue?

**Comment by jtpio** [comment]
Closing as fixed by #931 and released in `0.2.11`.

Thanks @trungleduc!

https://user-images.githubusercontent.com/591645/131818555-a58cb710-1f9d-42f3-ad61-bdae56722eae.mp4

**Comment by marscher** [comment]
never mind. My pop up blocker was very silent about blocking these calls :+1: sorry for the noise

**Comment by gioxc88** [comment]
Hello,
this doesn't work if you put the widget in a container like `w.HBox`
