### ISSUE TITLE
Altair charts do not render in Safari with any Voila 0.2 version

### ISSUE THREAD

**Issue by parodayco** [voila-dashboards/voila#748]
Voila 0.1.23 renders all my Altair charts in the current versions of all browsers (Chrome, Firefox, Safari) but Voila 0.2+ (including 0.2.4) is inconsistent. Altair renders fine without Voila: Jupyter notebooks, Jupyterhub, and HTML files generated with nbconvert. 

Voila 0.2+ won't render Altair charts locally in Safari and it won't render them in my new Jupyterhub on an Ubuntu VPS in either Safari or Firefox. When they render locally in Firefox, I see the new loading animation, but nothing in Safari. There, it renders like 0.1+ does except the final result only includes markdown and pandas table cells. In Jupyterhub, both browsers render only markdown and pandas table cells.

When I downgrade to Voila 0.1.23 in both environments, my Altair charts render fine in all browsers. 

I'm using the latest versions of Mac OS, Firefox, Safari, Chrome, conda, pip, altair, etc. Conda built my voila-test env with python 3.7.9. The VPS is running Ubuntu 18.04 and The Littlest Jupyterhub built with python 3.7.4 in the user env. 

I saw the recently closed ticket #722 but I've had no success getting Altair charts to render with the current Voila and the terminal shows no errors. Any ideas?

**Comment by afonit** [comment]
Hello @parodayco , I am the person from the ticket you mentioned.  Based on Sylvain Corlay's comment Tornado - after I had upgraded Voila, I then manually upgraded my tornado to 6.0.4.

That seemed to solve 99% of my issues.  There are still edge cases that I can't account for - don't have evidence for.

I would suggest making sure your tornado is at least 6.0.4(?).

**Comment by parodayco** [comment]
Hi @afonit, my env has Tornado 6.1 with Altair 4.1.0 and Voila 0.2.4. Voila now renders Altair charts in Firefox and Chrome but not Safari. Two out of three isn't bad but the old Voila 0.1.x rendered Altair in all of them. I know Altair is a bit out of date, so thinking about trying another data viz package or perhaps the Vega-lite that Altair is built on. Thanks so much for your feedback, though. I appreciate it.
