### ISSUE TITLE
Graphs created using plotly are no longer displayed

### ISSUE THREAD

**Issue by jgbrainstorm** [voila-dashboards/voila#749]
Just recently, I noticed the plotly graphs in my dashboard using voila are not displaying anymore. Graphs using other tools are still working. I tried a few days but still not able to get it work. Here is the notebook I referred to:

https://github.com/jgbrainstorm/covid19_insight

It works well 2 months ago but suddenly the graphs do not display. Any ideas what is going wrong? Thanks.

**Comment by jeffyjefflabs** [comment]
There's some recent discussion in #619 - Plotly doesn't seem to work consistently with Voila 0.2.  As a workaround, wrapping plots in the [FigureWidget](https://plotly.com/python/figurewidget/) works in some cases.

**Comment by shrinathkeni** [comment]
I am facing the same issue.. please provide a solution for the same

**Comment by maartenbreddels** [comment]
Fixed in #735 should be in the next release.
