### ISSUE TITLE
When running as a server extension, no ability to display python errors with --debug

### ISSUE THREAD

**Issue by aschlaep** [voila-dashboards/voila#751]
We have Voila running as a server extension.  When there is a python error, Voila displays "There was an error when executing cell [X].  Please run Voilà with --debug to see the error message."  We can customize this message with `cell_error_instruction`, but we can not show the python stack.  It seems that there is no way to run with the --debug flag when running as a sever extension, rather than running it directly.

**Comment by aschlaep** [comment]
Entered per @maartenbreddels request.

**Comment by jeffyjefflabs** [comment]
You can set `c.Voila.show_tracebacks = True` in jupyter_notebook_config.py, unless you're trying to avoid restarting?
