### ISSUE TITLE
Sort notebooks within a folder alphabetically

### ISSUE THREAD

**Issue by giswqs** [voila-dashboards/voila#757]
When using voida to render notebooks within a folder, is it possible to sort the notebooks alphabetically? See below. The notebooks are not in alphabetical order. 
```
voila notebooks/
```

![](https://i.imgur.com/Z7xBgBB.png)

**Comment by jtpio** [comment]
Thanks @giswqs.

One way could be to implement the sorting in the tree handler: https://github.com/voila-dashboards/voila/blob/4d72fb2493d4c19ab85c0fe652a5d6be605bef7f/voila/treehandler.py#L50

Or as an alternative implement the sorting in the template (or in a custom template): 

https://github.com/voila-dashboards/voila/blob/4d72fb2493d4c19ab85c0fe652a5d6be605bef7f/share/jupyter/voila/templates/base/tree.html#L64

**Comment by giswqs** [comment]
@jtpio It would be nice to have this sorting feature built-in and enabled by default.

**Comment by jtpio** [comment]
@giswqs would you like to give a try and open a PR?

**Comment by giswqs** [comment]
@jtpio Thank you for your advice! I just submitted a PR https://github.com/voila-dashboards/voila/pull/791#partial-pull-merging to resolve this.
