### ISSUE TITLE
Question: Does it support ag-grid or ipyaggrid in lab

### ISSUE THREAD

**Issue by yinhua2018** [voila-dashboards/voila#760]
Does it support ag-grid or ipyaggrid in lab?
Thank you.

**Comment by maartenbreddels** [comment]
Hi,

did you try? I think there should not be a reason it would not.

Regards,

Maarten

**Comment by gunstonej** [comment]
i can confirm voila does support ipyaggrid in lab

see here:

https://gitlab.com/DGothrek/ipyaggrid/-/issues/37

**Comment by jtpio** [comment]
Closing as answered, thanks all!

**Comment by ankostis** [comment]
Confirm that `ipyaggrid` also works fine.
