### ISSUE TITLE
Voila in closed network

### ISSUE THREAD

**Issue by mpeschina** [voila-dashboards/voila#765]
Hi, 

I have problems running Voila in a closed network. 

I installed according to the guide within a fresh python 3.7 environment. Starting voila itself and then a notebook takes about 5 minutes. After this time, the notebook runs as expected. 

During this long startup, the browser displays for about 1-2 min "Read localhost". Then for about 1 min "Connecting to unpkg.com ..." and for another minute connecting to some cdnXXX.cloudflare.com.

I also tried the option voila --enable_nbextensions=True

Is it possible that voila tries to reach some external content in the internet and the startup time results in waiting for the different resources? Can I deactivate this?

Best regards, 
Markus

**Comment by mpeschina** [comment]
-- It got resolved after updating the complete installation to the newest version. Thanks for the great package and sorry for the comment.

**Comment by martinRenou** [comment]
> I also tried the option voila --enable_nbextensions=True

Yes, this option will be very important in a closed network if you use *e.g.* interactive widgets
