### ISSUE TITLE
Call a python function from an HTML widget

### ISSUE THREAD

**Issue by pabloppp** [voila-dashboards/voila#772]
I have created an HTML widget with multiple elements, I want to be able to call a python function from the onclick event  of one of them using javascript. If I run the widgets from the jupyter I am able to do something like
```
onclick="IPython.notebook.kernel.execute(`my_function({some_parameter})`)"
```
That way I can programmatically create the HTML elements and make them call a python function with whatever parameter I need, but when running this with Voila I get the error `IPython is not defined`

Is there a way to call a function defined in python from javascript in Voila? 

Thank you!

**Comment by jtpio** [comment]
Thanks @pabloppp.

Yes `IPython` is not available in Voila. Also Voila disables execute requests from the browser so even if `IPython` was available the request would not be allowed by the Voila server.

An alternative would be to use widget events to register callbacks: https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20Events.html

Would that work in your case?

**Comment by pabloppp** [comment]
Unfortunately, I need to be able to detect click events on custom HTML elements. Specifically, it is a grid of images, and I need to be able to select one of them and detect when it's clicked. I don't know if there is a way to do this using widgets events, but doesn't seem like it :/ 
Anyways, thank you 🙇

**Comment by jtpio** [comment]
Ah ok. It sounds like it should be possible with ipywidgets, but would require wrapping the images.

And maybe use something like `ipyevents`: https://github.com/mwcraig/ipyevents

**Comment by pabloppp** [comment]
Thanks, will take a look!

**Comment by jtpio** [comment]
OK great!

Closing as answered, but don't hesitate if you have other questions.
