### ISSUE TITLE
[Documentation] Configuration field for running Voila with Binder is misleading

### ISSUE THREAD

**Issue by thomas-bc** [voila-dashboards/voila#776]
## What
In [the documentation on how to configure Binder to run Voila](https://voila.readthedocs.io/en/stable/deploy.html#deployment-on-binder), step number 4 says 
> In Path to a notebook file, select URL and use the Voilà endpoint: /voila/render/path/to/notebook.ipynb \

I think the endpoint should be `voila/render/path/to/notebook.ipynb` (no leading`/`)

## Why
Both the current format and the one I'm mentioning work fine when specifying a tree (`/voila/tree/path/to/folder`). But the current format fails when specifying a notebook file (`/voila/render/path/to/notebook.ipynb`), where the one I'm mentioning does not.\
I'm not certain, but I think this is an issue on the Binder side.

It is also the format used in the [README](https://github.com/voila-dashboards/voila#) Binder button of this very repo. You can notice that on the URL the Binder button points to (https://mybinder.org/v2/gh/voila-dashboards/voila/stable?urlpath=voila%2Ftree%2Fnotebooks) as `voila%2Ftree%2Fnotebooks` has no leading `%2F`.

## How to reproduce
I have tested that with a repo of mine and made the 2 options available with a Binder button on each: https://github.com/thomas-bc/voila-examples
The former cause the redirection to lead to `<binder_url>/tree/voila/tree` which fails with a 404 Not Found. The latter leads to `<binder_url>/voila/tree`, which works as expected. 

If this is a something you want to go forward with, I can make a PR.

**Comment by jtpio** [comment]
Thanks @thomas-bc.

Would you like to open a PR to fix this in the documentation?
