### ISSUE TITLE
Jupyter notebook stops working when using voila

### ISSUE THREAD

**Issue by devanirudh98** [voila-dashboards/voila#782]
I used Voila with my jupyter notebook and deployed it on Heroku.

I used `--theme=dark --template=material`. However, after running for a few seconds, the notebook stopped working.

So I removed `--template=material` and went ahead with only `--theme=dark` and it works as it should (I used `--enable_nbextensions=True` in both of them). It seems to be an issue with the particular template.

I got these errors:

```
WARNING:tornado.general:403 GET /voila/files/favicon.ico
WARNING:tornado.access:403 GET /voila/files/favicon.ico
[Voila] WARNING | WebSocket ping timeout after 90001 ms
[IPKernelApp] WARNING | No such comm: 829cb632d6504ceb218089a385
```

**Note:** The results were the same even when I ran the notebook locally using cmd, so it's probably not a Heroku problem.

Thanks in advance!

**Comment by jtpio** [comment]
Thanks @devanirudh98.

> It seems to be an issue with the particular template.

Does this happen only with the `material` template? Were you able to try with other templates?

If that's the case we could move the issue to https://github.com/voila-dashboards/voila-material and investigate there.

**Comment by devanirudh98** [comment]
Thanks for replying @jtpio.

I tried other templates too and it didn't work in any of them. It only works when I run it without a template.
I have used interdependent drop-down widgets in the links below:

**Without Template:** https://iplani.herokuapp.com

**With Template:** https://ipltest.herokuapp.com

However, I noticed that if I used each of these drop-down widgets separately, it runs fine even when I use a template.

Here's the entire log until it stops working when a template is used:

`[Voila] Voilà is running at:
http://localhost:8866/
[Voila] Kernel started: e70afd15-48ea-423c-a0bd-179baee98864
WARNING:tornado.general:403 GET /voila/files/favicon.ico (::1): File not whitelisted
WARNING:tornado.access:403 GET /voila/files/favicon.ico (::1) 1.00ms
WARNING:tornado.general:403 GET /voila/files/voila/jquery.js (::1): File not whitelisted
WARNING:tornado.access:403 GET /voila/files/voila/jquery.js (::1) 2.00ms
WARNING:tornado.general:403 GET /voila/files/voila/base/js/namespace.js (::1): File not whitelisted
WARNING:tornado.access:403 GET /voila/files/voila/base/js/namespace.js (::1) 1.00ms
WARNING:tornado.general:403 GET /voila/files/voila/base/js/dialog.js (::1): File not whitelisted
WARNING:tornado.access:403 GET /voila/files/voila/base/js/dialog.js (::1) 1.00ms
WARNING:tornado.general:403 GET /voila/files/voila/base/js/events.js (::1): File not whitelisted
WARNING:tornado.access:403 GET /voila/files/voila/base/js/events.js (::1) 1.00ms
WARNING:tornado.general:403 GET /voila/files/voila/base/js/utils.js (::1): File not whitelisted
WARNING:tornado.access:403 GET /voila/files/voila/base/js/utils.js (::1) 1.00ms
[IPKernelApp] WARNING | No such comm: 6bdd03d84cb941ffaa1c454bf7537483
[IPKernelApp] WARNING | No such comm: ff19486f21a9405da10495072e124b7e`

It looks like an issue with interdependent widgets but why does it only occur when I use a template and run fine otherwise?

Thanks again!

**Comment by devanirudh98** [comment]
Thanks for replying @jtpio.

I tried other templates too and it didn't work in any of them. It only works when I run it without a template.
I have used interdependent drop-down widgets in the links below:

**Without Template:** https://iplani.herokuapp.com

**With Template:** https://ipltest.herokuapp.com

However, I noticed that if I used each of these drop-down widgets separately, it runs fine even when I use a template.

Here's the entire log until it stops working when a template is used:

```
[Voila] Voilà is running at:
http://localhost:8866/
[Voila] Kernel started: e70afd15-48ea-423c-a0bd-179baee98864
WARNING:tornado.general:403 GET /voila/files/favicon.ico (::1): File not whitelisted
WARNING:tornado.access:403 GET /voila/files/favicon.ico (::1) 1.00ms
WARNING:tornado.general:403 GET /voila/files/voila/jquery.js (::1): File not whitelisted
WARNING:tornado.access:403 GET /voila/files/voila/jquery.js (::1) 2.00ms
WARNING:tornado.general:403 GET /voila/files/voila/base/js/namespace.js (::1): File not whitelisted
WARNING:tornado.access:403 GET /voila/files/voila/base/js/namespace.js (::1) 1.00ms
WARNING:tornado.general:403 GET /voila/files/voila/base/js/dialog.js (::1): File not whitelisted
WARNING:tornado.access:403 GET /voila/files/voila/base/js/dialog.js (::1) 1.00ms
WARNING:tornado.general:403 GET /voila/files/voila/base/js/events.js (::1): File not whitelisted
WARNING:tornado.access:403 GET /voila/files/voila/base/js/events.js (::1) 1.00ms
WARNING:tornado.general:403 GET /voila/files/voila/base/js/utils.js (::1): File not whitelisted
WARNING:tornado.access:403 GET /voila/files/voila/base/js/utils.js (::1) 1.00ms
[IPKernelApp] WARNING | No such comm: 6bdd03d84cb941ffaa1c454bf7537483
[IPKernelApp] WARNING | No such comm: ff19486f21a9405da10495072e124b7e
```


It looks like an issue with interdependent widgets but why does it only occur when I use a template and run fine otherwise?

Thanks again!
