### ISSUE TITLE
classic Template doesn't feature dark theme 

### ISSUE THREAD

**Issue by YousefSaber** [voila-dashboards/voila#823]
using the command 
```
voila --template='classic' --theme='dark' --strip_resources='False' document.ipynb
```
doesn't generate a dark theme document.

**Comment by jtpio** [comment]
Thanks @YousefSaber for reporting.

It's possible the classic template does not support dark theme.

However the lab template does:

```bash
voila --template='lab' --theme='dark' --strip_resources='False' document.ipynb
```

![image](https://user-images.githubusercontent.com/591645/108231527-25269d80-7142-11eb-8239-317f71a8b0d2.png)

**Comment by YousefSaber** [comment]
@jtpio I know but I prefer the `classic` template, is there any possibility that `classic` template may implement a dark theme.

**Comment by martinRenou** [comment]
This is inherited from nbconvert. The `classic` template comes from there and does not include a dark theme. Maybe it's worth opening an issue there? Although I am not sure it will be implemented as it's mimicking the classic Jupyter Notebook style (which does not have a dark theme).
