### ISSUE TITLE
Token management or any other secured way to serve a Voilà application

### ISSUE THREAD

**Issue by brichet** [voila-dashboards/voila#825]
Hi,
Maybe I missed some improvements but I didn't find a way to authenticate users before using a Voilà application.
In my case I don't necessarily need a secure authentication but it would be good to be able to use a token (that enough security for my needs).
Is there any reason why this is not implemented ? 
There is some commented code about that in app.py with that line above : 
```
# TODO: do we want to have the token?
```
I made some modifications to add an option `--Voila.token=<unicode>` to let user add his own token, so if you think this feature can be interesting I can create a PR.
Nicolas

**Comment by GregSilverman** [comment]
Same question I had. I do however need secure authentication.

**Comment by brichet** [comment]
@GregSilverman you can try https://github.com/brichet/voila/tree/token_management, this enables a token with the option `--Voila.token=<unicode>`. This is currently not updated to the latest version of the master.

**Comment by GregSilverman** [comment]
Cool! Thanks!

**Comment by timkpaine** [comment]
https://github.com/voila-dashboards/voila/pull/724 can also be used

**Comment by brichet** [comment]
Fixed by https://github.com/voila-dashboards/voila/pull/1308
