### ISSUE TITLE
How to use custom python package

### ISSUE THREAD

**Issue by mareksubocz** [voila-dashboards/voila#836]
Hi, I modified a [jupyter widgets package](https://github.com/ocoudray/jupyter-drawing-pad). When I try to use [my version](https://github.com/mareksubocz/jupyter-drawing-pad) of it, voila somehow uses the original one available by pip. How can I force it to use my version? Also, i do it to post it on binder, so the simpler the resolution will be, the better.

Is there a way to fix it? I'll appreciate any help :)

**Comment by marckassay** [comment]
If you executed this in your root folder: `pip install jupyter_drawing_pad`, it will install the `jupyter_drawing_pad` package from pypi.org. You would need to install yours like so: ` pip install .`

**Comment by marckassay** [comment]
Oh, it looks like you're aware of that from your project's README you modified.

What does `pip show jupyter_drawing_pad` output?

**Comment by mareksubocz** [comment]
I did install my version locally, normal jupyter notebook works as intended. The problem occurs when i start the notebook using voila, which is weird, because I don't even have the pip version installed on my computer anywhere.

**Comment by mareksubocz** [comment]
When i run voila, I get this:
``` bash
WARNING:tornado.general:403 GET /voila/files/voila/jupyter-drawing-pad.js (::1): File not whitelisted
WARNING:tornado.access:403 GET /voila/files/voila/jupyter-drawing-pad.js (::1) 1.05ms
```
It looks like its changing the part of the file that I modified. How can I turn this off?

**Comment by marckassay** [comment]
Oh, good! I'm not familiar with binder deployments, but take a look at this section of voila's [docs](https://voila.readthedocs.io/en/stable/using.html#using-third-party-widgets-with-voila).

**Comment by mareksubocz** [comment]
It boils down to if it is possible to add this voila argument either inside the notebook itself or while starting voila by accessing url (instead of command line).

**Comment by marckassay** [comment]
If there is a `voila.json` file in the same folder as your notebook, I believe voila will attempt to read it as a configuration file. This test [file](https://github.com/voila-dashboards/voila/blob/master/tests/configs/general/voila.json) of theirs, happens to use the same option (`enable_nbextensions`) you posted above.

**Comment by mareksubocz** [comment]
It worked! Thank you so much!

For anybody looking for answer how to fix this, you need to name the file ```jupyter_config.json``` and put it in root of the github repo. More info [here](https://voila.readthedocs.io/en/stable/deploy.html).
