### ISSUE TITLE
How to tell voila to use the other browser?

### ISSUE THREAD

**Issue by pllim** [voila-dashboards/voila#843]
I have this in my `~/.jupyter/jupyter_notebook_config.py`:

```python
c.NotebookApp.browser = '/usr/bin/google-chrome'
```

But when I run `voila somenotebook.ipynb`, it stubbornly uses the default browser:

```
START /usr/bin/firefox ...
```

I don't have enough privilege to change the system default browser on this machine, so how do I tell `voila` to use what I have set for `jupyter`?

Hope you can help. Thanks!

**Comment by jtpio** [comment]
Thanks @pllim.

Maybe something like this would work? 

```python
voila --Voila.browser=/usr/bin/google-chrome
```

Or in a `voila.py` file:

```python
c.Voila.browser = '/usr/bin/google-chrome'
```

**Comment by pllim** [comment]
Yes, thank you!
