### ISSUE TITLE
New release with PR [#841]?

### ISSUE THREAD

**Issue by mcornudella** [voila-dashboards/voila#865]
Hi everyone. I would like to use the multi_kernel_manager_class configuration, in combination with  the [hotpot_km](https://github.com/voila-dashboards/hotpot_km) library in order to warm up kernels. Unfortunately, I've found that the latest release (0.2.7) available from PyPI doesn't contain it. Would it be possible to do a new release of voilà including PR [#841](https://github.com/voila-dashboards/voila/pull/841/files)?

**Comment by maartenbreddels** [comment]
Hi @mcornudella,

thanks for asking and showing interest in this feature.
@jtpio are there any other PR's open that we should merge, otherwise I'm ok with doing a release today or this week.

Regards,

Maarten

**Comment by mcornudella** [comment]
That would be great Maarten, thank you very much!

**Comment by jtpio** [comment]
Thanks, I think we can cut a new release.

Maybe that one could also go in: https://github.com/voila-dashboards/voila/pull/860

**Comment by edisongustavo** [comment]
Hello all! I'm also interested in a new release. Thanks for the great project too.

**Comment by jtpio** [comment]
Cutting `0.2.8` now.

**Comment by jtpio** [comment]
https://pypi.org/project/voila/0.2.8/

https://www.npmjs.com/package/@voila-dashboards/jupyterlab-preview/v/2.0.2
