### ISSUE TITLE
when moving rendered files to another directory the format changes?!

### ISSUE THREAD

**Issue by YousefSaber** [voila-dashboards/voila#875]
when I convert my notebook to HTML file in a specific directory it looks like this 
![image](https://user-images.githubusercontent.com/33742499/115995227-ba2e9280-a5da-11eb-9983-ac9945b03ef2.png)

when moving the HTML file to another directory the format changes to this?

![image](https://user-images.githubusercontent.com/33742499/115995247-cf0b2600-a5da-11eb-8b62-c97f7e1350f2.png)

voila version 0.2.9

**Comment by jtpio** [comment]
Thanks @YousefSaber.

Not sure it's directly related to Voila. Or maybe you were using `nbconvert` directly?

You can check if there are other files next to the HTML file, for example `.css` files. Those would also need to be moved so they can properly be referenced from the html file.

**Comment by YousefSaber** [comment]
@jtpio  
> Not sure it's directly related to Voila. Or maybe you were using nbconvert directly?


I was using Voila commands line didn't use `nbconvert` 
```
voila --strip_sources=False --theme=dark 1st\ Lab.ipynb
```
after executing the command line, a web application is opened then by right click choosing `save as ` an `.HTML` and `.css` files are generated. 

> You can check if there are other files next to the HTML file, for example .css files. Those would also need to be moved so they can properly be referenced from the html file.

yeah you are right I found the `.css` files in folder `1st Lab_files` containing all the `.css` files 
```
index.css  MathJax.js  require.min.js  theme-dark.css
```
isn't there anyway to embed the `.HTML` and `.CSS` files in one single document so moving and sharing documents can be easier and more convenient

**Comment by jtpio** [comment]
Ah ok thanks @YousefSaber for the details.

So it looks like you were using voila to render the notebook, and then download the HTML via a web browser?

> isn't there anyway to embed the .HTML and .CSS files in one single document so moving and sharing documents can be easier and more convenient

Another way would be to print to PDF using the browser. Or maybe check whether `nbconvert` could be used directly for the export as it might embed everything in one file.

**Comment by YousefSaber** [comment]
@jtpio alright thank you very much, `nbconvert` doesn't explicitly provide a way to produce dark theme templates, but I'll search into this, for now I'll close this issue.

**Comment by maartenbreddels** [comment]
it should be supported, `nbconvert --help-all | grep theme` should give you a hint, I think `--TemplateExporter.theme=dark` is the right flag.

**Comment by YousefSaber** [comment]
@maartenbreddels found it I could produce Dark theme documents by the command `--HTMLExporter.theme=dark` the full command line is 
```
jupyter nbconvert --to html --template lab --HTMLExporter.theme=dark 1st\ Lab.ipynb
```

thank you very much.
