### ISSUE TITLE
voila ipyvuetify ipydatagrid interference with each other. ipydatagrid kills ipyvuetify

### ISSUE THREAD

**Issue by joseberlines** [voila-dashboards/voila#877]
It looks like when importing ipydatagrid and ipyvuetify in the same notebook then voila does not render the ipyvuetify components.

I initially opened this issue in:
https://github.com/bloomberg/ipydatagrid/issues/231#issue-867607527

Thinking that it was an ipydatagrid issue but actually it might be a voila issue.

I am running the notebooks in a jupyterlab 3.0.10

![image](https://user-images.githubusercontent.com/33203439/116096381-8bcbb880-a6a9-11eb-9f17-b2e5f58e0e73.png)

Any idea?
@mariobuikhuizen

**Comment by joseberlines** [comment]
Btwin the screenshot it's not to be seen but on the right side the datagram tables are rendered down

**Comment by joseberlines** [comment]
This is a bit duplicate of https://github.com/bloomberg/ipydatagrid/issues/231

**Comment by maartenbreddels** [comment]
Does it work with `voila --enable_nbextensions=True` ?
