### ISSUE TITLE
Bqplot.PanZoom zoom doesn't work in jupyter notebook and voila

### ISSUE THREAD

**Issue by sntgluca** [voila-dashboards/voila#881]
**Describe the bug**
Dear bqplot and voila developers,
Not sure if this is a `bplot` problem or a `voila` issue, starting posting here to seek for feedback.

The _zoom_ functionality from the `bqplot.Panzoom` interaction widget doesn't seem to work in a `notebook` context or in `voila`.
It's possible to _pan_ and move around the graph but I can't find a way to _zoom_.

In `jupyter-lab`, including `voila-preview` it works as expected.

Tested with `bqplot==0.12.26` and `voila==0.2.10`.

**To Reproduce**
```python
from bqplot import *

x_sc = LinearScale()
y_sc = LinearScale()

ax_x = Axis(scale=x_sc)
ax_y = Axis(scale=y_sc, orientation="vertical")

x_data = np.arange(20)
y_data = x_data ** 2
scatter = Scatter(
    x=x_data,
    y=y_data,
    scales={"x": x_sc, "y": y_sc},
)

fig = Figure(axes=[ax_x, ax_y], marks=[scatter])
fig.interaction = bqplot.PanZoom(scales={"x": [x_sc], "y": [y_sc]})
fig
```

Is there anything that can be done about it?

**Comment by maartenbreddels** [comment]
Hi,

Did you see https://github.com/bqplot/bqplot/issues/1304 ? It's strange that it seems to be working in Jlab though.

cheers,

Maarten

**Comment by maartenbreddels** [comment]
Let's move the discussion to bqplot ok?

**Comment by sntgluca** [comment]
Thanks @maartenbreddels.
Damn, was searching all over the place for `PanZoom`.  Completely agree to keep the discussion in one place.
