### ISSUE TITLE
Missing font-awesome icons in voilà output

### ISSUE THREAD

**Issue by deeplook** [voila-dashboards/voila#887]
I want to use a font-awesome icon like `fas fa-external-link-alt` in HTML, so I'm using the code `<i class="fas fa-external-link-alt"></i>`. When I put this in a Jupyter Markdown cell it appears as an icon, but when clicking the Voilà button in Jupyter to render it (with Voilà 0.2.7) it is ignored in the output. Inspecting the HTML I see the element there. Same if I use it inside an `ipywidgets.HTML` element. I haven't tested by starting Voilà from the command-line. Do I need to specify somewhere I want to use font-awesome icons? (Tested only on JupyterLab 3.)

<img width="1064" alt="Screenshot 2021-05-15 at 00 09 25" src="https://user-images.githubusercontent.com/1001778/118336384-d8b8e700-b511-11eb-8c2e-8f609b50dfe0.png">

**Comment by jtpio** [comment]
Thanks @deeplook.

Would you mind trying with the latest `0.2.10` which should include the update to font awesome 5? https://github.com/voila-dashboards/voila/pull/870

**Comment by deeplook** [comment]
A quick smoke test with 0.2.10 appears to work fine with the `<i class="fas fa-external-link-alt"></i>` from above. That's awesome (of course). ;) Thanks!!
