### ISSUE TITLE
Uncaught ReferenceError: IPython is not defined

### ISSUE THREAD

**Issue by VitoKovacic** [voila-dashboards/voila#903]
Hi,

when i try to render a simple notebook 

```
import IPython.display
IPython.display.HTML('''
    <script type="text/javascript">
        IPython.notebook.kernel.execute("foo=11")
    </script>
''')
```

in the JS console Voila comes back with 
Uncaught ReferenceError: IPython is not defined

voila --version
0.2.10

Starting with
voila notebooks/ --enable_nbextensions=True --debug

**Comment by jtpio** [comment]
Thanks @VitoKovacic.

Yes this is normal since `IPython` is not available on the Voila frontend. This may work in the classic notebook for legacy reasons though.

> IPython.notebook.kernel.execute("foo=11")

Also voila prevents arbitrary code execution requests, so this would not be possible to execute.

**Comment by jtpio** [comment]
Depending on what you are trying to do, maybe using `ipywidgets` can be useful here?

**Comment by jtpio** [comment]
Closing as answered.

Support for calling `IPython` is not supported in Voila. Instead we recommend using `ipywidgets` for building interactive UIs: https://ipywidgets.readthedocs.io/en/stable/
