### ISSUE TITLE
display(Markdown(f'![]({relpth})') - works in Jupyter Lab (3.0.14) but not Voila (0.2.9)

### ISSUE THREAD

**Issue by jgunstone** [voila-dashboards/voila#904]
![image](https://user-images.githubusercontent.com/21370980/122106889-64c07600-ce12-11eb-8d60-c17f37e016eb.png)

relevant code:

```python
from IPython.display import display, Markdown
display(Markdown(f'![]({relpth})')
```

perhaps related to?
https://github.com/voila-dashboards/voila/issues/659
https://github.com/voila-dashboards/voila/issues/796

**Comment by gunstonej** [comment]
think i found the cause of the issue - 

image files named with a capital ".PNG" extension don't render in Voila, but do still render in Jupyter Lab

i.e. 
```python
from IPython.display import display, Markdown
display(Markdown(f'![](img.png)')   # works
display(Markdown(f'![](img.PNG)')   # doesn't work
```

i'll leave the issue open for now as this is unexpected behaviour
