### ISSUE TITLE
voila not able to run kernel if not running as root on Ubuntu.

### ISSUE THREAD

**Issue by mangecoeur** [voila-dashboards/voila#905]
I'm having this issue where ipywidgets don't work, but diagnosing more it seems voila is simply not starting a kernel for my notebook - none of the code is run (it's just rendering the notebook as it was saved).Similar issue when running as a server extension - I get the buttons to create a voila preview but it seems to just show the output of nbconvert. However it doesn't show any errors on start up so I don't know what could be going wrong.

It does work correctly when run as root (`sudo voila notebook.ipynb`).

I'm running on ubuntu 20.04 with a conda env with python 3.8 and voila from conda-forge.

**Comment by mangecoeur** [comment]
I'm getting nowhere solving this - there are no errors shown but the kernel is not launched when it should. This only makes sense if voila is trying to write somewhere it doesn't have permissions when it launches the kernel, but for some reason no traceback is shown.
Can someone at least point me to where in the code the kernel should be launched so i can try to add some logging?

**Comment by luphord** [comment]
Thanks @mangecoeur for following up and describing your findings! I have just spent hours facing the same frustrating problem as you did. Your comments pointed me in the right direction.

#### Issue
Voila does not execute any notebook cells, but displays a statically rendered version of the notebook. No error messages at all (even with `--debug`). Kernels appear to be started.

#### My setup
- Linux Mint 20.3
- Python 3.9.5
- Virtual environment created with `python -m venv`
-  All dependencies installed via `pip`, i.e. no `conda`
- Voila 0.3.1 (also tried 0.3.0 with same results)

#### Resolution
Running voila as root also worked for me. But as @mangecoeur writes, this is not related to any access rights, but to my *user level files* outside of the virtual environment which are simply not used when running as root. More specifically, `nbconvert` templates broke voila for me. By removing/renaming `.local/share/jupyter/nbconvert/templates/lab`, I could fix my setup.
