### ISSUE TITLE
Specify custom template on Binder deployment

### ISSUE THREAD

**Issue by fredgrub** [voila-dashboards/voila#908]
I'm trying to use a custom template to render my notebook through myBinder. However, I don't know how to specify the template in this case. When running locally I can specify by the command `--template=mytemplate` (where the template is located in one of the configuration points: in my case `~/miniconda3/envs/sandbox/share/jupyter/nbconvert/templates/mytemplate`). But when I'm going to specify the template on myBinder, I need to select it via `jupyter_config.json` as follows
```json
{
	"VoilaConfiguration": {
		"template": "mytemplate"
	}
}
```
However, there would be no way for me to add my template to one of the configuration points. So is there any way to specify a template present in the git directory? For example,
```text
.
|
├── DATA
│   └── ...
├── notebook1.ipynb
├── notebook2.ipynb
├── jupyter_config.json
├── notebook3.ipynb
├── notebook4.ipynb
├── requirements.txt
└── share
    └── jupyter
        ├── nbconvert
        │   └── templates
        │       └── mytemplate
        └── voila
            └── templates
                └── mytemplate
```

**Comment by jtpio** [comment]
Thanks @fredgrub.

> However, there would be no way for me to add my template to one of the configuration points

If your template is pip installable, then it will be placed at the right location on disk. As an example there is the `voila-material` template: https://github.com/voila-dashboards/voila-material

**Comment by fredgrub** [comment]
I understand, it would be harder than just adding a file to the repository. Anyway thank you very much, I managed to customize in an alternative way. I will mark this issue as closed.

**Comment by jtpio** [comment]
ok good to hear you found a solution.

Don't hesitate to post it here if you would like to!
