### ISSUE TITLE
JavaScript output is disabled in JupyterLab

### ISSUE THREAD

**Issue by dhirschfeld** [voila-dashboards/voila#917]
I'm trying to show a `bokeh` plot in an [`ipywidget.Output`](https://ipywidgets.readthedocs.io/en/latest/examples/Output%20Widget.html) and to render that with voila (in JupyterLab):
```python
import bokeh.plotting as plt
import ipywidgets as widgets

plt.output_notebook()

x = [1, 2, 3, 4, 5]
y = [6, 7, 2, 4, 5]
fig = plt.figure(
    title="Simple line example",
    x_axis_label='x',
    y_axis_label='y',
)
fig.line(x, y, legend_label="Temp.", line_width=2)
out = widgets.Output()
with out:
    plt.show(fig)

out
```

In the notebook it renders fine:

![image](https://user-images.githubusercontent.com/881019/123570015-c2899080-d80a-11eb-853e-3f3999e4c12d.png)

...but voila gives a `JavaScript output is disabled in JupyterLab` error:

![image](https://user-images.githubusercontent.com/881019/123570128-f4025c00-d80a-11eb-80f7-ab9ddaa58b67.png)

It would be a pretty big limitation if you can't use `ipywidgets` in a voila app! Is there a way to get this to work?

**Comment by jtpio** [comment]
Thanks @dhirschfeld.

> It would be a pretty big limitation if you can't use `ipywidgets` in a voila app! Is there a way to get this to work?

Probably this is an issue with Bokeh? iirc this was also mentioned before in https://github.com/voila-dashboards/voila/issues/244 with links to an `ipybokeh` project.

Jupyter Widgets have been working in Voila since the very start, with some example notebooks in https://github.com/voila-dashboards/voila/tree/master/notebooks

**Comment by jtpio** [comment]
> iirc this was also mentioned before in #244 with links to an `ipybokeh` project.

Ah looks like https://github.com/philippjfr/ipybokeh is now archived and https://github.com/bokeh/jupyter_bokeh is the new repo.

**Comment by jtpio** [comment]
Thanks for checking :+1: 

> I'll close this now as I think it may just be that bokeh isn't fully compatible with `ipywidgets`/`voila` :/

Maybe this will improve when Voila becomes a JupyterLab based app (#846) so it can reuse prebuilt lab extensions directly.

**Comment by dhirschfeld** [comment]
> *Maybe this will improve when Voila becomes a JupyterLab based app (#846)*

Thanks for the pointer, that looks promising indeed - subscribed! 👀

**Comment by dhirschfeld** [comment]
NB: I also didn't have any luck displaying a perspective widget so that issue seems a likely culprit.
