### ISSUE TITLE
Performance: Approximately 3 second delay between code completion and ipywidgets rendering in browser 

### ISSUE THREAD

**Issue by julian-west** [voila-dashboards/voila#929]
# Description

There is a long delay between the code execution completing and the ipywidgets rendering in the browser (approximately 3 seconds) - see screen recording below.

In the example below I have a very simple app to demonstrate the issue. 

The app renders some HTML text to signal the the beginning and end of the Python script and displays a single widget. There is a considerable time delay between the code completion and the actual widget rendering in the browser. There is at least a 3 second delay no matter which widget I use, even for the simplest possible webapp as demonstrated below.

<br>

![voila-slow-loading-widgets](https://user-images.githubusercontent.com/47723873/129016620-0a1a1907-aecf-4f82-afa2-96f72424c091.gif)

<br>

This issue is potentially related to issue #764 

I am not sure if this is an issue with Voila or IpyWidgets. There is no noticeable delay when rendering the same simple ipywidgets in a Jupyter notebook.

**Why is there a consistent delay before rendering the widgets? How can this time delay be reduced?**

# Reproducing the Simple Example App

## App Code

```python
# simple_app.py
import ipywidgets as widgets
from IPython.display import display, HTML

display(HTML("<h2> My Simple App</h2>"))

slider = widgets.IntSlider(description="x")
display(slider)

display(HTML("<p>Code execution completed</p>"))
```

## Requirements
```markdown
# requirements.txt
voila==0.2.10
```

## Deployment command
```
# set up virtual environment
pyenv virtualenv 3.8.8 voila-test
pyenv activate voila-test
pip install -r requirements.txt

# deploy voila app
voila simple_app.py --VoilaConfiguration.extension_language_mapping .py=python
```

## Testing environment
- Local machine (MacBook Pro Intel i7, 16GB RAM)
- Python version = 3.8.8
- Google Chrome (also observed in Firefox and Edge)

```markdown
# pip freeze
anyio==3.3.0
argon2-cffi==20.1.0
async-generator==1.10
attrs==21.2.0
bleach==4.0.0
certifi==2021.5.30
cffi==1.14.6
charset-normalizer==2.0.4
defusedxml==0.7.1
entrypoints==0.3
idna==3.2
ipython-genutils==0.2.0
Jinja2==3.0.1
jsonschema==3.2.0
jupyter-client==6.1.12
jupyter-core==4.7.1
jupyter-server==1.10.2
jupyterlab-pygments==0.1.2
MarkupSafe==2.0.1
mistune==0.8.4
nbclient==0.5.3
nbconvert==6.1.0
nbformat==5.1.3
nest-asyncio==1.5.1
packaging==21.0
pandocfilters==1.4.3
prometheus-client==0.11.0
ptyprocess==0.7.0
pycparser==2.20
Pygments==2.9.0
pyparsing==2.4.7
pyrsistent==0.18.0
python-dateutil==2.8.2
pyzmq==22.2.1
requests==2.26.0
requests-unixsocket==0.2.0
Send2Trash==1.8.0
six==1.16.0
sniffio==1.2.0
terminado==0.10.1
testpath==0.5.0
tornado==6.1
traitlets==5.0.5
urllib3==1.26.6
voila==0.2.10
webencodings==0.5.1
websocket-client==1.2.0
```

**Comment by julian-west** [comment]
Looks like that works! Increasing the @jupyterlab/services dependency to version 6.1.8 (latest stable release) almost completely removes rendering delay. Thanks a lot!

**Comment by jtpio** [comment]
Thanks @julian-west for the heads-up!

Would you like to open a PR to apply the change here in voila? So it can be part of the next release.

**Comment by jtpio** [comment]
Fixed by https://github.com/voila-dashboards/voila/pull/933

https://user-images.githubusercontent.com/591645/131682586-e4e5aa7c-562f-4646-90af-af9cfe676148.mp4
