### ISSUE TITLE
ipysheet==0.5.0 not rendering in Voila==0.2.11 in jupyterlab>3

### ISSUE THREAD

**Issue by gunstonej** [voila-dashboards/voila#945]
## Description

ipysheet ui displaying in jupyter lab but not in voila:

![image](https://user-images.githubusercontent.com/21370980/131982630-3b681492-c75f-440a-b361-1b0dc6a03b46.png)

## Reproduce

create a new environment: 

```
mamba create -n ipysheettest python jupyterlab>3 voila>=0.2.11 ipysheet>=0.5.0
```

launch jupyterlab in env and test ipysheet in a new notebook. click the render with Voila button.

```python
from IPython.display import display
import ipysheet
sheet = ipysheet.sheet()

sheet = ipysheet.sheet(rows=3, columns=4)
cell1 = ipysheet.cell(0, 0, 'Hello')
cell2 = ipysheet.cell(2, 0, 'World')
cell_value = ipysheet.cell(2,2, 42.)
sheet
```

## Expected behavior

the see the UI sheet object in Voila

## Context

- ipysheet ==0.5.0
- voila==0.2.11
- jupyterlab==3.1.10 
- Linux PORT4028 4.19.128-microsoft-standard SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux> Ubuntu 20.04 (also tested on Linux JupyterHub server running Ubuntu 20.04)

**Comment by jtpio** [comment]
Thanks @gunstonej for the report.

It seems to be working fine when testing locally in a new environment:

![image](https://user-images.githubusercontent.com/591645/131992977-b75e379f-a910-42aa-ba81-7cf9703664ec.png)

Did you start voila with the [`enable_nbextensions`](https://voila.readthedocs.io/en/latest/using.html#using-third-party-widgets-with-voila) flag?

**Comment by gunstonej** [comment]
perfect - thanks - that solves the issue :+1:

is there a way to globally change the configuration of the environment to `--enable_nbextensions=True` so you don't have to specify it on the command line?  

... and so that when using the Voilà Preview Extension:
![image](https://user-images.githubusercontent.com/21370980/132009163-9da4fc50-d6a6-44c7-a195-a05ca29b2832.png)
it still works?

**Comment by jtpio** [comment]
> is there a way to globally change the configuration of the environment to `--enable_nbextensions=True` so you don't have to specify it on the command line?

Creating a `jupyter_config.json` file in the same folder where Voila is started (or in a Jupyter config directory) with the following content should do the trick:

https://github.com/voila-dashboards/voila-material/blob/30942c202d44b51e5e839a6bf3ca8ead0c7c0264/jupyter_config.json#L3

**Comment by gunstonej** [comment]
perfect - thanks!
