### ISSUE TITLE
Add more UI tests

### ISSUE THREAD

**Issue by jtpio** [voila-dashboards/voila#948]
As a follow-up to #946, we should add more UI tests to the setup: https://github.com/voila-dashboards/voila/tree/master/ui-tests

One idea could be to make sure the examples notebooks are correctly rendered: https://github.com/voila-dashboards/voila/tree/master/notebooks

We can also test setting a different template or theme.

This will help detect visual regressions, for example with PRs introducing big changes like #846.

**Comment by trungleduc** [comment]
@jtpio I can take this task.

**Comment by jtpio** [comment]
That would be great, thanks!

**Comment by jtpio** [comment]
Closing as there are now a couple of UI tests in https://github.com/voila-dashboards/voila/blob/main/ui-tests/tests/voila.test.ts.

We can continue to iterate on them and add new ones as we go.
