### ISSUE TITLE
Wrong widget initial state

### ISSUE THREAD

**Issue by davidbrochart** [voila-dashboards/voila#976]
## Description

Running the `notebooks/basics.ipynb` notebook, I see:
![image](https://user-images.githubusercontent.com/4711805/134551298-9cd66947-c697-45ed-90e0-c50712addc77.png)

## Reproduce

1. `mamba install voila ipykernel ipywidgets pandas`
2. `voila notebooks/basics.ipynb`

## Expected behavior

When moving the slider, the value of `x2` updates, but initially we should see `x2 = 16` for `x = 4`.

## Context

- voila version 0.2.14
- Operating System and version: Ubuntu 21.04
- Browser and version: any browser

**Comment by jtpio** [comment]
Thanks @davidbrochart for reporting :+1: 

Probably something to do with the code of the example notebook.

Running the first cell in JupyterLab gives the same:

![image](https://user-images.githubusercontent.com/591645/134552622-33d8f915-19f2-4e1d-94d0-a4f2cd39bf40.png)

So we might want to update the notebook to avoid that kind of confusion.
