### ISSUE TITLE
Wrong branch for latest version of documentation on `readthedocs`

### ISSUE THREAD

**Issue by trungleduc** [voila-dashboards/voila#989]
Latest version of [Voila RTD](https://voila.readthedocs.io/en/latest/) is still pointing to `master` instead of `main`

**Comment by jtpio** [comment]
Thanks @trungleduc for reporting.

Looks like this might be related: https://github.com/voila-dashboards/voila/issues/958#issuecomment-921028509

It should now be switched to `main` explicitly: 

![image](https://user-images.githubusercontent.com/591645/135988573-d0302237-207c-45f2-8a4d-1bac1ad8f773.png)

**Comment by trungleduc** [comment]
Thanks, it works now.
