### ISSUE TITLE
0.3.0 Release Plan

### ISSUE THREAD

**Issue by jtpio** [voila-dashboards/voila#991]
`0.3.0a0` was just published: https://github.com/voila-dashboards/voila/releases/tag/v0.3.0a0

`main` now targets the `0.3.0` release. And there is the `0.2.x` branch to cut new patch releases for `0.2` if needed (`0.2.17`, `0.2.18`, ...).

## `0.3.0` milestone

For issues and PRs that should go to the `0.3.0` release, we add them to the `0.3.0` milestone: https://github.com/voila-dashboards/voila/milestone/4

This will be the case for anything major, or a PR that introduces backward incompatible changes with `0.2.x`.

## Making a new `0.3.0` pre-release

We use the Jupyter Releaser as documented in:

https://github.com/voila-dashboards/voila/blob/main/RELEASE.md#using-jupyter_releaser

As an example, the current version is `0.3.0a0`. If we want to release `0.3.0a1`, we do the following:

### Draft Changelog

With `next` as the version spec:

![image](https://user-images.githubusercontent.com/591645/136009831-d4d0b5cc-1369-4b5d-9f46-b38433e1118c.png)

We then wait for:

1. the PR to be created on the repo. Example: https://github.com/voila-dashboards/voila/pull/990
2. Tests to pass
3. Merge the changelog PR

### Full Release

Using the information in the body of the changelog PR, for example:

![image](https://user-images.githubusercontent.com/591645/136010048-1a29894c-47ac-4f4a-af71-6b4d89b8c587.png)

We use the Full Release workflow:

![image](https://user-images.githubusercontent.com/591645/136010167-be4dc245-ada8-4305-add4-5bf5b3f09272.png)

## Backporting changes to `0.2.x`

We use https://github.com/meeseeksbox to backport changes to the `0.2.x` branch if needed: https://github.com/voila-dashboards/voila/tree/0.2.x

## Making a new `0.2.x` release

We use the Jupyter Release, specifying the `0.2.x` when launching the workflows.

---

cc @voila-dashboards/voila-core 

Let me know if all of this makes sense, and if you would like to cut new releases with the releaser and need guidance. Don't hesitate to comment here otherwise.

**Comment by trungleduc** [comment]
Hello all, `0.3.0rc0` is released today. The release candidate phase is planned for about 2 weeks and we will try to have the final by early December.

**Comment by trungleduc** [comment]
Hello all, we had 3 weeks of RC for now, is it ok for you to release the final version now?

**Comment by jtpio** [comment]
Sounds good!

Let's get these 2 PRs in first?

- https://github.com/voila-dashboards/voila/pull/1039
- https://github.com/voila-dashboards/voila/pull/1038

**Comment by trungleduc** [comment]
Yes, I want to do a quick pass for the tests  on `Windows` too.

**Comment by jtpio** [comment]
The version spec to use in the releaser to make the final release will be `release`.

**Comment by trungleduc** [comment]
Thanks @jtpio, will do it today.

**Comment by jtpio** [comment]
Closing as `0.3.0` has now been released: https://github.com/voila-dashboards/voila/releases/tag/v0.3.0

Thanks @trungleduc!

**Comment by jtpio** [comment]
Create a new `0.3.x` milestone to track future `0.3.x` patches.
