### ISSUE TITLE
Benchmarks workflow overwrites the Binder badge comment

### ISSUE THREAD

**Issue by jtpio** [voila-dashboards/voila#994]
## Description

At the moment the benchmark workflow overwrites the Binder badge comment:

![image](https://user-images.githubusercontent.com/591645/136060682-a31dc928-b75e-403d-8cd1-48f27f12cfed.png)

## Reproduce

Example: https://github.com/voila-dashboards/voila/pull/993

## Expected behavior

This logic would need to handle other comments that are not benchmark comments:

https://github.com/voila-dashboards/voila/blob/4cf7eaf3a81c1c7748a6066f73399e37de1c0650/.github/workflows/benchmark-report.yml#L61-L70

## Context

Noticed in https://github.com/voila-dashboards/voila/pull/993#issuecomment-934547899

**Comment by trungleduc** [comment]
Thanks @jtpio  for reporting it, I will update the bot.

**Comment by jtpio** [comment]
Thanks!
